apache/flink-cdc

flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java

[debezium] Rename class RowDataDebeziumDeserializeSchema method extractBeforeRow variable name
Rename class RowDataDebeziumDeserializeSchema method extractBeforeRow
variable name afterSchema and after to beforeSchema and before
Fixed ververica/flink-cdc-connectors#198

[debezium] Rename class RowDataDebeziumDeserializeSchema method extractBeforeRow variable name

---

flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/DebeziumReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/enumerator/MySQLSourceEnumerator.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/split/MySQLRecords.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/split/MySQLSplitReader.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java

In current implementation, there're multiple binlog reader even in pure binlog read phase, This PR merge them to one to decrease the db pressure.

[mysql] Support binlog reader merge optimization

---

flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/dispatcher/EventDispatcherImpl.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/DebeziumReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySqlParallelSource.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/assigner/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumState.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumStateSerializer.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/events/EnumeratorAckEvent.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/events/SourceReaderReportEvent.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/offset/BinlogOffset.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/split/MySqlRecords.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/split/MySqlSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySqlParallelSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySqlParallelSourceTestBase.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/source/assigner/MySqlSnapshotSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/source/enumerator/MySqlParallelSourceEnumStateSerializerTest.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer.sql
pom.xml

change:
* Bump flink version to 1.13.1
* Do not send notify noMoreSplits signal
* Add JM/TM failover tests to check checkpoint works fine

[mysql] Add JM/TM failover tests to check checkpoint works fine

---

flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySqlParallelSource.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySqlSourceOptions.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySqlTableSource.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySqlParallelSourceTestBase.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java

Enable single server id for MySqlParallelSource for compatibility consideration

[mysql] Enable single server id for MySqlParallelSource

---

docs/content/connectors/mysql-cdc.md
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/dispatcher/SignalEventDispatcher.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSource.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactory.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java

* [mysql][doc] Add mysql cdc document for 2.0.0  
* [mysql] deprecate invalid startup options of MySqlSource

[doc] Add docs for cdc-2.0

---

flink-format-changelog-json/src/main/java/com/ververica/cdc/formats/json/ChangelogJsonDeserializationSchema.java

fix changelog-deserialize exception message typo.

[changelog] fix changelog-deserialize exception message typo.

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/Validator.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/MySqlValidator.java

Validator add extends Serializable

Validator add extends Serializable

---

docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/MySqlSource.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgresValueValidator.java

Fix [issue-322](https://github.com/ververica/flink-cdc-connectors/issues/322).
Summary:
Upgrade the debezium doc version to 1.5.

[docs]upgraded the Debezium doc version to 1.5.2.Final.

---

docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/MySqlSource.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgresValueValidator.java

Fix issue-322 in Release 2.0 branch.
Summary:
Upgrade the debezium doc version to 1.5.

[docs]upgraded the Debezium doc version to 1.5.2.Final.For Release 2.0 branch.

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/dispatcher/SignalEventDispatcher.java

Fixed SignalEventDispatcher code format.

[mysql] Fixed SignalEventDispatcher code format

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/dispatcher/SignalEventDispatcher.java

Improve the code format in SignalEventDispatcher

[mysql] Improve the code format in SignalEventDispatcher

---

docs/content/connectors/mysql-cdc.md

bin.yang dosc Public Key Retrieval is not allowed #278

[docs]  mysql8.0 Public Key Retrieval is not allowed 

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSource.java

ISSUE #326 
PR #350 
Fix database history missing problem for version release-2.0

[ISSUE-326] Fix database history missing problem for release-2.0

---

README.md

* Fixing broken readme link to the documentation

[Docs] Fix broken readme link

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/MySqlSourceTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/MySqlValidatorTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSourceTestBase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MysqlTimezoneITCase.java

commit f04fcca104f63c1f4a1fd87948c050229dcd6ebf  Fix #358 
commit  a5334c222207d4168837efb7d28bc7edd2723fe5 Improve test code

 [mysql] Fix the MySqlSnapshotSplitAssigner may assign duplicate splits

---

flink-connector-debezium/pom.xml
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
flink-sql-connector-mysql-cdc/pom.xml
flink-sql-connector-postgres-cdc/pom.xml

*Shade Kafka-related dependency.*

[common] Shade kafka-related dependency

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSourceFactory.java

Remove no need config option prefix `debezium.`

[mongodb] Remove no need config option prefix debezium.

---

docs/content/about.md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md

Improve the DataStream Source use JsonDeserializationSchema ouput json fomart.

[docs] Improve the CDC DataStream API docs

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/ObjectUtils.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/StatementUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer.sql

[mysql] Use MIN/MAX of split key and rowCount to judge the distribution of table

---

docs/Dockerfile
docs/build_docs.sh

We use latest packages to build documents. But some time the documents will  crash when use latest packages.
So this pr try to fix the packages used to build docuemnts.

[hotfix] fix documents crash issue

---

docs/Dockerfile
docs/README.md
docs/build_docs.sh
docs/docs_site.sh
pom.xml

[docs] Support build document website locally

[docs] Support build document website locally

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSourceTestBase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MysqlTimezoneITCase.java

[tests] Correct the argument order of assertArrayEqualInOrder/assertArrayEqualAnyOrder

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java

[mysql] Support wide table with huge columns

---

README.md
docs/content/about.md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md

Correct usage dataStream API for release-2.0 branch

[docs] Correct usage dataStream API for release-2.0

---

azure-pipelines.yml

To fix #445 , you can refer https://github.com/actions/virtual-environments/issues/1499 for more details

[build] Fix maven connection timeout issue in azure CI

---

README.md
docs/content/about.md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md
docs/content/formats/changelog-json.md
docs/content/tutorials/mysql-postgres-tutorial-zh.md
docs/content/tutorials/mysql-postgres-tutorial.md

Update the dependency version to 2.1.0

[docs] Update the dependency version to 2.1.0 in documentation

---

docs/content/connectors/mysql-cdc.md

add some explaination about the supporting to mysql HA cluster in Flink MySQL CDC

add docs to explain supporting to mysql HA cluster

---

flink-sql-connector-oracle-cdc/pom.xml

verified with shaded oracle-cdc connector manually.

[oracle] shade dependencies in oracle-cdc connector jar #519

---

docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md

translate tutorial mysql-postgres-tutorial.

[docs] add mysql-postgres-tutorial-zh

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

[mysql] Set server time zone information for connection pool factory

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBConnectorSourceTask.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBEnvelope.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorITCase.java

Fix NullPointException when heartbeat is enabled.
#579 
#585

[hotfix][mongodb] Fix NullPointException when heartbeat is enabled

---

flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorITCase.java
pom.xml
tools/ci/log4j.properties

Append log to console to track MongoDBConnectorITCase is timeout on Azure. #584

[build] MongoDBConnectorITCase is timeout on Azure

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer.sql

fix issue:https://github.com/ververica/flink-cdc-connectors/issues/516

[mysql] if colunm defined default value and nullable,when column value is null. flink-cdc catch field value is default

---

docs/content/about.md

add Flink CDC Version 2.1.* Supported Flink Versions

add supported Flink versions, Flink CDC Version 2.1.*

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

This PR aims to fix #628 
I have checked in local stanalone cluster with a datastream job

[mysql] Set default driver class name for PooledDataSource

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

backport to release-2.1 branch

[mysql] Set default driver class name for PooledDataSource (#659)

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/MongoDBSource.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/MongoDBSourceTest.java

Support connect to MongoDB do not require authentication.
#640

[mongodb][hotfix] Support connect to MongoDB do not require authentication

---

docs/content/connectors/mongodb-cdc.md

Some typos fixed for docs/content/connectors/mongodb-cdc.md

[docs] Fixed some typos for mongodb-cdc.md

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java

[mysql] change the CREATE record to READ record in upsertBinlog

---

flink-cdc-e2e-tests/pom.xml
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/SqlServerE2eITCase.java
flink-cdc-e2e-tests/src/test/resources/container-license-acceptance.txt
flink-cdc-e2e-tests/src/test/resources/ddl/sqlserver_inventory.sql

add sqlserver-connector e2e test.Link [issue-775](https://github.com/ververica/flink-cdc-connectors/issues/775).

[sqlserver-connector] add e2e test.

---

docs/content/connectors/mysql-cdc.md

This PR is same with #857 but target branch changes to release-2.1

[docs][mysql][2.1] add connection options

---

docs/content/connectors/oracle-cdc.md

[docs][oracle] add documents about oracle cdb (#790)

---

docs/content/quickstart/index.md
docs/content/quickstart/sqlserver-tutorial.md

Link (https://github.com/ververica/flink-cdc-connectors/issues/681)
Add sqlserver-cdc connector en tutorial.

[doc][SqlServer] add sqlserver en tutorial.

---

docs/content/connectors/index.md
docs/content/connectors/sqlserver-cdc.md

Add sqlserver-cdc connector documentation.Link to [issues-682](https://github.com/ververica/flink-cdc-connectors/issues/682).

[docs][sql-server] add sqlserver-cdc connector document.

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/internal/DebeziumChangeFetcher.java

[common] DebeziumChangeFetcher's emit delay and fetch delay should be unavailable during the snapshot phase

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java

[hotfix][mysql] snapshotState should return unfinishedSplits

---

flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorITCase.java

Fix unstable tests of MongoDBConnectorITCase (#919)

[mongodb][test] Fix unstable tests of MongoDBConnectorITCase (#919)

---

docs/content/quickstart/tidb-tutorial.md
docs/content/快速上手/tidb-tutorial-zh.md

issue https://github.com/ververica/flink-cdc-connectors/issues/899 .

[tidb][docs] Add tidb connector tutorial.

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/polardbx/PolardbxSourceTCase.java

[mysql][test] Remove class PolardbxSourceTCase debug print.

[mysql][test] Remove class PolardbxSourceTCase debug print.

---

flink-cdc-e2e-tests/pom.xml
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/TIDBE2eITCase.java
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/TiDBE2eITCase.java
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
flink-cdc-e2e-tests/src/test/resources/ddl/tidb_inventory.sql
flink-cdc-e2e-tests/src/test/resources/docker/tidb/pd.toml
flink-cdc-e2e-tests/src/test/resources/docker/tidb/tidb.toml
flink-cdc-e2e-tests/src/test/resources/docker/tidb/tikv.toml
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/testutils/UniqueDatabase.java
flink-sql-connector-tidb-cdc/pom.xml
tools/ci/test_controller.sh

Issue https://github.com/ververica/flink-cdc-connectors/issues/932. Please just review lastest commit.

[tidb] Add tidb cdc connector e2e test.

---

flink-sql-connector-oceanbase-cdc/pom.xml
pom.xml

Try with snapshot version, will replace with release version after ci passes, fix #989

[tests] fix NPE caused by oblogclient in OceanBase tests

---

docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/oceanbase-cdc.md
docs/content/connectors/oracle-cdc.md
docs/content/connectors/postgres-cdc.md
docs/content/connectors/sqlserver-cdc.md
docs/content/connectors/tidb-cdc.md

Doc improvement

---

flink-connector-oceanbase-cdc/pom.xml
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/OceanBaseTestBase.java

[oceanbase] Remove useless dependency and code of test.

[oceanbase] Remove useless dependency and code of test.

---

flink-connector-oceanbase-cdc/pom.xml
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/OceanBaseTestBase.java

(cherry picked from commit 446a1f02f2f791f13c01fdd975aaee5890f9edaa)

[oceanbase] Remove useless dependency and code of test. (#1018)

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/AssignerStatus.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializerTest.java

[mysql][hotfix] serialize isSuspended flag for MySqlBinlogSplit

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/config/BaseSourceConfig.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/DataSourceDialect.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/JdbcDataSourceDialect.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/JdbcSourceRecordEmitter.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/connection/JdbcConnectionPools.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/assigner/SnapshotSplitAssigner.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/FinishedSnapshotSplitInfo.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SnapshotSplitState.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/StreamSplitState.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/metrics/SourceReaderMetrics.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/metrics/SoureReaderMetricConstants.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/JdbcSourceSplitReader.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceStreamFetcher.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/utils/SourceRecordUtils.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/config/MySqlSourceConfigFactory.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/config/ServerIdRange.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/fetch/MySqlScanFetchTask.java

[cdc-base] Polish platform code.

[cdc-base] Polish platform code.

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/utils/ResolvedSchemaUtils.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSourceFactory.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactory.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactory.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableFactory.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableFactoryTest.java
flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/table/TiDBTableSourceFactory.java

[common] Apply filter on ResolvedSchema to keep physical columns only

---

docs/content/connectors/mongodb-cdc.md

Update document about MongoDB database and collection regex filter.

[docs][mongodb] Update document about MongoDB database and collection regex filter for master.

---

docs/content/connectors/mongodb-cdc.md

Update document about MongoDB database and collection regex filter for release 2.2.0

[docs][mongodb] Update document about MongoDB database and collection regex filter for release 2.2.0

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java

Throw RuntimeException timely in snapshot scan phase

[mysql] Throw RuntimeException timely in snapshot scan phase

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer.sql

Unchanged back port of #1109 on release-2.2

[BP-2.2][MySQL] Catch and hold exception in chunk splitter thread and rethrow in getNext()

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSource.java

Unchanged back port of #1116 on release-2.2

[mysql] Add heartbeatInterval field to equals() and hashCode()

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorDeserializationSchema.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTimeZoneITCase.java

[mongodb] Fix UnsupportedTemporalTypeException when define Datetime/Timestamp as String

---

docs/content/connectors/mongodb-cdc.md

Fix meta field collection_name of metadata sql example for branch release-2.1
[issue](https://github.com/ververica/flink-cdc-connectors/issues/1286)

[mongodb][doc] Fix meta field collection_name of metadata sql example

---

flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseJdbcConverter.java

fix string encoding in change events reading, close #1266

[oceanbase] fix string encoding

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/JdbcSourceSplitReader.java

Fix a typo:  'currenFetcher' -> 'currentFetcher' in flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/JdbcSourceSplitReader.java

[hotfix][cdc-base] Fix typo 'currenFetcher' -> 'currentFetcher'

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBConnectorSourceTask.java

Fixes #1237.
Permission optimization of single database is specified.

[mongodb] Permission optimization of single database is specified

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/config/JdbcSourceConfigFactory.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/options/SourceOptions.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/MySqlSourceBuilder.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceBuilder.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/config/MySqlSourceConfigFactory.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/config/MySqlSourceOptions.java

[typo]Fix typo.

---

flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java

[dbz] Patch for DBZ-5126 to fix memory leak problem. (#939)

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/MySqlSnapshotSplitReadTask.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/context/StatefulTaskContext.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java

issues :  #1219 
This PR supports streaming merge during snapshot split reads
Changes:
1、Change snapshot split queue size = splitSize + 1024
2、Once a batch of data is obtained, it can be merged immediately without waiting for all data to be collected

[mysql] Streaming merge during snapshotSplit read (#1219)

---

.github/workflows/build_docs.yml

add  path filter to build doc workflow.  run build_docs.sh only if current PR modified docs

[build]run build_docs.sh only if current PR modified docs (#343)

---

docs/content/connectors/tidb-cdc.md

Signed-off-by: Yi Xie <xieyi01@rd.netease.com>
fix a typo in tidb-cdc.md

[docs]fix a typo in tidb-cdc.md 

---

docs/content/connectors/sqlserver-cdc.md

[docs] Fix a typo in sqlserver-cdc.md.

[docs] Fix a typo in sqlserver-cdc.md.

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/utils/ObjectUtils.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/MySqlChunkSplitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/ObjectUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlChunkSplitterTest.java

Link issue https://github.com/ververica/flink-cdc-connectors/issues/1031.

[mysql] Fix dead loop when splitting chunks.

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorDeserializationSchema.java

Closing https://github.com/ververica/flink-cdc-connectors/issues/1384

[mongodb] allow document field defined as string type in flink

---

flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/MongoDBSourceExampleTest.java

Example tests for MongoDBSource.
Closed #750.

[mongodb] Example tests for MongoDBSource

---

docs/content/connectors/sqlserver-cdc.md

Link https://github.com/ververica/flink-cdc-connectors/issues/1400 .

[docs] Add step up SQLServer Database cdc document in sqlserver-cdc.md.

---

flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/TiKVRichParallelSourceFunction.java

[tidb] Fix NPE when the specified table not found (#1410)

---

flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/OracleE2eITCase.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/internal/DebeziumChangeFetcher.java
flink-connector-oracle-cdc/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java

try to fix unstable tests #1345

[test][oracle] Fix unstable tests OracleE2eITCase due to reuse container

---

docs/content/connectors/index.md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/oceanbase-cdc.md
docs/content/connectors/oracle-cdc.md
docs/content/connectors/postgres-cdc.md
docs/content/connectors/sqlserver-cdc.md
docs/content/connectors/tidb-cdc.md

Since the debezium version has not been upgraded to 1.6 when it was released in 2.2, the link about debezium in this document is still 1.5. In addition, the version of CDC connector is unified as 2.2.1

[docs] translate mysql cdc doc to Chinese.

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/polardbx/PolardbxSourceITCase.java

rename PolardbxSourceTCase to PolardbxSourceITCase

[hotfix][test] rename PolardbxSourceTCase to PolardbxSourceITCase

---

.github/ISSUE_TEMPLATE/bug_report.md

[docs][typo] fix typo in bug report doc

---

docs/content/connectors/mysql-cdc(ZH).md

1.Repair page display
2.Page Jump can jump normally in my local and GitHub tests, but it can't jump normally in the official website page. Therefore, I changed the jump related code. I can test the jump here, but I can't guarantee whether the official website page can jump normally
@leonardBang 
I need help

[hotfix][docs] Fix page display errors and improve page Jump mode

---

docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md

in master branch, the server-time-zone's default value has changed, however the description of the configuration in doc haven't updated. So I do that.
[](url
)

[mysql][doc] update mysql doc server-time-zone description

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/utils/SourceRecordUtils.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtilsTest.java

[cdc-base][mysql] Fix split key comparison when may contain different types

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/SnapshotPendingSplitsState.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/offset/BinlogOffset.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSchemaLessSnapshotSplit.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSnapshotSplit.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplit.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializerTest.java

The optimization to reduce JM memory usage, this PR aims to resolve #865

[mysql] Reduce the memory usage of JM by sharing table schemas between splits

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlSource.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java

This PR aims to delay the captured tables enumeration from startup to runtime

[mysql] Enumerate captured tables lazily

---

flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlDefaultValueConverter.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer.sql

This PR fix the error when parsing ddl which uses string default values for numeric types.

[mysql] fix parsing ddl error when use string default values for numeric types

---

tools/ci/test_controller.sh

[ci] Polish test_controller.sh,remove useless code.

[ci] Polish test_controller.sh,remove useless code.

---

flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLDeserializationConverterFactory.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableSource.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/PostgresTestBase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-connector-postgres-cdc/src/test/resources/ddl/column_type_test.sql

[[add geometry type support.](https://github.com/ververica/flink-cdc-connectors/issues/1539)](https://github.com/ververica/flink-cdc-connectors/issues/1539)

[pg-connector] add geometry type support.

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceScanFetcher.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/utils/SourceRecordUtils.java

Apply changs in #1231 to cdc-base.

[cdc-base] Adopt streaming merge during snapshotSplit scan to avoid OOM (#1219)

---

docs/content/connectors/mysql-cdc(ZH).md

update doc for scan.incremental.snapshot.chunk.size

[doc]update doc for scan.incremental.snapshot.chunk.size

---

docs/content/connectors/oceanbase-cdc(ZH).md

[doc][oceanbase] add oceanbase-cdc-zh

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceStreamFetcher.java

Apply changes in #1392 to cdc-base.

[cdc-base] Optimize pure binlog phase check logic to improve performance

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceScanFetcher.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceStreamFetcher.java

Apply changes in #1358 to cdc-base.

[cdc-base] Release the debezium reader thread resources after reading finished

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/assigner/HybridSplitAssigner.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/assigner/SnapshotSplitAssigner.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializer.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/assigner/state/SnapshotPendingSplitsState.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SchemaLessSnapshotSplit.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SchemalessSnapshotSplit.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SnapshotSplit.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SourceSplitBase.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SourceSplitSerializer.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/SnapshotPendingSplitsState.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSchemalessSnapshotSplit.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSnapshotSplit.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplit.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializerTest.java

Apply changes in #1523 to cdc-base.

[cdc-base] Reduce the memory usage of JM by sharing table schemas between splits

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/JdbcIncrementalSourceReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java

Resolve project compilation ⚠️ trivial code submission

MySqlSourceReader The project code optimization   

---

docs/content/connectors/db2-cdc.md

[hotfix][docs] fix db2 doc download link

---

docs/content/about.md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/formats/changelog-json.md
docs/content/quickstart/db2-tutorial.md
docs/content/quickstart/mongodb-tutorial.md
docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/quickstart/oceanbase-tutorial.md
docs/content/quickstart/oracle-tutorial.md
docs/content/quickstart/polardbx-tutorial.md
docs/content/quickstart/sqlserver-tutorial.md
docs/content/quickstart/tidb-tutorial.md
docs/content/快速上手/mongodb-tutorial-zh.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md
docs/content/快速上手/oceanbase-tutorial-zh.md
docs/content/快速上手/oracle-tutorial-zh.md
docs/content/快速上手/polardbx-tutorial-zh.md
docs/content/快速上手/sqlserver-tutorial-zh.md
docs/content/快速上手/tidb-tutorial-zh.md
flink-cdc-e2e-tests/pom.xml
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
pom.xml

[common] Bump Flink version to 1.16.0

---

docs/content/connectors/mongodb-cdc.md

Add docs for MongoDB incremental source

[docs][mongodb] Add docs for MongoDB incremental source

---

flink-connector-tidb-cdc/pom.xml
flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/TiKVChangeEventDeserializationSchema.java
flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/TiKVSnapshotEventDeserializationSchema.java
flink-connector-tidb-cdc/src/test/java/com/ververica/cdc/connectors/tidb/table/TiDBConnectorRegionITCase.java

[tidb] Fix tidb unstable test.

[tidb] Fix tidb unstable test.

---

docs/content/connectors/db2-cdc.md
flink-connector-db2-cdc/src/test/java/com/ververica/cdc/connectors/db2/Db2SourceTest.java

[db2] Fix stream api example in db2 doc.

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlBinlogSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java

[fix][mysql] Fix "MySqlBinlogSplitAssigner" reassign split after exception restart

---

flink-connector-db2-cdc/src/main/java/com/ververica/cdc/connectors/db2/table/Db2TableSource.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSource.java
flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseTableSource.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/table/OracleTableSource.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableSource.java

Improve build changelog mode

---

flink-connector-tidb-cdc/pom.xml

[ci][tidb] Fix dns cache works incorrect in latest jdk 8.

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/CollectionDiscoveryUtils.java

Remove redundant code snippet and improve code structure

[mongodb] Improve code structure

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlChunkSplitter.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/assigner/splitter/OracleChunkSplitter.java

These are some wrong comments.

[mysql/oracle] Fix the wrong comments in ChunkSplitter

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/schema/MySqlTypeUtils.java

[mysql] Add note and test for MySQL TINYINT(1) type to Flink SQL Boolean type

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java

[tests][mysql] Skip unnecessary IT Case which uses legacy debezium source

---

docs/content/about.md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/formats/changelog-json.md
docs/content/quickstart/db2-tutorial.md
docs/content/quickstart/mongodb-tutorial.md
docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/quickstart/oceanbase-tutorial.md
docs/content/quickstart/oracle-tutorial.md
docs/content/quickstart/polardbx-tutorial.md
docs/content/quickstart/sqlserver-tutorial.md
docs/content/quickstart/tidb-tutorial.md
docs/content/快速上手/mongodb-tutorial-zh.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md
docs/content/快速上手/oceanbase-tutorial-zh.md
docs/content/快速上手/oracle-tutorial-zh.md
docs/content/快速上手/polardbx-tutorial-zh.md
docs/content/快速上手/sqlserver-tutorial-zh.md
docs/content/快速上手/tidb-tutorial-zh.md
flink-cdc-e2e-tests/pom.xml
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/MySqlE2eITCase.java
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
pom.xml
tools/azure-pipelines/jobs-template.yml

The PR to move to 1.17.0 flink

[common] Bump flink to 1.17.0

---

flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseDeserializationRuntimeConverter.java
flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/RowDataOceanBaseDeserializationSchema.java
flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseRecord.java
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseConnectorITCase.java

[oceanbase] use real charset to convert change record

---

docs/content/quickstart/oceanbase-tutorial.md
docs/content/快速上手/oceanbase-tutorial-zh.md
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/OceanBaseTestBase.java
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseConnectorITCase.java

Use OceanBase 4.0.0.0 CE and oblogproxy 1.1.0 for 4x in tests.

[test][oceanbase] update oceanbase and oblogproxy docker image

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactory.java

[hotfix][mysql-cdc] Use session timezone instead of local time zone as the default server time zone

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java

[mysql-cdc] Add handler for catching async exceptions in snapshot reading executor

---

flink-connector-mysql-cdc/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/ColumnType.java
flink-connector-mysql-cdc/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventDataDeserializer.java
flink-connector-mysql-cdc/src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventDataDeserializerTest.java

[mysql-cdc] Add MYSQL_TYPE_TYPED_ARRAY column type when parsing the table map event

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/LegacyMySqlTestBase.java

Shutdown mysql container timely for legacy mysql tests

[tests][mysql] Shutdown mysql container timely for legacy mysql tests

---

flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/OracleDialect.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/OracleScanFetchTask.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/OracleSourceFetchTaskContext.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/utils/OracleUtils.java

[oracle] close the oracle connection after the backfill task finished

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactory.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java

Supplement startup mode exception information

Supplement startup mode exception information

---

.gitignore
.idea/vcs.xml

Add PullRequestNavigationLink for IDEA
Before：
After：

[build] Add IssueNavigationLink for IDEA

---

docs/content/connectors/postgres-cdc.md

please merge into master tag and release-2.4 tag

Update Postgres CDC  SQL demo default conditions with slot.name

---

docs/content/connectors/postgres-cdc.md

please merge into release-2.4 branches

Update Postgres CDC SQL demo default conditions with slot.name in release-2.4 branches

---

flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/SqlServerSourceBuilder.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableFactory.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableSource.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableFactoryTest.java

[hotfix][sqlserver]fix sqlserver close idle and chunk key column missing

[hotfix][sqlserver]fix sqlserver close idle and chunk key column missing

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlBinlogSplit.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/NewlyAddedTableITCase.java

[mysql] Remove the finished snapshot splits for the binlog split when restoring from the checkpoint

---

flink-connector-debezium/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
flink-connector-oracle-cdc/src/main/java/io/debezium/connector/oracle/logminer/LogMinerChangeRecordEmitter.java

[oracle] Fix class conflict when using multi cdc sql jar

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/events/BinlogSplitAssignedEvent.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/NewlyAddedTableITCase.java

[mysql] skip closing reader when the reader received the binlog split

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/internal/Handover.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/LegacyMySqlSourceTest.java

[debezium] Fix DebeizumSourceFunction can not do savepoint after close

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/MongoDBSource.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorDeserializationSchema.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorFullChangelogDeserializationSchema.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/utils/BsonUtilsTest.java

This PR contains following changes:
* Adds class visibility annotations
* Adds unit tests for utility classes

[mongo] Improve test coverage & add class visibility annotations

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/StatementUtils.java

According to the opinion of the audit, I modified the reference of the method.

Fix issues(2381)

---

flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/utils/SqlServerTypeUtils.java

Add support bigint type as table split column

[sqlserver] Add support bigint type as table split column

---

flink-cdc-e2e-tests/pom.xml
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/PostgresE2eITCase.java
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
tools/azure-pipelines/jobs-template.yml
tools/ci/stage.sh

Recently, our CI is pretty unstable, and I' ll try to fix it.

try to fix e2e tests

---

flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/PostgresSourceBuilder.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/config/PostgresSourceConfigFactory.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactory.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableSource.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java

support pg https://github.com/ververica/flink-cdc-connectors/issues/1731

[Postgres] Close idle readers when snapshot finished.

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/connection/ConnectionPoolId.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/connection/JdbcConnectionFactory.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/connection/JdbcConnectionPoolFactory.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/JdbcConnectionPoolTest.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/PostgresConnectionPoolFactory.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/source/PostgresDialectTest.java

Fix https://github.com/ververica/flink-cdc-connectors/issues/2428

[postgres] Reuse pool connection based on database in postgres cdc

---

flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/utils/SqlServerUtils.java

[sqlserver] Fix get latest lsn

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/event/ChangeEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DataChangeEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DataRecord.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/Event.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/OperationType.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/SchemaChangeEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/TableId.java

Introduce Event API for CDC 3.0 which represents the data in the pipeline.
This closes #2624

[3.0][cdc-common] Introduce Event related APIs for Flink CDC 3.0

---

flink-cdc-runtime/pom.xml
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/SchemaOperator.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/SchemaOperatorFactory.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/coordinator/SchemaManager.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/coordinator/SchemaOperatorCoordinator.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/coordinator/SchemaOperatorCoordinatorProvider.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/event/FlushSuccessEvent.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/event/ReleaseUpstreamEvent.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/event/SchemaChangeRequest.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/event/SchemaChangeResponse.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/event/SinkWriterRegisterEvent.java
flink-cdc-runtime/src/test/resources/log4j2-test.properties

[3.0][cdc-runtime] Provide schema evolution framework API

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/source/DataSource.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/source/EventSourceProvider.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/source/FlinkSourceFunctionProvider.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/source/FlinkSourceProvider.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/source/MetadataAccessor.java

Introduce DataSource related APIs for Flink CDC 3.0.
This closes #2625

[3.0][cdc-common] Introduce DataSource related APIs for Flink CDC 3.0

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/sink/DataSink.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/sink/EventSinkProvider.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/sink/FlinkSinkFunctionProvider.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/sink/FlinkSinkProvider.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/sink/MetadataApplier.java

Introduce Event DataSink APIs for Flink CDC 3.0
This closes #2626

[3.0][cdc-common] Introduce Event DataSink APIs for Flink CDC 3.0

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Column.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/MetadataColumn.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/PhysicalColumn.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Schema.java

[3.0][cdc-common] Introduce Schema API for CDC 3.0

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/DataSinkFactory.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/DataSourceFactory.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/Factory.java

Introduce Connector Factory APIs
This closes #2640

[3.0][cdc-common] Introduce Connector Factory APIs

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DataChangeEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/RecordData.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Schema.java

This PR aims at fixing #2628's comment

[cdc-common] Keep columns of Schema in fixed order

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/event/GenericRecordData.java

Refer to #2644 . 
I'm not sure if we need to implement other types like BinaryDataRecord at this stage. If necessary, please contact me and I will implement it.
cc plz. @lvyanquan @GOODBOY008

[3.0][cdc-common] Add GenericDataRecord to describe the data.

---

flink-cdc-cli/pom.xml
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/CliExecutor.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/CliFrontend.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/CliFrontendOptions.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/PipelineDefinitionParser.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/utils/ConfigurationUtils.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/utils/FlinkEnvironmentUtils.java
flink-cdc-cli/src/test/java/com/ververica/cdc/cli/CliFrontendTest.java
flink-cdc-cli/src/test/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-full.yaml
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-minimized.yaml
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-with-optional.yaml
flink-cdc-cli/src/test/resources/flink-home/conf/flink-conf.yaml
flink-cdc-cli/src/test/resources/global-config/global-config.yaml
flink-cdc-cli/src/test/resources/log4j2-test.properties

This pull request implements #2607, which is the CLI frontend of Flink CDC, including:
- Parser interface and YAML implementation for parsing pipeline definition files into objects
- Implementation of CLI frontend
~~This is created as a draft because it is blocked by #2656 and #2659.~~
Converted to PR as all blocking PRs are merged.

[cli] Implementation of CLI frontend

---

tools/ci/stage.sh

close #2671 
[build] Enable tests for CDC 3.0 modules

[build] Enable tests for CDC 3.0 modules

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/testutils/UniqueDatabase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/resources/ddl/customer.sql

Add tests for latest offset strategy.

[postgres] Add tests for latest offset strategy

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/annotation/Experimental.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/annotation/Internal.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/annotation/Public.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/annotation/PublicEvolving.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/annotation/VisibleForTesting.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/types/VarBinaryType.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/types/VarCharType.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlRecordEmitterTest.java
pom.xml
tools/maven/checkstyle.xml
tools/maven/suppressions.xml

Add header copyright check for java files

[build] Add header copyright check for java files

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Column.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/MetadataColumn.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/PhysicalColumn.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Schema.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/utils/SchemaUtils.java
flink-cdc-common/src/test/java/com/ververica/cdc/common/utils/SchemaUtilsTest.java

Add SchemaUtil class to perform schema evolution.
@leonardBang @PatrickRen @GOODBOY008 CC.

[3.0][cdc-common] add SchemaUtil to perform schema evolution.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/src/test/java/com/ververica/cdc/connectors/vitess/VitessSourceTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/src/test/java/com/ververica/cdc/connectors/vitess/VitessTestBase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/src/test/java/com/ververica/cdc/connectors/vitess/container/VitessContainer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/src/test/java/com/ververica/cdc/connectors/vitess/table/VitessConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/src/test/java/com/ververica/cdc/connectors/vitess/table/VitessTableFactoryTest.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/VitessE2eITCase.java

[hotfix] Fix invalidate package name

[hotfix] Fix invalidate package name

---

docs/content/about.md

We don't have version 2.5.0, which needs to be modified here.

[hotfix][docs] Change to the correct version

---

docs/content/quickstart/oracle-tutorial.md
docs/content/快速上手/oracle-tutorial-zh.md

Back support to 2.4
This closes #2727.
(cherry picked from commit 9aed54d70f350688f645e8d12fedd6461e12512a)

[docs][oracle] Fix oracle cdc quick start (#2727)

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/labeler.yml
.github/workflows/build_docs.yml
.github/workflows/label.yml

Add an action to auto label pr with connector type based on the files it changed for user searching.
For example:

[github] Add labeler for pull-request

---

.github/labeler.yml

Fix the failure of CI.
@leonardBang CC.

[github] Use the correct format for labeler.yml.

---

flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineComposer.java

fix a bug. 
@PatrickRen @leonardBang CC.

[cdc-composer] use the right class to find sink connector JAR.

---

flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/sink/DataSinkWriterOperator.java

maintain a set of TableId in DataSinkWriterOperator to make sure that a CreateTableEvent is sent before all DataChangeEvents with the same TableId.

[cdc-runtime] maintain a set of TableId in DataSinkWriterOperator

---

flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/translator/DataSinkTranslator.java

A fix to support TwoPhaseCommittingSink for DataSink.

[cdc-composer] use DataSinkWriterOperatorFactory to replace all SinkWriterOperatorFactory.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/SpecificStartingOffsetITCase.java

SpecificStartingOffsetITCase.testStartingFromSpecificOffset sometimes failed in CI. Try to fix it.

[hotfix] Fix test failure in SpecificStartingOffsetITCase

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/DebeziumUtilsTest.java

MysqlTableSource return metadata in a fixed order

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/data/LocalZonedTimestampData.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/types/DataTypes.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/types/utils/DataTypeUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/factory/DorisDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisDataSinkOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisEventSerializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisRowConverter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/resources/META-INF/services/com.ververica.cdc.common.factories.Factory
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/com/ververica/cdc/connectors/doris/sink/DorisRowConverterTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/pom.xml
pom.xml

Authered and committed by @JNSimba, copy from https://github.com/ververica/flink-cdc-connectors/pull/2729 to rebase master and squash commit.

[pipeline-connector][doris] add doris pipeline connector.

---

tools/maven/suppressions.xml

[build][hotfix] Remove useless suppressions.

[build][hotfix] Remove useless suppressions.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventDataDeserializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventMetadataDeserializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/github/shyiko/mysql/binlog/event/deserialization/TableMapEventDataDeserializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/ddl/binlog_metadata_test.sql

[mysql] fix deserialization issue on table metadata binlog event

---

docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/oceanbase-cdc.md
docs/content/connectors/oracle-cdc.md
docs/content/connectors/postgres-cdc.md
docs/content/connectors/sqlserver-cdc.md
docs/content/pipelines/index.md
docs/content/pipelines/mysql-pipeline(ZH).md
docs/content/pipelines/mysql-pipeline.md
docs/index.md

Add documents for MySql pipeline connector

[3.0][docs] Add documents for MySql pipeline connector

---

README.md

[3.0][docs] fix yaml tables parameter in readme

---

README.md

cherry pick readme commits from master to release-3.0

cherry pick readme commits from master to release-3.0

---

flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/serializer/data/binary/BinaryRecordDataSerializer.java

minor code refractor in BinaryRecordDataSerializer

[Rumtime] Hotfix in BinaryRecordDataSerializer with code refractor

---

docs/content/pipelines/doris-pipeline(ZH).md
docs/content/pipelines/doris-pipeline.md

[bp-3.0][hotfix][docs] Change the title to keep the document format uniform

---

docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/table/AppendMetadataCollector.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/table/MetadataWithRowDataConverter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlReadableMetadata.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java

[mysql] Support metadata 'operation' virtual column for MySql Connector.

---

docs/content/quickstart/mysql-doris-pipeline-tutorial.md
docs/content/quickstart/mysql-starrocks-pipeline-tutorial.md
docs/content/快速上手/mysql-doris-pipeline-tutorial-zh.md
docs/content/快速上手/mysql-starrocks-pipeline-tutorial-zh.md
docs/site/index.html

this closes https://github.com/ververica/flink-cdc-connectors/issues/2966 and https://github.com/ververica/flink-cdc-connectors/issues/2905.
PTAL @leonardBang.

[doc] fix invalid page in website and update yaml in tutorial.

---

docs/content/connectors/db2-cdc.md
docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/oceanbase-cdc(ZH).md
docs/content/connectors/oceanbase-cdc.md
docs/content/connectors/oracle-cdc.md
docs/content/connectors/postgres-cdc.md
docs/content/connectors/sqlserver-cdc.md
docs/content/connectors/tidb-cdc.md
docs/content/connectors/vitess-cdc.md
docs/content/overview/cdc-connectors.md
docs/content/quickstart/build-real-time-data-lake-tutorial.md
docs/content/quickstart/db2-tutorial.md
docs/content/quickstart/mongodb-tutorial.md
docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/quickstart/oceanbase-tutorial.md
docs/content/quickstart/oracle-tutorial.md
docs/content/quickstart/polardbx-tutorial.md
docs/content/quickstart/sqlserver-tutorial.md
docs/content/quickstart/tidb-tutorial.md
docs/content/快速上手/build-real-time-data-lake-tutorial-zh.md
docs/content/快速上手/mongodb-tutorial-zh.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md
docs/content/快速上手/oceanbase-tutorial-zh.md
docs/content/快速上手/oracle-tutorial-zh.md
docs/content/快速上手/polardbx-tutorial-zh.md
docs/content/快速上手/sqlserver-tutorial-zh.md
docs/content/快速上手/tidb-tutorial-zh.md

- Fixes #2989 
update docs version from 2.5-SNAPSHOT to 3.0-SNAPSHOT

[docs] update doc version description

---

docs/content/connectors/db2-cdc.md
docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/oceanbase-cdc(ZH).md
docs/content/connectors/oceanbase-cdc.md
docs/content/connectors/oracle-cdc.md
docs/content/connectors/postgres-cdc.md
docs/content/connectors/sqlserver-cdc.md
docs/content/connectors/tidb-cdc.md
docs/content/connectors/vitess-cdc.md
docs/content/overview/cdc-connectors.md
docs/content/quickstart/build-real-time-data-lake-tutorial.md
docs/content/quickstart/db2-tutorial.md
docs/content/quickstart/mongodb-tutorial.md

- Fixes #2989 
update doc version description
from  2.5-SNAPSHOT to  3.0-SNAPSHOT

[doc] update doc version description

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/DataSourceDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/IncrementalSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReaderWithCommit.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/PostgresDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/PostgresSourceBuilder.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/source/MockPostgresDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/MockPostgreSQLTableFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/MockPostgreSQLTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory

[postgres] Fix data lost problem when new lsn committed to slot between snapshotState and notifyCheckpointComplete

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/OracleValidator.java

[cdc][oracle] Add oracle 21 version to OracleValidator

---

docs/content/overview/cdc-pipeline.md

[docs] correct word 'escription' to 'description'

---

NOTICE
docs/site/NOTICE
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-db2-cdc/src/main/resources/META-INF/NOTICE
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-mongodb-cdc/src/main/resources/META-INF/NOTICE
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-mysql-cdc/src/main/resources/META-INF/NOTICE
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-oceanbase-cdc/src/main/resources/META-INF/NOTICE
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-oracle-cdc/src/main/resources/META-INF/NOTICE
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-postgres-cdc/src/main/resources/META-INF/NOTICE
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-sqlserver-cdc/src/main/resources/META-INF/NOTICE

This PR updates NOTICE files in Flink CDC.

[FLINK-34183] Update NOTICE files

---

.asf.yaml

This pull request adds `.asf.yaml` file for configuring project descriptions, merge behaviors and Jira auto-links.

[FLINK-34664][cdc] Add .asf.yaml file

---

docs/content.zh/docs/developer-guide/contribute-to-flink-cdc.md
docs/content.zh/docs/developer-guide/licenses.md
docs/content/docs/developer-guide/contribute-to-flink-cdc.md
docs/content/docs/developer-guide/licenses.md

This PR adds licenses & contributing docs to Flink CDC.

[FLINK-34684 & 34683][docs] Add licenses & contributing docs in Flink CDC

---

docs/content/docs/connectors/doris.md
docs/content/docs/connectors/legacy-flink-cdc-sources/overview.md
docs/content/docs/connectors/mysql.md
docs/content/docs/connectors/overview.md
docs/content/docs/connectors/starrocks.md

This pull request adds overview page for CDC connectors and optimizes connector docs.

[FLINK-34680][cdc] Add overview page for CDC connectors and optimize connector docs

---

docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md
docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

Minor: improve the quick start examples of Flink docs

[minor][cdc][docs] Improve the quickstart examples for Flink CDC docs

---

docs/content/docs/deployment/kubernetes.md

[FLINK-34685][cdc][doc] add kubernetes.md under deployment directory.

---

docs/content/docs/deployment/standalone.md

[FLINK-34681][cdc][doc] add standalone.md under deployment directory.

---

docs/content/docs/deployment/yarn.md

Add doc about deploying CDC pipeline to yarn cluster.

[FLINK-34686][cdc] add docs about yarn deployment

---

docs/content.zh/docs/connectors/_index.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/_index.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/datastream-api-package-guidance.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/overview.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/_index.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/build-real-time-data-lake-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/db2-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/mongodb-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/mysql-postgres-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/oceanbase-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/oracle-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/polardbx-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/sqlserver-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/tidb-tutorial.md
docs/content.zh/docs/connectors/overview.md
docs/content.zh/docs/core-concept/_index.md
docs/content.zh/docs/deployment/_index.md
docs/content.zh/docs/developer-guide/_index.md
docs/content.zh/docs/developer-guide/contribute-to-flink-cdc.md
docs/content.zh/docs/developer-guide/licenses.md
docs/content.zh/docs/developer-guide/understand-flink-cdc-api.md
docs/content.zh/docs/faq/_index.md
docs/content.zh/docs/faq/faq.md
docs/content.zh/docs/get-started/_index.md
docs/content.zh/docs/get-started/introduction.md
docs/content.zh/docs/get-started/quickstart/_index.md
docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md
docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md

[FLINK-34734][cdc][doc] update the title of content.zh to Chinese.

---

docs/content.zh/docs/faq/faq.md
docs/content/docs/faq/faq.md

Translate https://github.com/apache/flink-cdc/blob/master/docs/content/docs/faq/faq.md page into Chinese.

[FLINK-34742][docs] Translate "FAQ" Page for Flink CDC Chinese Documentation

---

docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/oceanbase-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/overview.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/build-real-time-data-lake-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/build-streaming-etl-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/db2-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/mongodb-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/mysql-postgres-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/oceanbase-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/oracle-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/polardbx-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/sqlserver-tutorial.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tutorials/tidb-tutorial.md
docs/content/docs/connectors/legacy-flink-cdc-sources/overview.md
docs/content/docs/connectors/legacy-flink-cdc-sources/tutorials/build-real-time-data-lake-tutorial.md
docs/content/docs/connectors/legacy-flink-cdc-sources/tutorials/build-streaming-etl-tutorial.md
docs/content/docs/connectors/legacy-flink-cdc-sources/tutorials/db2-tutorial.md

Docs are copied from https://github.com/apache/flink-cdc/tree/release-2.4/docs/content/connectors and https://github.com/apache/flink-cdc/tree/release-2.4/docs/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B,
and update some links.

[FLINK-34740][cdc][doc] copy back Chinese connector docs and update some links.

---

docs/content.zh/docs/get-started/introduction.md
docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md
docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

Translate https://github.com/apache/flink-cdc/tree/master/docs/content/docs/get-started pages into Chinese.

[FLINK-34741][docs] Translate "get-started" Page for Flink CDC Chinese Documentation.

---

docs/content.zh/docs/connectors/doris.md
docs/content.zh/docs/connectors/mysql.md
docs/content.zh/docs/connectors/overview.md
docs/content.zh/docs/connectors/starrocks.md

Translate pipeline connector pages https://github.com/apache/flink-cdc/tree/master/docs/content/docs/connectors into Chinese

[FLINK-34739][docs] Translate "Connectors" Page for Flink CDC Chinese Documentation

---

docs/content.zh/docs/connectors/legacy-flink-cdc-sources/db2-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/oceanbase-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/oracle-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/postgres-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/sqlserver-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tidb-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/vitess-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/db2-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/mongodb-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/oceanbase-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/oracle-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/postgres-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/sqlserver-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/tidb-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/vitess-cdc.md

Remove invalid links unify add download links to fat jar.

[FLINK-34770][cdc][doc] fix download links.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-tidb-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-vitess-cdc/pom.xml

[build] fix inconsistent Kafka shading among cdc connectors

---

docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

https://nightlies.apache.org/flink/flink-cdc-docs-release-3.0/docs/get-started/quickstart/mysql-to-doris/#synchronize-schema-and-data-changes

[minor][docs] Optimize markdown styles in quickstart doc

---

docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

https://nightlies.apache.org/flink/flink-cdc-docs-release-3.0/docs/get-started/quickstart/mysql-to-doris/#synchronize-schema-and-data-changes

[BP-3.0][minor][cdc][docs] Optimize markdown styles in quickstart doc

---

docs/content.zh/docs/connectors/mysql.md
docs/content/docs/connectors/mysql.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceFactoryTest.java

desc :[FLINK-34903](https://issues.apache.org/jira/browse/FLINK-34903)

[FLINK-34903][MySQL][Feature] Add mysql-pipeline-connector with tables.exclude option to exclude unnecessary tables

---

docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

[BP-3.0][minor][cdc][docs] Fix outdated StarRocks quickstart guide

---

flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-full.yaml
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/pipeline/PipelineOptions.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/SchemaOperatorTranslator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperatorFactory.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistry.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/event/RefreshPendingListsRequest.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/event/RefreshPendingListsResponse.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/event/SchemaChangeProcessingResponse.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/event/SchemaChangeResultRequest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/testutils/operators/EventOperatorTestHarness.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/testutils/schema/CollectingMetadataApplier.java

This closed https://github.com/apache/flink-cdc/issues/2910#issuecomment-1987707544, https://github.com/apache/flink-cdc/issues/2956.

[FLINK-34648] add waitChangeResultRequest and WaitChangeResultResponse to avoid RPC timeout.

---

tools/releasing/create_release_branch.sh
tools/releasing/create_source_release.sh
tools/releasing/deploy_staging_jars.sh
tools/releasing/update_branch_version.sh

refer to [paimon](https://github.com/apache/incubator-paimon/tree/master/tools/releasing) and [flink-ml](https://github.com/apache/flink-ml/tree/master/tools/releasing).

[FLINK-34188][cdc][build] Add scripts in tools/releasing to help release.

---

.github/workflows/flink_cdc.yml

Changes:
- Avoid canceling ci in branch.

[hotfix][ci] Polish ci concurrency group

---

.github/workflows/build_docs.yml
docs/config.toml
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
pom.xml

This pull request bumps the version to 3.2-SNAPSHOT for master branch.

[release] Update version to 3.2-SNAPSHOT

---

docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md

There is an issue with the format of three shell scripts

[docs]Problem with Case Document Format in Quickstart

---

docs/content.zh/docs/connectors/doris.md
docs/content/docs/connectors/doris.md

This PR backports [FLINK-35258](https://issues.apache.org/jira/browse/FLINK-35258) to release 3.1 branch.

[BP-3.1][FLINK-35258][cdc][doc] Fix broken links to Doris in documentation

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformSchemaOperatorTest.java

[BP-3.1][FLINK-35256][runtime] Fix transform node does not respect type nullability

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/typeutils/DataTypeConverter.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformDataOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/JaninoCompilerTest.java

This closes [FLINK-35259](https://issues.apache.org/jira/browse/FLINK-35259).

[FLINK-35259][cdc] Fix FlinkCDC pipeline transform can't deal timestamp field

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/sink/DataSinkWriterOperator.java

DataSinkWriterOperator should override snapshotState and processWatermark method

[FLINK-35255]DataSinkWriterOperator should override snapshotState and processWatermark method

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/ddl/mysql_inventory.sql
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/ddl/transform_test.sql
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformSchemaOperator.java

This PR fixes multiple transform rules do not take effect since transform rules are overwritten in for-loop, and adds transform IT test cases.

[FLINK-35264] Fix multiple transform rules do not take effect

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/io/debezium/connector/db2/Db2Connection.java

[FLINK-35274](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-35274)

[FLINK-35274][cdc-connector][db2] Fix occasional failure issue with Flink CDC Db2 UT

---

docs/content.zh/docs/connectors/paimon.md
docs/content/docs/connectors/paimon.md

[BP-3.1][hotfix][docs] Correct example configuration for Paimon warehouse path

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

Improve jdbc connection pool initialization failure message.

[FLINK-35295][mysql] Improve jdbc connection pool initialization failure message

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

[BP-3.1][FLINK-35295][mysql] Improve jdbc connection pool initialization failure message

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/relational/connection/JdbcConnectionPoolFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

[BP-3.1][FLINK-35301][cdc] Avoid deadlock when loading driver classes

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/task/MySqlBinlogSplitReadTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java

[BP-3.1][FLINK-35294][mysql] Use source config to check if the filter should be applied in timestamp starting mode

---

pom.xml

[build] fix jackson conflicts among cdc connectors

---

docs/content.zh/docs/connectors/flink-sources/db2-cdc.md
docs/content.zh/docs/connectors/flink-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/flink-sources/oceanbase-cdc.md
docs/content.zh/docs/connectors/flink-sources/oracle-cdc.md
docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md
docs/content.zh/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content.zh/docs/connectors/flink-sources/tidb-cdc.md
docs/content.zh/docs/connectors/flink-sources/tutorials/build-real-time-data-lake-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/build-streaming-etl-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/mongodb-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/oceanbase-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/oracle-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/polardbx-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/sqlserver-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/tidb-tutorial.md
docs/content.zh/docs/connectors/flink-sources/vitess-cdc.md
docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md
docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/connectors/flink-sources/db2-cdc.md
docs/content/docs/connectors/flink-sources/mongodb-cdc.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/flink-sources/oceanbase-cdc.md
docs/content/docs/connectors/flink-sources/oracle-cdc.md
docs/content/docs/connectors/flink-sources/postgres-cdc.md
docs/content/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content/docs/connectors/flink-sources/tidb-cdc.md
docs/content/docs/connectors/flink-sources/vitess-cdc.md
docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

[BP-3.1][FLINK-35527][docs] Polish quickstart guide & migrate maven links from ververica to apache

---

docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md

Optimize markdown formats in doris quickstart doc

[BP-3.0][minor][cdc][docs] Optimize markdown formats in doris quickstart doc

---

docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md

Optimize markdown formats in doris quickstart doc

[BP-3.1][minor][cdc][docs] Optimize markdown formats in doris quickstart doc

---

flink-cdc-common/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/pom.xml
flink-cdc-e2e-tests/flink-cdc-e2e-utils/pom.xml
pom.xml

Cherry picked from https://github.com/apache/flink-cdc/commit/38a1782ecc320c587200bd94e1836795cd9e0896, and fixed MySQL to Doris E2e test case.

[hotfix] Remove test-jar from parent pom and only add to necessary modules

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslator.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/utils/DorisContainer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/utils/DorisSinkTestBase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/resources/log4j2-test.properties
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/com/starrocks/shade/org/apache/commons/compress/utils/Lists.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/utils/StarRocksContainer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/utils/StarRocksSinkTestBase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MySqlToDorisE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestEnvironment.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
pom.xml

[BP-3.1][FLINK-35415][base] Fix compatibility with Flink 1.19

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/org/apache/flink/cdc/connectors/doris/sink/DorisEventSerializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisRowConverterTest.java

pick from master. https://github.com/apache/flink-cdc/pull/3207

[pipeline-connector][doris] Fix Mysql pipeline to doris will lost precision for timestamp

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/converters/MysqlDebeziumTimeConverter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/converters/MysqlDebeziumTimeConverterITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/ddl/date_convert_test.sql

hotfix Fix [FLINK-35173](https://issues.apache.org/jira/browse/FLINK-35173) MysqlDebeziumTimeConverter miss timezone convert to timestamp.

[BP-3.1][FLINK-35592] Fix MysqlDebeziumTimeConverter miss timezone convert to timestamp

---

docs/assets/_custom.scss
docs/content.zh/_index.md
docs/content/_index.md

[docs][minor] Optimize styles of the Flink CDC index page

---

docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md
docs/content/docs/connectors/flink-sources/postgres-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceBuilder.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceExampleTest.java

[hotfix][postgres] Remove unsupported erroneous example code from documentation

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/StreamSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresDialect.java

[cdc][postgres]PostgresDialect removes useless code

---

docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/pipeline-connectors/mysql.md

[FLINK-35758][doc] add scan.startup.timestamp-millis to mysql connector options.

---

docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/pipeline-connectors/mysql.md

Add Doc for https://github.com/apache/flink-cdc/pull/2901.

[FLINK-35871][doc] add "snapshot" to mysql connector startup options.

---

README.md
docs/content.zh/docs/core-concept/data-pipeline.md
docs/content/docs/core-concept/data-pipeline.md

Add transform piece for pipeline example

[docs][minor] Add transform piece for pipeline example

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomAlterTableParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java

Doris & StarRocks are not support the `UpdateTypeEvent` right now, So should i need change the implement for Doris and Starrocks to ignore the UpdateTypeEvent to keep job healthy?

[FLINK-35432]Support catch modify event for the mysql.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/source/MongoDBParallelSourceITCase.java

This fixes a rarely happened failure case, observed in https://github.com/apache/flink-cdc/actions/runs/10209766277/job/28253831363?pr=3388 by @loserwang1024.
`testSnapshotOnlyModeWithDMLPreHighWaterMark` case will fail, if there's no operation or heartbeat events between event `#a` (the ChangeStream opLog caused by the last event in the hook) and event `#b` (the calculated high watermark that limits the bounded back-filling stream fetch task), `#a` and `#b` will point to the same offset in change stream, thus the last event of hook will be missed since back-filling task only reads data between `[loW, hiW)` (high watermark not included).
This is a workaround by insert a dummy event in another collection to forcefully push opLog forward, so `#a` will not be the same as the high watermark …

[hotfix][cdc-connector][mongodb] Fix unstable test cases for snapshot back-filling

---

docs/config.toml

This pull request updates documentation configurations on release-3.2 branch

[hotfix][docs] Update documentation config for release-3.2

---

flink-cdc-cli/pom.xml
flink-cdc-common/pom.xml
flink-cdc-composer/pom.xml
flink-cdc-connect/pom.xml
flink-cdc-dist/pom.xml
flink-cdc-dist/src/main/assembly/assembly.xml
flink-cdc-e2e-tests/pom.xml
flink-cdc-migration-tests/pom.xml
flink-cdc-pipeline-udf-examples/pom.xml
flink-cdc-runtime/pom.xml
pom.xml
tools/releasing/create_source_release.sh

Unchanged backport of #3540 on release-3.2

[BP-3.2][FLINK-36054][cdc][build] Fix Flink CDC parent pom and release scripts

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/pom.xml

change flink.connector.elasticsearch.version to a release version

[FLINK-36055] change flink.connector.elasticsearch.version to a release version

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomAlterTableParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MysqlPipelineNewlyAddedTableITCase.java

Support parsing table creation ddl and creating CreateTableEvent in Binlog reading phase.

[FLINK-36148][pipeline-connector][mysql] Add custom parser for CreateTableEvent

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolveE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperator.java

[BP-3.2][FLINK-36184][transform] Fix transform operator swallows schema changes from tables not present in transform rules

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/typeutils/BinaryRecordDataGenerator.java

[FLINK-35291] Improve the ROW data deserialization performance of DebeziumEventDeserializationScheme

---

docs/content.zh/docs/connectors/flink-sources/vitess-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/elasticsearch.md
docs/content/docs/connectors/flink-sources/vitess-cdc.md
docs/content/docs/connectors/pipeline-connectors/elasticsearch.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/pom.xml

@proletarians @leonardBang PTAL, thanks.
Or we can continue previous pr(https://github.com/apache/flink-cdc/pull/3539).

[FLINK-36052][docs][elasticsearch] Add flink cdc elasticsearch pipeline sink to docs

---

docs/content.zh/docs/connectors/flink-sources/vitess-cdc.md
docs/content.zh/docs/core-concept/transform.md
docs/content/docs/connectors/flink-sources/vitess-cdc.md
docs/content/docs/core-concept/transform.md

[BP-3.2][FLINK-36221] Add `CAST ... AS ...` documentations

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/SchemaUtils.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/utils/SchemaUtilsTest.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/SchemaOperatorTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksMetadataApplierITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolveE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolvingTransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperatorFactory.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivation.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivationTest.java

[BP-3.2][FLINK-36474] Support merging timestamp columns when routing

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/NewlyAddedTableITCase.java

[BP-3.2][FLINK-36326] Fix auto scan newly-added table failure

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/SchemaUtils.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/utils/SchemaUtilsTest.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperator.java

[BP-3.2][FLINK-36565][transform] Route allows merging Decimals with various precisions

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/typeutils/BinaryRecordDataGenerator.java

backport of https://github.com/apache/flink-cdc/pull/3289 to release 3.2

[FLINK-35291][runtime] Improve the ROW data deserialization performance of DebeziumEventDeserializationScheme (#3289)

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/StoreSinkWriteImpl.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

backport of FLINK-36750 to release-3.2

[FLINK-36750][paimon] Restore SinkWrite from state to keep the information of previous SinkWrite when schema evolution happen.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/SnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java

[FLINK-36772](https://issues.apache.org/jira/browse/FLINK-36772)

[FLINK-36772][mysql][cdc-base] Fix error placeholder for errorMessageTemplate of Preconditions

---

docs/content.zh/docs/connectors/flink-sources/overview.md
docs/content.zh/docs/connectors/flink-sources/vitess-cdc.md
docs/content/docs/connectors/flink-sources/overview.md
docs/content/docs/connectors/flink-sources/vitess-cdc.md

Add missed supported flink versions

[hotfix][docs] Add missed supported flink versions

---

docs/content.zh/docs/core-concept/transform.md

[Minor][Doc] fix spelling error.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java

This fixes a unstable test case in `MySqlPipelineITCase`, where `CreateTableEvent`s might be emitted duplicately if snapshot splits are assigned to different subTasks. Changed result checking logic to verify properly.

[hotfix] Fix unstable `testInitialStartupModeWithOpTs` case

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

Fix CI failure caused by https://github.com/apache/flink-cdc/pull/3644 which didn't contain the fix of https://github.com/apache/flink-cdc/pull/3760.

[hotfix] fix ci failure.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/main/java/org/apache/flink/cdc/connectors/elasticsearch/sink/ElasticsearchDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/test/java/org/apache/flink/cdc/connectors/elasticsearch/sink/Elasticsearch6DataSinkITCaseTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/test/java/org/apache/flink/cdc/connectors/elasticsearch/sink/Elasticsearch7DataSinkITCaseTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/test/java/org/apache/flink/cdc/connectors/elasticsearch/sink/ElasticsearchDataSinkITCaseTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/test/java/org/apache/flink/cdc/connectors/elasticsearch/sink/utils/ElasticsearchContainer.java

[FLINK-36700][pipeline-connector][elasticsearch] Elasticsearch pipeline sink support authentication

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/schema/Schema.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformChangeInfo.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformProcessor.java

See [FLINK-37011](https://issues.apache.org/jira/browse/FLINK-37011)

[FLINK-37011] Improve get source field value by column name in PreTransformProcessor.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/resources/log4j2-test.properties
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/test/resources/db2_server/customers.sql
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/docker/mysql/my.cnf
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/docker/mysql/setup.sql
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/log4j2-test.properties
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/resources/docker/db2/customers.sql

License of some files need to be updated.

[hotfix][license] Update legacy license

---

.github/workflows/flink_cdc_base.yml
.github/workflows/utils.sh

Refer to [this comment](https://github.com/apache/flink-cdc/pull/3648#pullrequestreview-2374769012)
Copy from Paimon repo.
How to verify:

[FLINK-36564][ci] Running CI in random timezone to expose more time related bugs.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/polardbx/PolardbxCharsetITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/polardbx/PolardbxSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/polardbx/PolardbxSourceTestBase.java

[FLINK-37362][tests][polardbx] Check Polardbx CDC component is ready before test

[FLINK-37362][tests][polardbx] Check Polardbx CDC component is ready before test

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonEvent.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonRecordEventSerializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriterHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

Write full changelog to PaimonSink so that PaimonSource of Flink Streaming won't need another operator to product the changelog.

[FLINK-37352] Write full changelog to PaimonSink.

---

docs/content.zh/docs/connectors/pipeline-connectors/starrocks.md
docs/content/docs/connectors/pipeline-connectors/starrocks.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSinkOptions.java

[FLINK-37204](https://issues.apache.org/jira/browse/FLINK-37204)

[FLINK-37204] Add missing StarRocks connector options for 1.2.10.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/enumerator/PostgresSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/reader/PostgresSourceReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java

[FLINK-37449][postgres] Fix postgres cdc don't commit lsn when taskManager failover

---

docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content.zh/docs/core-concept/transform.md
docs/content/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/core-concept/transform.md

Add op_ts metadata docs in MySQL pipeline connector

[FLINK-36784][docs] Add op_ts metadata docs in MySQL pipeline connector

---

docs/content.zh/docs/connectors/pipeline-connectors/kafka.md
docs/content/docs/connectors/pipeline-connectors/kafka.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/ChangeLogJsonFormatFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlAncientDateAndTimeITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlAncientDateAndTimeITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlAncientDateAndTimeITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlToKafkaE2eITCase.java

Code style verifier has been updated to JUnit 5

[hotfix] Rename sink.debezium-json.include-schema.enabled and fix code style

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/reader/IncrementalSourceSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/reader/external/IncrementalSourceScanFetcher.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/source/MongoDBFullChangelogITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/source/NewlyAddedTableITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/split/MySqlRecords.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/NewlyAddedTableITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/source/NewlyAddedTableITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresScanFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/NewlyAddedTableITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresScanFetchTaskTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/reader/PostgresSourceReaderTest.java

Fix https://issues.apache.org/jira/browse/FLINK-37509

[FLINK-37509] Increment scan source no need to buffer data when enable skipping backfill.

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/schema/Schema.java

[BP-3.4][FLINK-37741][cdc-runtime] Fix transform operator performance degradation

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaCoordinator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaOperator.java

[BP-3.4][FLINK-37462] Fix consecutive schema change requests might be overwritten

---

docs/content/docs/connectors/pipeline-connectors/mysql.md

Close https://issues.apache.org/jira/browse/FLINK-37784

[FLINK-37784][docs] Remove Duplicate Description for `scan.incremental.snapshot.unbounded-chunk-first.enabled` Parameter in Documentation

---

.github/workflows/build_docs.yml

Refer to change of 3.3 via https://github.com/apache/flink-cdc/pull/3882/files.

[hotfix][cdc][docs] Build 3.4 docs and mark it as stable.

---

docs/content/docs/connectors/flink-sources/postgres-cdc.md

Fix https://issues.apache.org/jira/browse/FLINK-36844

[FLINK-36844][docs]Postgres CDC document add mapping from postgres timestamp_tz to flink timestamp ltz.

---

docs/content/docs/connectors/pipeline-connectors/iceberg.md

Minor updates as I read through the documentation. Excited to see the Iceberg sink connector land in Flink CDC! 🎉

docs: minor updates to Iceberg sink reference

---

docs/content/docs/connectors/flink-sources/postgres-cdc.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java

JIRA: https://issues.apache.org/jira/browse/FLINK-37824

[FLINK-37577][pipeline-connector/paimon] Fix missing column comment

---

tools/releasing/create_source_release.sh

https://superuser.com/questions/259703/get-mac-tar-to-stop-putting-filenames-in-tar-archives
https://superuser.com/questions/61185/why-do-i-get-files-like-foo-in-my-tarball-on-os-x

[FLINK-37839][tools]Fix source release package contains ._* files

---

flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/CliExecutor.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlOnLineSchemaMigrationITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlParallelizedPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MysqlPipelineNewlyAddedTableITCase.java

Remove useless imports in files.

[hotfix] Remove useless imports.

---

.github/workflows/flink_cdc_base.yml
.github/workflows/flink_cdc_ci.yml
.github/workflows/flink_cdc_ci_nightly.yml

This PR added the omitted Iceberg connector into the CI test matrix. Also split the pipeline connector UT into individual stages as the number of connectors has increased a lot.

[hotfix][ci] Add missing Iceberg unit tests & split pipeline connector UT into stages

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomAlterTableParserListener.java

Fix case-insensitive error when adding column After an existed column.

[FLINK-38244][hotfix] Fix case-insensitive error when adding column After an existed column.

---

docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md
docs/content/docs/connectors/flink-sources/postgres-cdc.md

[FLINK-37738][postgres-cdc] Fix the corresponding Chinese and English of the append only document

[FLINK-37738][postgres-cdc] Fix the corresponding Chinese and English of the append only document

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonRecordEventSerializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriterHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/TableSchemaInfo.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

Avoid exception when writing update/delete data change events to Paimon append only table.

[FLINK-38359][pipeline-connector][paimon] Avoid exception when writing update event to Append only table.

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java

This closes FLINK-38393.
Consider this transform block:
```yaml
transform:
- { source-table: db.tbl1, filter: 'id > 0', projection: 'id, col1' }
- { source-table: db.tbl1, filter: 'id <= 0', projection: 'id, col2, col3' }
```
This should be correctly rejected, since there might be two incompatible schemas deduced, depending on if the filter condition is satisfied or not.
However, consider a slightly different example:
```yaml
transform:
- { source-table: db.tbl1, projection: 'id, col1' }
- { source-table: db.tbl2, projection: 'id, col2' }
- ...
- { source-table: db.\.*, projection: 'id, fallback' }
```
One may write a wildcard matching rule at the end, as a fallback rule. However, this will be rejected in CDC 3.4.0, because Table "db.tbl1" matches two rules with incompatible schema, …

[FLINK-38393][runtime/transform] Loosen schema consistency check for unreachable rules
