apache/flink-cdc

flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/MySQLSourceTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySQLConnectorITCase.java
pom.xml

It has been a long time since the release of debezium-1.5.2-final. In this release, a new capturing implementation for the Debezium MySQL connector has been created, which is almost in parity with previous implementation, with the exception of the experimental parallel snapshotting feature. If users enounter any problems, they can the **_legacy_**  implementation of the MySQL connector by setting the `internal.implementation=legacy` connector configuration option.
The other breaking changes about MySQL connector is when MySQL connector emits snapshot messages it marks the record as the `c` operation but it marks as the `r` operation. Our implementation doesn't relies on this and the change only breaks the test `MySQLSourceTest#testConsumingAllEvents`. 
Other breaking changes are about …

[debezium] Bump debezium version to 1.5.2.Final

---

flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/FlinkDatabaseHistory.java
flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/FlinkDatabaseSchemaHistory.java
flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/SchemaRecord.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/MySQLSource.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/MySQLSourceTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySQLConnectorITCase.java
flink-connector-mysql-cdc/src/test/resources/ddl/inventory.sql
flink-connector-postgres-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/postgres/PostgreSQLSourceTest.java
flink-connector-postgres-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-connector-postgres-cdc/src/test/resources/ddl/inventory.sql

*This PR aims to solve the out of memory poblem caused by the frequent schema changes. In this PR, we propose to use `FlinkDatabaseSchemaHistory`, which only stores the current snapshot of the table schema. If the pipeline fails and recovers from the state, it doesn't need to replay all the ddl history any more but only applies the maintained tables.*
*When starting from a state, the source funciton will automatically determine which history should use according to the state structure.  Users don't need to pay attention to the internal implementation.*
**Break Changes**
Because the new database history has a different state structure comparing to before. Therefore, it's not avaliable to start the pipeline with a state with different structure.

[common] Fix schema history run out of memory

---

flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySQLSourceOptions.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/assigner/MySQLSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/source/utils/StatementUtils.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySQLTableSource.java
flink-connector-mysql-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySQLTableSourceFactory.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/source/MySQLParallelSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/source/assigner/MySQLSnapshotSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/alibaba/ververica/cdc/connectors/mysql/table/MySQLTableSourceFactoryTest.java
flink-connector-mysql-cdc/src/test/resources/ddl/custom.sql

In the case that the split key is integral type(INT and BIGINT, DECIMAL), we can optimize the snapshot splits analyzing by integral range rather than querying the DB for every splits.
Introduce option `scan.optimize.integral-key` to enable the feature or not, by default the option value is `true` which means the enable this optimization.

[mysql] Support numeric type optimization for split boundary calculation

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/Validator.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/MySqlValidator.java

提交解决问题：
com.ververica.cdc.debezium.Validator$$Lambda$25/1712669532@12f41634 is not serializable.
https://github.com/ververica/flink-cdc-connectors/issues/311

release-2.0:com.ververica.cdc.debezium.Validator add Serializable

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java

[common] Remove useless parameter 'converter.schemas.enable'

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSource.java

Fixed the problem of #326 .
If `database.history.instance.name` property not set, the key of `EmbeddedFlinkDatabaseHistory.TABLE_SCHEMAS` will be "null_" + SourceReaderContext.getIndexOfSubtask. 
The exception may happen in the scenario of multi-table join because `EmbeddedFlinkDatabaseHistory.TABLE_SCHEMAS`  will be incorrectly overwritten or removed when executed concurrently.
Add logger at  MySqlParallelSource.getReaderConfig
```
ReaderConfig index of task: 0
ReaderConfig index of task: 0
ReaderConfig table: {database.user=mysqluser, database.server.name=mysql_binlog_source, scan.startup.mode=initial, database.port=55169, table.whitelist=history_missing_7rl2ke.sfy_live_act_employ, scan.snapshot.fetch.size=1024, database.serverTimezone=UTC, database.hostname=localhost, …
```

[ISSUE-326] Fix database history missing.

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java

When all snapshot spit stage finished , it need to create a MySqlBinlogSplit to start up a increment binlog stage .
First need to find a startingOffset position from all assignedSnapshotSplit of snapshot stage.
But it always get BinlogOffset.INITIAL_OFFSET value .

[issue-329] Fix find min binlog offset wrong value in increment binlog stage

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlParallelSourceTestBase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MysqlTimezoneITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/testutils/RecordsFormatter.java

Introduce assertEqualsInOrder/assertEqualsInAnyOrder for tests,
This also fixes #436 which we should not use equals to compare the un-ordered result because the snapshot data comes from  different task and may arrives in different order.

[tests] Introduce assertEqualsInOrder/assertEqualsInAnyOrder for tests

---

README.md
docs/content/about.md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md

issue #414 
- Incorrect use of no lock mode.
e.g. `debeziumProperties.put("debezium.snapshot.locking.mode", "none")`
- The captured table could not be set up correctly..
e.g. `tableList("tableName")`
- Unable to get json output.
e.g. `deserializer(new StringDebeziumDeserializationSchema())`
```java
Properties debeziumProperties = new Properties();
debeziumProperties.put("snapshot.locking.mode", "none");// do not use lock
SourceFunction<String> sourceFunction = MySQLSource.<String>builder()
.hostname("yourHostname")
.port(yourPort)
.databaseList("yourDatabaseName") // set captured database
.tableList("yourDatabaseName.yourTableName") // set captured table
.username("yourUsername")
.password("yourPassword")
.deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to …
```

[docs] Correct Usage for DataStream API

---

docs/content/connectors/mongodb-cdc.md
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBConnectorSourceTask.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBEnvelope.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorDeserializationSchema.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBReadableMetadata.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorITCase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java

We introduced following MongoDB metadata columns in this PR:
#476
Key | DataType | Description
-- | -- | --
database_name | STRING NOT NULL | Name of the database that contain the row.
collection_name | STRING NOT NULL | Name of the collection that contain the row.
op_ts | TIMESTAMP_LTZ(3) NOT NULL | It indicates the time that the change was made in the database. If the record is read from snapshot of the table instead of the change stream, the value is always 0.

[mongodb] Support metadata columns for mongodb-cdc connector (#476)

---

pom.xml

There are some critical bug fix in the new debezium version, e.g. [DBZ-3068](https://issues.redhat.com/browse/DBZ-3068).

[common] Bump debeizum version to 1.5.4.Final

---

docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlReadableMetadata.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLReadableMetadata.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableSource.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java

Expose following Postgres metadata columns in this PR:
issue: https://github.com/ververica/flink-cdc-connectors/issues/249
<html>
<body>
Key | DataType | Description
-- | -- | --
database_name | STRING NOT NULL | Name of the database that contain the row.
collection_name | STRING NOT NULL | Name of the collection that contain the row.
op_ts | TIMESTAMP_LTZ(3) NOT NULL | It indicates the time that the change was made in the database. If the record is read from snapshot of the table instead of the change stream, the value is always 0.
</body>
</html>

[postgres] Support metadata columns for postgres-cdc connector

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/MySqlBinlogSplitReadTask.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/offset/BinlogOffset.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java

the `isAtOrBefore & isBefore` was actually meaning
`isAtOrAfter & isAfter`, so let's do this right ;)
Signed-off-by: Zhao Junwang <zhjwpku@gmail.com>

[mysql] polish binlog offset compare semantic

---

docs/content/connectors/oracle-cdc.md

Oracle's DATE type is actually a datetime type, which should be mapped to flink's TIMESTAMP type.

[docs] Fix oracle DATE type mapping

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/MongoDBSource.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/MongoDBTestBase.java
flink-connector-mongodb-cdc/src/test/resources/ddl/setup.js

Fix the username or password contains `: / ? # [ ] @` authentication failed problem.
Cause URI encoded `authority` twice.

[hotfix][mongodb] Correct the connection uri building of MongoDB

---

flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/OracleSourceTest.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleConnectorITCase.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/utils/OracleCdcContainer.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/utils/OracleTestUtils.java
pom.xml

Upgrade the testcontainers dependency from 1.15.1 to 1.16.2. This newer version should be quicker.

[tests] Upgrade testcontainers dependency to 1.16.2

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBConnectorSourceTask.java

Fix problem of cannot look up fields on non-struct type

[hotfix][mongodb] Fix problem of cannot look up fields on non-struct type

---

docs/content/connectors/oracle-cdc.md

In Oracle database if we created a table without quoting the field names, it would automatically convert the field names to uppercase. As a result, we can get the right data only if we create table in Flink with field names excatly matching cases with those defined in Oracle. Field name defined without quotes will be convert to uppercase by oracle and fieled names in SQL executed in Oracle will also be converted to uppercase. However, Flink SQL will not do it, which means usually we have to create table with uppercased field names, otherwise we would get null values.
To minify the misleading effect of the document, I suggest we change the field names in oracle-cdc.md to uppercase. By the way we can keep it consistent with those SQLs in oracle-tutorial-zh.md.

[docs] Changed field names to uppercase in Flink create table SQL.

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java

When nomarlize the snapshotRecords and binlogRecords, we should
remove from snapshotRecords by binlogRecords.keys().
Short version reason: it's the rule from DBLog paper
Long version reason. TLDR;
Let't see the followling illustration:
```
snapshot readview(sr)
|
v
------lw---------hw-----    <- binlog stream
```
For RR isolation level, the readview is a point corresponding to
the binlog stream, let's name it sr.
1. For an update binlog(ub):
If lw <= ub <= sr, the normalizedBinlogRecord first add the
new value(i.e the updateAfter), and then add the snapshotRecords,
so there will be two record for this key, both contain the new value,
there is no problem since the downstream use the upsert logic.
But if sr < ub <= hw, the snapshotRecords contains the old
value, and the …

[mysql]: fix the normalizedSplitRecords logic

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlSource.java

Expose an interface for user to use the MySqlSourceConfigFactory#createConfig.
Some discussion can be found here [0]
[0] https://github.com/ververica/flink-cdc-connectors/pull/638

[mysql] add an interface to get MySqlSourceConfigFactory

---

docs/content/connectors/mysql-cdc.md
docs/content/connectors/postgres-cdc.md

Add FAQ that  the tableList is using full path rather than table name in datastream API #356
- Add mysql-cdc tableList config description into mysql-cdc.md FAQ list.
- Add postgres-cdc tableList config description into postgres-cdc.md FAQ list.

[docs-356] Add FAQ that the tableList is using full path rather than table name in datastream API

---

flink-connector-mongodb-cdc/pom.xml
flink-connector-mysql-cdc/pom.xml
flink-connector-oracle-cdc/pom.xml
flink-connector-postgres-cdc/pom.xml
pom.xml

This enables code coverage works using [JaCoCo](https://www.eclemma.org/jacoco/trunk/doc/maven.html) for the connector modules.

[build] Remove override definition of maven-surefire-plugin in connectors pom

---

pom.xml

2.0 <= Apache log4j2 <= 2.14.1 have a RCE zero day.
https://www.lunasec.io/docs/blog/log4j-zero-day/

Update log4j to fix RCE zero day.

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

Set HikariCP's minimumIdle to 1 to reduce connections size.

[mysql] Set HikariCP's minimumIdle to 1 to reduce connection size

---

docs/content/connectors/mysql-cdc.md

This PR fixes issue #854.
add connection options in mysql connectors docs:
- connection.pool.size
- connect.max-retries

[docs][mysql] add connection options

---

flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorITCase.java

Add default timeout as 10 minutes for method `waitForSinkSize` to tracking tests hang in azure CI #619.

[mongodb][tests] Tracking tests hang in azure CI.

---

flink-connector-mysql-cdc/src/main/java/com/github/shyiko/mysql/binlog/io/BufferedSocketInputStream.java
flink-connector-mysql-cdc/src/test/java/com/github/shyiko/mysql/binlog/io/BufferedSocketInputStreamTest.java

[mysql] Fix ArrayIndexOutOfBoundsException in mysql binlog read phase

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleTableSourceFactoryTest.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableFactoryTest.java
flink-connector-test-util/pom.xml
flink-connector-test-util/src/main/java/com/ververica/cdc/connectors/utils/AssertUtils.java

During the test, I found that the typeInfo created by the OracleTableSource was incorrect, because the producedDataType processed by #applyReadableMetadata was not used.
I added a test method to ensure that the data type of the source funtion matches the expected schema data type.

Fix the type information of source funtion and add tests

---

docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md

Fix https://github.com/ververica/flink-cdc-connectors/issues/918.

[docs] The link of download flink is 404 now.

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/context/MySqlErrorHandler.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/context/StatefulTaskContext.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java

when starting from a savepoint with the scanNewlyAddedTable
flag enabled, if there are some binlog records starting from
savepoint belong to the newly added table, Debeziumn can
not parse the record because of the table's schema isn't
known to the connector.
We can simply filter this kind of Exceptions.

[mysql][hotfix] fix schema isn't known to connector bug

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java

`suspendBinlogReaderIfNeed` broadcast `SuspendBinlogReaderEvent`
when splitAssigner is in suspend status, but there are chances
that this happens before `SourceReader` registered to
`SourceEnumerator`, in that case, we will need to wait
`CHECK_EVENT_INTERVAL` a.k.a 30s to resend the event message,
which can be annoying.
In this patch, simply send `SuspendBinlogReaderEvent` message
when `SourceReader` registers if the assigner's status is
suspended.

[mysql] accelerate suspend speed

---

docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md

In `mysql-postgres-tutorial.md`, environment variable `POSTGRES_PASSWORD` is defined twice with different values. This is not only redundant, but it could also lead to errors if/when the wrong value is used.
This PR removes the wrong value and only keeps the right one.

Remove redundant environment variable in tutorial

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/AssignerStatus.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializerTest.java

serialize `isSuspended` field, and modify the test case to enable Snapshot failover.

[mysql][hotfix] serialize isSuspended flag for MySqlBinlogSplit backport to 2.2

---

flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/table/RowDataTiKVChangeEventDeserializationSchema.java

RowKind.INSERT is decided via `if (row.getOldValue() == null)` in `RowDataTiKVChangeEventDeserializationSchema:84`. 
But when performing INSERT statements in TiDB, it produced a Row record with NOT NULL return value from  `row.getOldValue()` but `Internal.EMPTY_BYTE_ARRAY`(a String[0] array) return value from `row.getOldValue().toByteArray()`, which will produce wrong RowKind (expect `INSERT` but actual `UPDATE_AFTER`) of the emitted RowData.
Hence it should add a length judgement condition for INSERT.

[hotfix][tidb] fix RowKind.INSERT judgement condition

---

flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/table/RowDataTiKVChangeEventDeserializationSchema.java

RowKind.INSERT is decided via `if (row.getOldValue() == null)` in `RowDataTiKVChangeEventDeserializationSchema:84`. 
But when performing INSERT statements in TiDB, it produced a Row record with NOT NULL return value from  `row.getOldValue()` but `Internal.EMPTY_BYTE_ARRAY`(a String[0] array) return value from `row.getOldValue().toByteArray()`, which will produce wrong RowKind (expect `INSERT` but actual `UPDATE_AFTER`) of the emitted RowData.
Hence it should add a length judgement condition for INSERT.

[tidb] fix RowKind.INSERT judgement condition in DeserializatonSchema

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/context/StatefulTaskContext.java

Flink job could not restart from checkpoint when some binlog files in the new master were cleared during the master/slave switchover. We add the gtid logic, it works. #743

[mysql] update check gtid set

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/context/StatefulTaskContext.java

This is an unchanged back port of #761 on release-2.2

[mysql] Use the gtid set firstly when compare the binlog offset (#761)

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer.sql

This pull request fixes #1081 that an exception should be thrown in coordinator thread if the consuming table doesn't have primary key.

[mysql] Catch and hold exception in chunk splitter thread and rethrow in getNext()

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSource.java

This pull request adds a missing field `heartbeatInterval` into MySqlTableSource.equals() and hashCode().

[mysql] Add heartbeatInterval field to equals() and hashCode()

---

docs/content/connectors/mongodb-cdc.md

Fix [issue-1286](https://github.com/ververica/flink-cdc-connectors/issues/1286).
I change `table_nam`e to `collection_name`.

[mongodb][doc] Fix meta field collection_name of metadata sql example

---

flink-connector-tidb-cdc/src/main/java/org/tikv/common/operation/iterator/ScanIterator.java

Link https://github.com/ververica/flink-cdc-connectors/issues/1159.

[tidb-cdc] Monitor tidb table lose data, which table has one more regions.

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/connection/ConnectionPoolId.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/connection/JdbcConnectionFactory.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/ConnectionPoolId.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/JdbcConnectionFactory.java

Connection pool id should contains user name to prevent different user using the same connection.
Fix #1328

[mysql] Connection pool id should contains username (#1328)

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java

**Pure binlog phase performace opt**
Our online business found that the performance of the binlog phase of Flink jobs could not meet the demand. Through performance analysis, we found that the performance bottleneck in the phase was the comparison of binlog offset. For each binlog data, mysql-cdc needs to judge whether the offset of the binlog data is after the end of the full snapshot phase (max split high watermark). If so, it is in pure binlog phase, and can be directly output to the downstream. The comparison between binlog data offset and max split high watermark consumes CPU very much and has become a performance bottleneck (see the following figure).
Further analysis of the internal logic of mysql-cdc shows that for each mysql-cdc table, the state of incremental synchronization …

[mysql] Optimize pure binlog phase check logic to improve performance

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceScanFetcher.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceStreamFetcher.java

issues : [issues-1122](https://github.com/ververica/flink-cdc-connectors/issues/1122)

[fix][cdc-base] fix cdc bug

---

flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/MySqlChunkSplitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlChunkSplitterTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java

This PR fix the bug #1349 in splitting the chunks. The splitter should use dynamic chunk size instead of chunk size.

[mysql] Generates multiple chunks when approximate row count is bigger than chunk size

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceTestBase.java

fix debezium reader thread lake

---

flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/table/RowDataTiKVEventDeserializationSchemaBase.java

Fix issue https://github.com/ververica/flink-cdc-connectors/issues/1442 .

[tidb-cdc] TiDB CDC dealUnsignedColumnValue throw NullPointerException.

---

flink-connector-oracle-cdc/src/test/resources/docker/assets/activate-archivelog.sh

Minor change: the '#!/bin/bash' line in shell script must be set at first line

[shell] fix shell script 

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java

`StreamExecutionEnvironment#getConfiguration` now returns an unmodifiable configuration, which will cause test failing.

[hotfix][test] fix the error in MySqlSourceITCase when adding the savepoint path

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java

dont need captureNewlyAddedTables when isRemainingTablesCheckpointed is false and assign isnt finished on MySqlSnapshotSplitAssigner

 dont need captureNewlyAddedTables when isRemainingTablesCheckpointed is false and assign isnt finished on MySqlSnapshotSplitAssigner

---

docs/content/connectors/oceanbase-cdc.md
flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/OceanBaseSource.java
flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseTableSourceFactory.java
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseConnectorITCase.java
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseTableFactoryTest.java

Similar to [MySQL](https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html#time-zone-variables), OceanBase may not support named timezone like 'UTC' and 'PST'. So it's better to use UTC offset here.

[oceanbase] use utc offset as timezone by default

---

docs/content/connectors/oceanbase-cdc.md
docs/content/quickstart/oceanbase-tutorial.md
docs/content/快速上手/oceanbase-tutorial-zh.md
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/OceanBaseTestBase.java
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseConnectorITCase.java

As the `storage` mode of `obcdc` will store the log data on the disk, which may waste the disk space. It's better to use `memory` mode for testing.
Fix #1473

[oceanbase][test] Use memory mode of obcdc and double startup timeout

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorDeserializationSchema.java

failed to convert BsonArray to String type in Flink
```
2022-08-11 17:57:06.023 [Source: mongodb source datamanager.bcsdatamanager_cluster (1/1)#0] WARN  org.apache.flink.runtime.taskmanager.Task  - Source: mongodb source datamanager.bcsdatamanager_cluster (1/1)#0 (310561d264d8435431a809240a2e1802) switched from RUNNING to FAILED with failure cause: java.lang.IllegalArgumentException: Unable to convert to string from unexpected value 'BsonArray{values=[{"index": 30, "time": {"$date": "2022-04-29T06:30:00Z"}, "nodecount": 0, "availablenodecount": 0, "minnode": {"name": "MinNode", "metricname": "MinNode", "value": 0.0, "period": "2022-04-29 14:30:00 +0800 CST", "xxx_nounkeyedliteral": {}, "xxx_unrecognized": null, "xxx_sizecache": 0}, "maxnode": {"name": "MaxNode", "metricname": "MaxNode", …
```

[mongodb] Allow mongo ARRAY to be converted to string type in Flink

---

flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorITCase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBRegexFilterITCase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTimeZoneITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/LegacyMySqlSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlCompatibilityITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlTimezoneITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MysqlConnectorCharsetITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/polardbx/PolardbxCharsetITCase.java
flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseConnectorITCase.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleConnectorITCase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerConnectorITCase.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTimezoneITCase.java
flink-connector-tidb-cdc/src/test/java/com/ververica/cdc/connectors/tidb/table/TiDBConnectorITCase.java

`org.apache.flink.table.api.EnvironmentSettings.Builder#useBlinkPlanner` became deprecated in 1.14.x when there is only one planner left.
In 1.15.x it is removed => makes sense remove here to simplify future updates

[test] Remove usage of deprecated EnvironmentSettings.Builder#useBlinkPlanner

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlSource.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlRecordEmitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlRecords.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/SourceRecords.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlRecordEmitterTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java

The output records of a snapshot split should not cross checkpoints, this may lead to data duplication when failover happen, because partial snapshot records of one split may sent in last checkpoint, but this snapshot split may be re-read all snapshot records after failover, this behavior bring potential data duplication issue.

[mysql] Let the records of snapshot split don't cross checkpoints

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSnapshotSplit.java

should be "The high watermark is not null when the split read finished.", but not 'bull'.

There is a typo in the comments in MysqlSnapshotSplit.

---

flink-sql-connector-oceanbase-cdc/pom.xml

The `oblogclient` uses an incompatible codec function in `Hex` class, here shade it to prevent version conflicts.

[oceanbase] shade apache commons package

---

docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md

add document for the usage of regex to match multi-tables

[doc]add document for the usage of regex to match multi-tables

---

docs/content/connectors/postgres-cdc.md
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/table/DebeziumChangelogMode.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactory.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableSource.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java

This PR implements #1241 proposal with generic code but exposing support in configuration just for postgres module.
I am opening the PR to share one possible implementation of my proposal in a clearer way than words, feel free to close it if it is considered not relevant or not useful for the community.
Fixes #1241 
Unstable tests failing because of https://github.com/ververica/flink-cdc-connectors/pull/1181

[postgres] Add changelog mode configuration with upsert/retract modes

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/relational/JdbcSourceRecordEmitter.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/JdbcIncrementalSource.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/ChangeEventRecords.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SourceRecords.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/JdbcIncrementalSourceReader.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/JdbcSourceSplitReader.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceScanFetcher.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceStreamFetcher.java

Apply changes in #1505 to cdc-base.

[cdc-base] Let all records of one snapshot split don't cross checkpoints

---

flink-cdc-e2e-tests/pom.xml
flink-connector-postgres-cdc/pom.xml

There are 1 security vulnerabilities found in org.postgresql:postgresql 42.3.1
- [CVE-2022-31197](https://www.oscs1024.com/hd/CVE-2022-31197)
Upgrade org.postgresql:postgresql from 42.3.1 to 42.4.1 for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` failed locally, couldn't complete the build process.
Run `mvn clean test` failed locally, unit-test couldn't pass.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade org.postgresql:postgresql to 42.4.1

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java

related to #1149 
I debugged for a while and find the reason of stucking at the second split(not 100% percent second , could  be third or later but  always stuck) is that it triggers two split requests on one subtask at the same time.
When adding a new table to an existed flinkcdc task , if the old table has finished snapshot phase and has been consuming binlog.  It will read some binlog splits  before finding there is new table during task restart.
Here when a binlog split finished in MysqlSourceReader#onSplitFinished(...),  it actually activate next split twice.  
1. SuspendBinlogReaderAckEvent -> WakeupReaderEvent -> context.sendSplitRequest()
2.  directly  context.sendSplitRequest(). 
Which lead to two snapshot splits handled by one subtask , one split fetcher and one same debezium …

[mysql]fix duplicate split request for newly added table

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java

reduce number of BinlogSplitMetaEvent transmission between MySqlSoureReader and MySqlSourceEnumerator; fixed log MySqlSourceEnumerator

[Mysql]reduce number of BinlogSplitMetaEvent transmission between MySqlSoureReader and MySqlSourceEnumerator

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/DataSourceDialect.java

`JdbcSourceConfig` can be template type of `DataSourceDialect`.

[cdc-base] JdbcSourceConfig can be template type of DataSourceDialect

---

flink-cdc-base/pom.xml
flink-cdc-e2e-tests/pom.xml
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
flink-connector-debezium/pom.xml
flink-connector-mongodb-cdc/pom.xml
flink-connector-mysql-cdc/pom.xml
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlDeserializationConverterFactory.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/MySqlTestUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-oceanbase-cdc/pom.xml
flink-connector-oracle-cdc/pom.xml
flink-connector-postgres-cdc/pom.xml
flink-connector-sqlserver-cdc/pom.xml
flink-connector-test-util/pom.xml
flink-connector-tidb-cdc/pom.xml
pom.xml

Bumped Flink version to 1.15.1. 
Added Maven profile for Flink 1.14 compatibility.
Relates to #1363

[common] Add Flink 1.15 support. 

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/assigner/HybridSplitAssigner.java

Fix OffsetFactory is not initialized when restored from checkpoint.

[cdc-base] Fix OffsetFactory is not initialized when restored from checkpoint

---

flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/TiKVRichParallelSourceFunction.java

Signed-off-by: Yi Xie <xieyi01@rd.netease.com>
Link： https://github.com/ververica/flink-cdc-connectors/issues/1206

fix data loss in tidb-cdc when switch from snapshot read to change event read

---

docs/content/connectors/db2-cdc.md
docs/content/connectors/oracle-cdc.md

Correct reference link for DB2 docs

[hotfix][docs] Correct reference link for DB2 docs

---

flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/TiKVRichParallelSourceFunction.java
flink-connector-tidb-cdc/src/main/java/org/tikv/cdc/CDCClient.java
flink-connector-tidb-cdc/src/main/java/org/tikv/cdc/CDCEvent.java
flink-connector-tidb-cdc/src/main/java/org/tikv/cdc/RegionCDCClient.java
flink-connector-tidb-cdc/src/main/java/org/tikv/common/util/ChannelFactory.java
flink-connector-tidb-cdc/src/test/java/com/ververica/cdc/connectors/tidb/table/TiDBConnectorITCase.java
flink-connector-tidb-cdc/src/test/java/com/ververica/cdc/connectors/tidb/table/TiDBConnectorRegionITCase.java
flink-connector-tidb-cdc/src/test/resources/ddl/region_switch_test.sql

1. add cdc error event handler
2. fix issue when pull cdc event blocked

[fix][tidb-connector][#1631]  add cdc error event handle function 

---

docs/content/about.md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/formats/changelog-json.md
docs/content/quickstart/db2-tutorial.md
docs/content/quickstart/mongodb-tutorial.md
docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/quickstart/oceanbase-tutorial.md
docs/content/quickstart/oracle-tutorial.md
docs/content/quickstart/polardbx-tutorial.md
docs/content/quickstart/sqlserver-tutorial.md
docs/content/quickstart/tidb-tutorial.md
docs/content/快速上手/mongodb-tutorial-zh.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md
docs/content/快速上手/oceanbase-tutorial-zh.md
docs/content/快速上手/oracle-tutorial-zh.md
docs/content/快速上手/polardbx-tutorial-zh.md
docs/content/快速上手/sqlserver-tutorial-zh.md
docs/content/快速上手/tidb-tutorial-zh.md

Bump connector version to flink 1.15.2 in docs
Fix #1678

[docs] Bump connector version to flink 1.15.2 in docs

---

flink-connector-tidb-cdc/src/main/java/org/tikv/cdc/CDCClient.java

For this pr https://github.com/ververica/flink-cdc-connectors/pull/1686.

[hotfix] Add method getMaxResolvedTs back to class CDCClient.

---

flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/TiKVRichParallelSourceFunction.java

Describe the bug(Please use English)
Environment :
Flink version : 1.14
Flink CDC version: 2.3
Database and version: 5.1
To Reproduce
Steps to reproduce the behavior:
The error :
``2022-10-27 12:48:34,981 INFO org.tikv.cdc.CDCClient [] - handle resolvedTs: 436953707961122840, regionId: 1721083
2022-10-27 12:48:35,469 INFO org.tikv.cdc.CDCClient [] - handle resolvedTs: 436953708092194817, regionId: 10236245
2022-10-27 12:48:35,469 INFO org.tikv.cdc.CDCClient [] - handle resolvedTs: 436953708092194817, regionId: 10237829
2022-10-27 12:48:35,469 INFO org.tikv.cdc.CDCClient [] - handle resolvedTs: 436953708092194817, regionId: 8419115
2022-10-27 12:48:35,477 INFO org.tikv.cdc.CDCClient [] - handle resolvedTs: 436953708092194820, regionId: 7318373
2022-10-27 12:48:35,477 INFO …

[bug][tidb-connector]checkpoint is not updated long after a task has been running 

---

pom.xml

This PR excludes automatically generated folder `docs/_build` from apache-rat-plugin. If a developer builds the docs then build the project, the rat plugin will scan the folder and show error

[hotfix] Exclude auto-generated files in docs from apache-rat-plugin

---

docs/content/connectors/oracle-cdc.md
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/table/OracleTableSource.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/table/OracleTableSourceFactory.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleTableSourceFactoryTest.java

oracle table source Add missing parameters

[oracle] oracle table source Add missing parameters

---

docs/content/connectors/db2-cdc.md
flink-connector-db2-cdc/src/test/java/com/ververica/cdc/connectors/db2/Db2SourceTest.java

[db2] Fix stream api example in db2 doc.

[db2] Fix stream api example in db2 doc.

---

docs/content/connectors/oracle-cdc.md

…shot framework for Oracle CDC Connector config

Oracle cdc doc

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/offset/BinlogOffset.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/SerializerUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/utils/SerializerUtilsTest.java

This pull request fixes a backward compatibility issue on deserializing binlog offset from old versions (#1757), and add a new test for guarding the compatibility.

[mysql] Fix backward compatibility on deserializing binlog offset from old versions

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/internal/Handover.java

In our production system, I've seen exceptions about rejected snapshots, but I was not able to find the root cause (e.g. the exception in the handover). 
This change is adding the exception as the cause to the `FlinkRuntimeException` we throw in the `snapshotState` method.

[hotfix] Forward root cause in DebeziumSourceFunction

---

.github/workflows/build_docs.yml

https://github.com/ververica/flink-cdc-connectors/actions/runs/3785546870/jobs/6435677503
```
+ make -C docs clean
make: Entering directory '/__w/flink-cdc-connectors/flink-cdc-connectors/docs'
make: Leaving directory '/__w/flink-cdc-connectors/flink-cdc-connectors/docs'
++ git for-each-ref '--format=%(refname:lstrip=-1)' refs/remotes/origin/
++ grep -iE '^(release-|master)'
fatal: detected dubious ownership in repository at '/__w/flink-cdc-connectors/flink-cdc-connectors'
To add an exception for this directory, call:
git config --global --add safe.directory /__w/flink-cdc-connectors/flink-cdc-connectors
```

[ci] Fix for dubious repo ownership issue

---

flink-connector-mongodb-cdc/pom.xml

Fix authentication error when using a non admin auth source and duplicated usernames.
#1934

[mongodb][hotfix] Fix authentication error when using a non admin auth source and duplicated usernames

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/dialect/MongoDBDialect.java

Use unmatch resume token may cause resume token not found problem under MongoDB 4.4.x.
May fix #1879.

[mongodb][hotfix] Fix resume token not found problem #1879

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java

Throw an exception when the table has no primary key set instead of catching it,In this way, the flink job will failover, and users can find the problem faster.

[Flink][Improvement]Throw an exception when the table has no primary key set instead of catching it

---

docs/content/connectors/mongodb-cdc.md

Remove duplicate 'batch.size' options.
Fix #1989 
There are duplicate 'batch.size' options. The second 'batch.size' option is described incorrectly, we need to remove it.
```
<tr>
<td>batch.size</td>
<td>optional</td>
<td style="word-wrap: break-word;">1024</td>
<td>Integer</td>
<td>The cursor batch size.</td>
</tr>
<tr>
<td>batch.size</td>
<td>optional</td>
<td style="word-wrap: break-word;">0</td>
<td>Integer</td>
<td>Change stream cursor batch size. Specifies the maximum number of change events to return in each batch of the response from the MongoDB cluster. The default is 0 meaning it uses the server's default value.</td>
</tr>
```

[Doc][MongoDB CDC] Remove duplicate 'batch.size' options

---

docs/content/connectors/postgres-cdc.md
flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/PostgresE2eITCase.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/PostgreSQLSource.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactory.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/PostgreSQLSourceTest.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java

Change config option slot.name to be required, see #1386.

[postgres] Change config option slot.name to be required

---

docs/content/connectors/db2-cdc.md

db2 cdc doc modify , char type should be character type . linked below
https://www.ibm.com/docs/en/db2-for-zos/12?topic=columns-string-data-types

fix(db2-doc): for db2 , char should be CHARACTER

---

flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleConnectorITCase.java

ignore OracleConnectorITCase.testConsumingAllEvents util issue 1875 fix

[oracle][test]ignore OracleConnectorITCase.testConsumingAllEvents util issue 1875 fix

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/DebeziumUtils.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceBuilder.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlChunkSplitter.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/config/MySqlSourceConfig.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/config/MySqlSourceConfigFactory.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/ChunkUtils.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSource.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/table/MySqlTableSourceFactory.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer.sql
flink-connector-mysql-cdc/src/test/resources/ddl/inventory.sql

[mysql] Support tables which do not contain a primary key (#1827)

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/testutils/UniqueDatabase.java
flink-connector-mysql-cdc/src/test/resources/ddl/customer3.0.sql

[mysql] Fix NullPointerException when database name or table name contains dot

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/task/context/StatefulTaskContext.java
flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/util/ErrorMessageUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/MySqlTestUtils.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceTestBase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-connector-mysql-cdc/src/test/java/io/debezium/connector/mysql/util/ErrorMessageUtilsTest.java
flink-connector-mysql-cdc/src/test/resources/docker/server-gtids/expire-seconds/my.cnf

[mysql-cdc] Optimize the error msg when binlog expire or server id conflict

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/MongoRecordUtils.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorDeserializationSchema.java

[MongoDB] Fix NullPointerException when executing ddl operation in MongoDB
Fix: #2106 
When performing DDL operations in MongoDB, documentKey and fullDocument are null, so we need to check if it is a DML operation and retrieve documentKey and fullDocument from the record.
```java
if (isDMLOperation(op)) {
documentKey =
checkNotNull(
extractBsonDocument(
value, valueSchema, MongoDBEnvelope.DOCUMENT_KEY_FIELD));
fullDocument =
extractBsonDocument(value, valueSchema, MongoDBEnvelope.FULL_DOCUMENT_FIELD);
}
```

[MongoDB] Fix NullPointerException when executing ddl operation in MongoDB

---

flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseRichSourceFunction.java

Reconnect to oblogproxy with the same client id while the previous connection is not closed will cause exception 'Duplication exist clientId' at oblogproxy server side. So the process should always cleanup the connections before exit the source function.
Related: https://github.com/oceanbase/oblogproxy/issues/46

[oceanbase] always cleanup connections before exit

---

docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/MongoDBSource.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBEnvelope.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/MongoDBSourceBuilder.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceConfig.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceConfigFactory.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceOptions.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBScanFetchTask.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBStreamFetchTask.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/MongoRecordUtils.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/MongoUtils.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSourceFactory.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/LegacyMongoDBSourceTest.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java

Add support for mongodb+srv connection protocol.
Close #2049.

[mongodb] Add support for mongodb+srv connection protocol.

---

docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/oracle-cdc.md
docs/content/connectors/sqlserver-cdc.md

Add docs for close idle readers feature.

[doc] Add docs for close idle readers feature.

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBStreamFetchTask.java

Fix drop or rename record cause documentKey being empty.
Close #1963.

[mongodb][hotfix] Fix drop or rename record cause documentKey being empty

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/AssignerStatus.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/NewlyAddedTableITCase.java
tools/azure-pipelines/jobs-template.yml

When the newly added table finishes (Assigner status is NEWLY_ADDED_ASSIGNING_FINISHED) and then job failsover before a success checkpoint, the snapshotSplits of newly added table will be added back, and are assigned to taskmanager later. However, taskmanager will first start MySqlBinlogSplit read task after failover, the the later assigned snapshotSplits will never be processed if the job parallelism is 1.  Also the binlog of newly added table will never be processed, as shown in the log below。
```
2023-01-31 23:40:45.283 [blc-9.134.34.15:3306] MySqlStreamingChangeEventSource.java:1222 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.000101/143162238
2023-01-31 …
```

[mysql-cdc] Fix newly-added-table failed if job failover before a success checkpoint

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlBinlogSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/NewlyAddedTableITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java

As mentioned in [Issue#913](https://github.com/ververica/flink-cdc-connectors/issues/913), when a task is stopped and its configuration changed, there might be redundant table information remaining in the states of SplitAssigner and SourceReader.
The current functionality of scanning newly added tables will removing and cleaning up table info in the previous savepoint according to the new configuration.
The changes proposed in this PR is as follows:
In MySqlSplitAssigner, it will apply the new filter in the new configuration and remove redundant table info
In MySqlSourceReader, it will sieve out splits that do not match the new filter.

Remove table and clean up redundant state info when scanning newly added table

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/CollectionDiscoveryUtils.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBRegexFilterITCase.java
flink-connector-mongodb-cdc/src/test/resources/ddl/ns-regex.js

Fix regex inference of database or collection only contains dash.
Close #2152 , #2012

[mongodb][hotfix] Fix regex inference of database or collection only contains dash.

---

docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/assigner/StreamSplitAssigner.java
flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/offset/OffsetFactory.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/offset/BinlogOffset.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/experimental/offset/BinlogOffsetFactory.java
flink-connector-mongodb-cdc/pom.xml
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/MongoDBSource.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/MongoDBSourceBuilder.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceOptions.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/offset/ChangeStreamOffsetFactory.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSourceFactory.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBConnectorITCase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/meta/offset/RedoLogOffsetFactory.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/offset/LsnFactory.java

This may close #1787, #1584, #876

[mongodb] Support specific timestamp startup mode.

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/IncrementalSourceScanFetcher.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/offset/LsnOffset.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerScanFetchTask.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerSourceFetchTaskContext.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/source/read/fetch/SqlServerScanFetchTaskTest.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/testutils/RecordsFormatter.java

[sqlserver] Merge high and low watermark data during snapshot reading process

---

flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/PostgresDialect.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/enumerator/PostgresSourceEnumerator.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresScanFetchTask.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresSourceFetchTaskContext.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/PostgreSQLSourceTest.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/PostgresTestBase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLSavepointITCase.java

Fix #2248 .
TODO: cp to master branch.

[postgres] Fix the slot name conflict bug

---

flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/SqlServerSourceBuilder.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableFactory.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableSource.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTableFactoryTest.java

[hotfix][sqlserver] Fix sqlserver close idle and chunk key column missing

[hotfix][sqlserver] Fix sqlserver close idle and chunk key column missing

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java

[mysql] Fix assigning duplicate snapshot splits when enable scan newly added tables

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java

Fix #2095 
I carefully debugged the bug and there is the analysis:
1、In MySqlSnapshotSplitAssigner, split table happens asynchronously
2、After the finish of every table split the table will be moved from remaining table 
3、After tm calls getNext() from  MySqlSnapshotSplitAssigner, the table will be added to alreadyProcessedTables
4、However when job restarts and open scanNewlyAddedTableEnabled and discover newly added table, it gets into the following logic
The alreadyProcessedTables + remainingTables won't always be euqals to the tables splitted in the last run.
This happens when table is so large and tm can't process split on time. 
For example:
1、The task reads from A and B, and each of them split into 1000 chunks 
2、The remaingTable is empty since they are already splitted, but …

[Mysql] Fix duplicate split which cause duplicate data when open scanNewlyAddedTableEnabled

---

flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/dialect/SqlServerDialect.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/utils/SqlServerConnectionUtils.java
flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerConnectorITCase.java
flink-connector-sqlserver-cdc/src/test/resources/ddl/product.sql

[hotfix] Fix sqlserver monitor same table in other database

---

flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/MongoE2eITCase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/utils/MongoDBContainer.java

Currently MongoDB E2E test has rather tight limitations. Container startup time limit is 30 seconds, and each E2E test are expected to complete data capturing in 60 seconds. When Azure pipeline is busy, unexpected timeout exception might occur.
This PR loosens container startup timeout to 120 seconds (closer to TiDB, PolarDB, and OceanBase) and capturing timeout to 150 seconds (like DB2).

[mongodb] [tests] Loosen E2E timeout limitations

---

docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/MongoDBSourceBuilder.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceConfig.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceConfigFactory.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceOptions.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBScanFetchTask.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSourceFactory.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java

This PR fixes issue #2302.
Currently, MongoDB CDC uses `noCursorTimeout` option when performing incremental snapshot. However, some MongoDB server doesn't support creating cursor with unlimited timeout.
To address this issue, an option `disableCursorTimeout` was added in `mongodb.source.MongoDBSource` (but not its legacy counterpart `mongodb.MongoDBSource` since it isn't affected).

[mongodb] Add `disableCursorTimeout` option, addresses #2302

---

docs/content/connectors/postgres-cdc.md

PostgresSourceBuilder is private, failed to compile.

[doc] fix errors in PostgresParallelSourceExample

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBFetchTaskContext.java

This fixes `MongoDBFetchTaskContext#isRecordBetween` checking function which may close #2183.

[mongodb] Fix SourceRecord range check

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/metrics/SourceReaderMetrics.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/internal/DebeziumChangeFetcher.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/internal/MetricRecord.java
flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/utils/DebeziumSourceMetricConstants.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/internal/MongoDBConnectorSourceTask.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/MongoDBRecordEmitter.java

This PR contains following changes:
* Added `pendingRecords` and `numRecordsInErrors` for CDC connector metrics
* Registered above two metrics in MongoSource (Legacy)
* Registered `numRecordsInErrors` metric in MongoSource (Modern)
Some concerns:
* `pendingRecords` now yields how many records `ConnectorSourceTask::poll()` received. However it won't exceed `poll.max.batch.size`, so it won't be accurate when pending data is huge.
* Currently, metric guage registering is hard-encoded in base classes, so this change affects every CDC connector. Maybe we should allow each connector decide its metrics?

[mongodb] Add `pendingRecords` and `numRecordsInErrors` metrics for legacy source

---

flink-connector-db2-cdc/src/test/java/com/ververica/cdc/connectors/db2/table/Db2ConnectorITCase.java

Currently, Db2ITCase fails occasionally due to attempts to cancel jobs which isn't running. Fixed this by adding a wrapper function and ignoring any `IllegalStateException`.

[db2] [tests] Fix `Db2ConnectorITCase` cleanup failure

---

flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceExampleTest.java

[mysql] fix com.ververica.cdc.connectors.mysql.source.MySqlSourceExampleTest#testConsumingAllEvents

---

flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/PostgreSQLSourceTest.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/PostgresTestBase.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java

Fix the test problem in [#2393](https://github.com/ververica/flink-cdc-connectors/issues/2393)
1. stop postgres docker container after test
2. don't the static **POSTGRES_CONTAINER** when get jdbc url
* Unit Tests
* Integration Tests (including covering migration scenarios)
* Connector Test Framework Integration

[Bug][Postgres] fix: the execution of the test case as a whole fails, while the individual execution succeeds

---

flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/TiDBE2eITCase.java
flink-connector-tidb-cdc/src/test/java/com/ververica/cdc/connectors/tidb/TiDBTestBase.java

a test branch to check whether this image can avoid `tikv disk full` like 
https://github.com/ververica/flink-cdc-connectors/pull/2400/checks?check_run_id=15945681519
since this issue had been resolved in https://github.com/tikv/tikv/pull/10264. 
will try to verify whether 6.1.0 is supportable and update the doc later.

[ci] avoid `tikv disk full` failure

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/TableDiscoveryUtils.java

We can filter out unnecessary databases before executing the "show full table" statement

[minor][mysql] Filter databases that do not need to be read

---

docs/content/connectors/oracle-cdc.md

[Doc] Fix Oracle document errors 
fix #2407

[Doc] Fix Oracle document errors 

---

flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlDefaultValueConverter.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java

Fix parsing DDL bug which is introducing by merging from 1.9.7 debezium.

[hotfix][mysql] Trim default value for BIGINT and SMALLINT types when parsing MySQL DDL

---

flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/dialect/SqlServerChunkSplitter.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/offset/LsnOffset.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerScanFetchTask.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerSourceFetchTaskContext.java
flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerStreamFetchTask.java
flink-connector-sqlserver-cdc/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java

[sqlserver] Fix backfill stream task hang

---

flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/OracleScanFetchTask.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/OracleStreamFetchTask.java
flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/table/OracleTableSource.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/OracleSourceTest.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/source/OracleSourceITCase.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleConnectorITCase.java

[oracle] Correct the naming error
Oracle reads the redo log instead of the binlog.
fix #2404

[oracle] Correct the naming error

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SourceSplitSerializer.java
flink-cdc-base/src/test/java/com/ververica/cdc/connectors/base/source/meta/split/SourceSplitSerializerTest.java

[hotfix] [base] fix TableId.java use identifier decode error with four quota

---

flink-cdc-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/MongoE2eITCase.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/dialect/MongoDBDialect.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/MongoDBFullChangelogITCase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/MongoDBSourceTestBase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBRegexFilterITCase.java
flink-connector-mongodb-cdc/src/test/resources/ddl/ns-dotted.js

For now, [MongoDB allows](https://www.mongodb.com/docs/manual/reference/limits/#mongodb-limit-Restriction-on-Collection-Names) collection names containing dots (`.`). According to [Mongo CDC docs](https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mongodb-cdc.html#connector-options), it should be ok to match them with fully-qualified regex like this:
```javascript
db[.]coll[.]name[.]with[.]dots // matches collection "coll.name.with.dots" in "db" database
```
However, it doesn't work when incremental snapshot option is enabled. Here's the minimum POC:
```java
@Test
public void testMatchCollectionWithDots() throws Exception {
// 1. Given colllections:
// db: [coll.name]
String db = CONTAINER.executeCommandFileInSeparateDatabase("ns-dotted");
TableResult result = …
```

[hotfix] Mongo CDC fails to capture collections with `.` in names

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java

try to fix https://github.com/ververica/flink-cdc-connectors/issues/2421

[mysql] Fix newly added table invalid request meta group id error(#1327)

---

flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java

Commit https://github.com/ververica/flink-cdc-connectors/commit/44cd46e227a5e772a6f740b3a8664b8e8afd2c77 introduces a change that using [.] as delimiter between database name and collection name to avoid conflicts between dot (`.`) and regex meta character. However this turns out to be unnecessary since in Regex mode, full qualified names will always be used and no pasting will be performed then, and such change will deteriorate performance.
This PR reverts the change above.

fix: mongo collection regex match logic

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/IncrementalSourceScanFetcher.java

The executor in `IncrementalSourceScanFetcher` ignores the uncaught exception.
If an error like `OutOfMemoryError` occurs, the taskmanager hangs forever.
Closes #2510

[cdc-base][hotfix] Fix TM hangs caused by uncaught exception

---

flink-connector-db2-cdc/src/test/java/com/ververica/cdc/connectors/db2/Db2SourceTest.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/LegacyMongoDBSourceTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/LegacyMySqlSourceExampleTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/LegacyMySqlSourceTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/MySqlValidatorTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/SpecificStartingOffsetITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlBinlogSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssignerTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlRecordEmitterTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MysqlConnectorCharsetITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/polardbx/PolardbxCharsetITCase.java
flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/polardbx/PolardbxSourceITCase.java
flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/OracleSourceTest.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/PostgreSQLSourceTest.java
flink-connector-vitess-cdc/src/test/java/com/vervetica/cdc/connectors/vitess/VitessSourceTest.java

In mysql and postgres test unit, the connections to database and Flink cluster are not closed after test.
This connections may influence other test unit.

[test] close jdbc and client after each test

---

flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/PostgresDialect.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/enumerator/PostgresSourceEnumerator.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/testutils/UniqueDatabase.java

In PostgresSourceEnumerator#createSlotForGlobalStreamSplit, PostgresReplicationConnection will be closed after create slot.
However, not any PostgresReplicationConnection.close will close the PostgresConnection in messageDecoder, which is generated by Hikari pool and is passed to PostgresReplicationConnection.
See AbstractMessageDecoder.close:
*  NonStreamingWal2JsonMessageDecoder.close： do nothing
* PgProtoMessageDecoder.close: do nothing
* StreamingWal2JsonMessageDecoder.close: do nothing
* PgOutputMessageDecoder.close: **the only one to close jdbc connection**.
Thus, the Hikari pool will be full if there is too much pg source.
Debug  PostgresReplicationConnection.close in any test.

[postgres] close jdbc connection when close replication connection

---

flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/JdbcSourceFetchTaskContext.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresScanFetchTask.java
flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresSourceFetchTaskContext.java
flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/source/PostgresSourceITCase.java

Fix https://github.com/ververica/flink-cdc-connectors/issues/2431

[postgres] never drop slot for stream split, which is also global split

---

flink-cdc-e2e-tests/src/test/resources/log4j2-test.properties

There is no `log4j2-test.properties` file in e2e tests, so it's hard to find problem in test.Now add `log4j2-test.properties` flie to e2e tests.

[tests][e2e] add log properties file to e2e tests

---

flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java

Currently, in DebeziumSourceFunction, some properties are hardcoded, such as `include.schema.changes`, so that even opening this property peripherally will not work. 
Therefore, the modification is that if the key exists in the `properties`, it will not be overwritten.

[Improve]Support customer debezium properties in DebeziumSourceFunction

---

flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/MySqlValidator.java

This is an optimization of code structure. Use automatic resource management to replace 'try - finally'  code block because of JdbcConnection implemented AutoCloseable interface.

[mysql] Use automatic resource management to replace 'try - finally'  code block.

---

docs/content/connectors/mongodb-cdc(ZH).md
docs/content/connectors/mongodb-cdc.md
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/MongoDBSourceBuilder.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/assigners/splitters/SampleBucketSplitStrategy.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/assigners/splitters/ShardedSplitStrategy.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/assigners/splitters/SplitContext.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceConfig.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceConfigFactory.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/config/MongoDBSourceOptions.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSourceFactory.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/MongoDBFullChangelogITCase.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/reader/MongoDBSnapshotSplitReaderTest.java
flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java

Use SampleBucketSplitStrategy for shard collection which contain hashed key, this would avoid OOM exception if some chunk contains huge records which could not be hold in a local HashMap.
Close #2504

Use SampleBucketSplitStrategy for shard collection with hashed keys #2504

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/source/MetadataAccessor.java

Add `getTableSchema` method for `MetadataAccessor`

[3.0][cdc-common] Add getTableSchema method for MetadataAccessor

---

flink-cdc-composer/src/main/java/com/ververica/cdc/composer/PipelineComposer.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/PipelineExecution.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/PipelineDef.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/RouteDef.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/SinkDef.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/SourceDef.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/TransformDef.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineExecution.java

This pull request implements #2608, which introduces base interfaces exposed to upper-level CLI, including:
- `PipelineComposer`: interface for composer
- `PipelineDef`: Java object abstracting a pipeline definition
- `PipelineExecution`: Abstraction for an execution of the pipeline
And a Flink implementation (just a framework without solid composing logic) is made as a proof of concept.

[flink-cdc-composer] Base interfaces and models for composer and pipeline definition

---

pom.xml

This pull request implement #2657, which introduces JUnit 5 and AssertJ dependencies in the root pom, including:
- Use `junit-bom` in dependency management to pin JUnit 5 versions for all modules
- Introduce AssertJ as global test dependency
- Bump `maven-surefire-plugin` version to 3.0.0-M5, which has better support for JUnit 5

[test] Introduce JUnit 5 and AssertJ dependencies

---

README.md
docs/content/about.md
docs/content/connectors/db2-cdc.md
docs/content/connectors/mongodb-cdc.md
docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
docs/content/connectors/oceanbase-cdc.md
docs/content/connectors/oracle-cdc.md
docs/content/connectors/postgres-cdc.md
docs/content/connectors/sqlserver-cdc.md
docs/content/connectors/tidb-cdc.md
docs/content/quickstart/build-real-time-data-lake-tutorial.md
docs/content/quickstart/db2-tutorial.md
docs/content/quickstart/mongodb-tutorial.md
docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/quickstart/oracle-tutorial.md
docs/content/quickstart/polardbx-tutorial.md
docs/content/quickstart/sqlserver-tutorial.md
docs/content/quickstart/tidb-tutorial.md
docs/content/快速上手/build-real-time-data-lake-tutorial-zh.md
docs/content/快速上手/mongodb-tutorial-zh.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md
docs/content/快速上手/oceanbase-tutorial-zh.md
docs/content/快速上手/oracle-tutorial-zh.md
docs/content/快速上手/polardbx-tutorial-zh.md
docs/content/快速上手/sqlserver-tutorial-zh.md
docs/content/快速上手/tidb-tutorial-zh.md

As showed in https://github.com/ververica/flink-cdc-connectors/issues/2526, Flink CDC 2.5 is no longer supported for flink 1.13, thus remove support for Flink 1.13 in docs and upgrade Flink version in tutorial.

[docs] Remove support for Flink 1.13 in docs and upgrade Flink version in tutorial

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/event/AddColumnEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/AlterColumnTypeEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/CreateTableEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DropColumnEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/RenameColumnEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/SchemaChangeEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/TableId.java

this closes https://github.com/ververica/flink-cdc-connectors/issues/2642
@leonardBang @Jiabao-Sun @PatrickRen  PTAL.

[3.0][cdc-common] Add SchemaChangeEvent implementations

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DataChangeEvent.java

Refer to #2665 
Change DataChangeEvent from interface to class, and add implementation for DataChangeEvent.
PTAL. @lvyanquan @GOODBOY008

[3.0][cdc-common] Change DataChangeEvent from interface to class, and add implementation for DataChangeEvent.

---

flink-cdc-composer/pom.xml
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/utils/FactoryDiscoveryUtils.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/FactoryDiscoveryUtilsTest.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSinkFactory1.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSinkFactory2.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSourceFactory1.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSourceFactory2.java
flink-cdc-composer/src/test/resources/META-INF/services/com.ververica.cdc.common.factories.Factory
flink-cdc-composer/src/test/resources/log4j2-test.properties

After https://github.com/ververica/flink-cdc-connectors/pull/2661#pullrequestreview-1717126037 merged will carry on.
[3.0][flink-cdc-composer] Connector JAR discovery utilities.
Close #2620

[3.0][flink-cdc-composer] Connector JAR discovery utilities

---

docs/content/quickstart/mysql-postgres-tutorial.md
docs/content/quickstart/polardbx-tutorial.md
docs/content/快速上手/mysql-postgres-tutorial-zh.md
docs/content/快速上手/polardbx-tutorial-zh.md
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/test/java/com/ververica/cdc/cli/CliFrontendTest.java
flink-cdc-cli/src/test/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/enumerator/IncrementalSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/IncrementalSourceScanFetcher.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/external/IncrementalSourceStreamFetcher.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/SnapshotSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssignerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/TiKVRichParallelSourceFunction.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/main/java/com/ververica/cdc/connectors/tidb/table/utils/TableKeyRangeUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/main/java/org/tikv/cdc/CDCClient.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/main/java/org/tikv/cdc/RegionCDCClient.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/src/main/java/com/ververica/cdc/connectors/vitess/VitessValidator.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
pom.xml

Upgrade Guava to version 31 to get compatibility with Flink 1.18

Change Guava version to 31 and Flink to 1.18

---

flink-cdc-cli/pom.xml
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/CliExecutor.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/CliFrontend.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/PipelineDefinitionParser.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/utils/ConfigurationUtils.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/utils/FlinkEnvironmentUtils.java
flink-cdc-cli/src/test/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/ConfigOption.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/ConfigOptions.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/Configuration.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/ConfigurationUtils.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/FallbackKey.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/StructuredOptionsSplitter.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/BlockElement.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/Description.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/DescriptionElement.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/Formatter.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/HtmlFormatter.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/InlineElement.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/LineBreakElement.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/LinkElement.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/ListElement.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/configuration/description/TextElement.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/utils/TimeUtils.java
flink-cdc-composer/pom.xml
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/PipelineDef.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/SinkDef.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/SourceDef.java

This pull request introduces `Configuration` and its related utilities such as `ConfigOption`, and migrate current usage of Flink `Configuration` to CDC's own one in `flink-cdc-composer` and `flink-cdc-cli`.
Please note that most code blocks are borrowed from Flink, and some deprecated and redundant methods are dropped.

[common] Introduce Configuration and related utilities

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/DataSinkFactory.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/DataSourceFactory.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/Factory.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/FactoryHelper.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSinkFactory1.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSinkFactory2.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSourceFactory1.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSourceFactory2.java
flink-cdc-connect/flink-cdc-source-connectors/pom.xml

Refer to #2666
We should add 'ConText' with options for Source/Sink initialization.

[3.0][cdc-common] Add ConText for Source/Sink initialization.

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/factories/Factory.java
flink-cdc-composer/pom.xml
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSinkFactory1.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSinkFactory2.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSourceFactory1.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/factory/DataSourceFactory2.java

As we have own ConfigOption, we should use 'ConfigOption' of cdc-common in Factory.
cc @lvyanquan @GOODBOY008

[3.0][cdc-common] Use 'ConfigOption' of cdc-common.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/MongoDBSourceBuilder.java

Comma-separated format parameter (e.g. "db1.col1,db2.col2") is supported in legacy source, but is not in incremental snapshot source for datastream jobs.

[mongodb] incremental snapshot source supports comma-separated format parameter for databases and collections

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerDeserializationConverterFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerTimezoneITCase.java

Fix https://github.com/ververica/flink-cdc-connectors/issues/2637

[sqlserver] Fix timestamp type parse of sqlserver

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Selectors.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/TableFilter.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/text/ParsingException.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/text/Position.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/text/TokenStream.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/utils/Predicates.java
flink-cdc-common/src/test/java/com/ververica/cdc/common/schema/SelectorsTest.java

Close #2669
[cdc-common] Introduce CollectionFilter to filter collection from given TableId pattern

[cdc-common] Introduce CollectionFilter to filter collection from given TableId pattern

---

docs/content/quickstart/datastream-api-package-guidance.md
docs/content/quickstart/index.md
docs/content/快速上手/datastream-api-package-guidance-zh.md
docs/content/快速上手/index.md

DataStream-api-package-guidance

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/factory/ValuesDataFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/source/ValuesDataSource.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/source/ValuesDataSourceHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/source/ValuesDataSourceOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/test/java/com/ververica/cdc/connectors/values/source/ValuesDataSourceITCase.java

add MULTI_SPLITS_SINGLE_TABLE to provide multiple splits case of ValuesDataSourceHelper.

[cdc-pipeline-connector] add MULTI_SPLITS_SINGLE_TABLE to provide multiple splits case of ValuesDataSourceHelper.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseConnection.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseRichSourceFunction.java

This pr changed the startup order of snapshot and change events reading, and it will reduce the risk of change events buffer OOM.

[oceanbase] Use global timestamp to start log client

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/schema/Schema.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/utils/SchemaUtils.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/schema/coordinator/SchemaManager.java
flink-cdc-runtime/src/test/java/com/ververica/cdc/runtime/operators/schema/coordinator/SchemaManagerTest.java

add PublicEvolving annotation to SchemaUtils, add modify code of SchemaManager to reuse the method of SchemaUtils.
@PatrickRen CC.

[cdc-common] add PublicEvolving annotation to SchemaUtils.

---

flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/sink/DataSinkWriterOperator.java

This pull request improves DataSinkWriterOperator logic that only emit latest schema for events that are not CreateTableEvent. Otherwise, sink will receive multiple CreateTableEvent for one table, which is unexpected.

[cdc-runtime] Improve DataSinkWriterOperator logic that only emit latest schema for events that are not CreateTableEvent

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/source/ValuesDataSourceHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/test/java/com/ververica/cdc/connectors/values/source/ValuesDataSourceITCase.java

Because `default` may be keyword  for some connectors, and could not be a name of database like doris.

[cdc-pipeline-connector][values] Avoid using `default` as name of namespace and schema.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBFetchTaskContext.java

Fix [#2759](https://github.com/ververica/flink-cdc-connectors/issues/2759)

[Bug][mongo] Fix MongoDB's rewriteOutputBuffer to emit +I rather than +U(or -U)

---

flink-cdc-dist/src/main/flink-cdc-bin/bin/flink-cdc.sh

This pull request introduces a shell script, #2606, `flink-cdc.sh`, that will be the main entrypoint of the Flink CDC project. This shell script sets up:
- Java classpath for running Flink CDC CLI
- Java environment
- log4j configurations
and then pull up the JVM to run `CliFrontend`.

[cdc-dist] Introduce flink-cdc.sh as the entrypoint of the Flink CDC

---

flink-cdc-composer/pom.xml
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/utils/FactoryDiscoveryUtils.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/utils/FactoryDiscoveryUtilsTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/sink/ValuesDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/source/ValuesDataSourceHelper.java

This pull request adds integration test for `FlinkPipelineComposer`

[cdc-composer] Add integration test for FlinkPipelineComposer

---

docs/content/connectors/mysql-cdc(ZH).md
docs/content/connectors/mysql-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/ddl/inventory.sql

dbzObj may be string when mysql cdc set with param 'debezium.binary.handling.mode' = 'base64'.
So add
```java
if (dbzObj instanceof String) {
String data = (String) dbzObj;
return data.getBytes(StandardCharsets.UTF_8);
} 
```

[debezium] Improve convertToBinary for RowDataDebeziumDeserializeSchema

---

flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/pom.xml

This pull request adds a logic in composer that discovers runtime and common JARs (usually the same one `flink-cdc-dist`) and submit then to the Flink cluster together with job graph. 
The dependencies of `flink-cdc-pipeline-connectors` are marked as `provided`, in order to not bundling `flink-cdc-runtime` and `flink-cdc-common` into connector JARs.

[cdc-composer] Add common and runtime JAR on submit

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/source/SqlServerSourceITCase.java

Fix UT errors by increasing the wait time after committing SQL.
commit() can't be  not effective when wait 1s. So change 1s to 5s.

[cdc-connector][sqlserver][tests] Fix UT errors by increasing the wait time after committing SQL

---

pom.xml

This pull request sets `trimStacktrace` to false in maven-surefire-plugin to keep the full stacktrace on test failure.

[build] Let surefire plugin to keep the full stacktrace on test failure

---

flink-cdc-cli/src/main/java/com/ververica/cdc/cli/utils/FlinkEnvironmentUtils.java
flink-cdc-cli/src/test/java/com/ververica/cdc/cli/CliFrontendTest.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-dist/src/main/flink-cdc-bin/bin/flink-cdc.sh

This pull request adds support to submit Flink CDC pipeline job to more Flink deployments, such as YARN. 
Please note that there are still many things that can be improved comparing to the native `flink run` or SQL client. For example to submit to a YARN session cluster, user needs to set `execution.target: yarn-session` and `yarn-application-id: {flink-app-id}` in order to make everything works.

[cdc-cli][cdc-composer][cdc-dist] Support submitting job to general Flink environment

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlDataSourceOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlPipelineITCase.java

The pipeline framework supports schema evolution by default, we should enable send schema change by default for mysql pipeline source

[pipeline-connector][mysql] Enable send schema change by default

---

docs/content/connectors/oceanbase-cdc(ZH).md
docs/content/connectors/oceanbase-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/OceanBaseSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseTableSourceFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/java/com/ververica/cdc/connectors/oceanbase/table/OceanBaseTableFactoryTest.java

Add option to support more [libobcdc configs](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000221095).

[oceanbase] add option for obcdc extra configs

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/utils/MySqlTypeUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlMetadataAccessorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/schema/MySqlTypeUtils.java

Ensure the inference of `MEDIUMINT UNSIGNED` type matches table schema.
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html

[cdc-pipeline-connector][mysql] Ensure the inference of MEDIUMINT_UNSIGNED type matches table schema

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java

This supports users upgrading from v2.2.0, where the flag is not present
Verified by starting a Flink job using this branch, which had a previous save point written from v2.2.0
Closes https://github.com/ververica/flink-cdc-connectors/issues/2549

[mysql] Fix attempted load of isSuspended in MySqlSplitSerializer::deserializeSplit

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlDataSource.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/source/MySqlEventDeserializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/event/DebeziumEventDeserializationSchema.java

Remove unnecessary serverTimeZone in DebeziumEventDeserializationSchema.

[cdc-pipeline-connector][mysql] Remove unnecessary serverTimeZone in DebeziumEventDeserializationSchema

---

flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/OceanBaseE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/com/ververica/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/resources/ddl/mysql_inventory.sql
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/resources/ddl/oceanbase_inventory.sql
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/resources/docker/oceanbase/setup.sql

[e2e] Add OceanBase e2e test case

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/pipeline/PipelineOptions.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/flink/translator/DataSourceTranslator.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/flink/FlinkPipelineComposerITCase.java

This pull request removes prefix `pipeline.` from pipeline options to simply user configurations.

[cdc-common] Remove prefix of pipeline options

---

flink-cdc-cli/src/main/java/com/ververica/cdc/cli/CliFrontend.java
flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-dist/src/main/flink-cdc-bin/bin/flink-cdc.sh
flink-cdc-dist/src/main/flink-cdc-bin/conf/flink-cdc.yaml

This pull request adds support to read global pipeline config from FLINK_CDC_HOME/conf/flink-cdc.yaml.

[cdc-cli][cdc-dist] Support loading global config from FLINK_CDC_HOME

---

flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-full.yaml
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-with-optional.yaml
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/RouteDef.java

This pull request fixes keywords in route definitions, which should be "source-table" and "sink-table".
Please note that in `RouteDef` these two keywords are still "sourceTable" and "sinkTable", because they are Java object names. Only keywords in YAML need to be adjusted.

[cdc-cli][cdc-composer] Use "source-table" and "sink-table" as keywords of route

---

flink-cdc-cli/src/main/java/com/ververica/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-full.yaml
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-with-optional.yaml
flink-cdc-composer/src/main/java/com/ververica/cdc/composer/definition/RouteDef.java

Unchanged backport of #2823 on release-3.0

[BP-3.0][cdc-cli][cdc-composer] Use "source-table" and "sink-table" as keywords of route

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/com/ververica/cdc/connectors/starrocks/sink/StarRocksUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/com/ververical/cdc/connectors/starrocks/sink/CdcDataTypeTransformerTest.java

In CDC framework, the length of char/varchar type represents the number of characters, but in StarRocks it represent the length of bytes. When mapping CDC char/varchar to that of StarRocks, we should multiply 3 for the length because a UTF-8 chinese character will use 3 bytes

[pipeline-connector][starrocks] Fix char/varchar length inconsistency between cdc and starrocks

---

docs/content/overview/cdc-pipeline.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/pipeline-test.yaml

In https://github.com/ververica/flink-cdc-connectors/pull/2821, prefix of pipeline options is removed. Thus, prefix of pipeline options in overview docs also need to be removed

[docs] Fix overview docs to remove prefix of pipeline options.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java

In https://github.com/ververica/flink-cdc-connectors/pull/2156, debezium version is bump to 1.9.7.Final, including PostgresConnection. It's a good thing, however some comments of PostgresConnection to distinguish with debezium's origin class are removed. 
Two additional methods of our PostgresConnection is not included in 1.9.7.Final Debezium's PostgresConnection., so these comment should not be removed.
These comments are important for us for future to track the changes of Debezium's  PostgresConnection. If these two PostgresConnection become same, we will remove it from cdc. Without it, it hard for us to distinguish the changes we did.

[postgres] Add commits of PostgresConnection back to distinguish with debezium's origin class

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/MongoDBFullChangelogITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/MongoDBParallelSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/source/OracleSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/source/SqlServerSourceITCase.java

As shown in https://github.com/ververica/flink-cdc-connectors/issues/2853, SqlServer incremental source cannot support exactly-once now. 
Between the time that a change is committed in the source table, and the time that the change appears in the corresponding change table, there is always a small latency interval.
Because the time is random, the test com.ververica.cdc.connectors.sqlserver.source.SqlServerSourceITCase#testEnableBackfillWithDMLPreHighWaterMark will sometime fail even sleep for 5 minute.
however, it's rather than tricky,  may not be fixed recently. In oder to not influence other PR's CI , before https://github.com/ververica/flink-cdc-connectors/issues/2853 is fixed,  fix UT errors by correcting right output which includes duplicate data.

[cdc-connector][sqlserver][tests] Fix UT errors by correcting right output

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseConnection.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseRichSourceFunction.java

Fix compatibility issue introduced by #2565

[cdc-source-connector][oceanbase] use current timestamp when query gts failure

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBStreamFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/MongoDBFullChangelogITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/com/ververica/cdc/connectors/mongodb/source/MongoDBParallelSourceITCase.java

Fix https://github.com/ververica/flink-cdc-connectors/issues/2892

[cdc-connector][mongodb] Avoid mongodb source to read data after high_watermark in backfill phase

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/types/utils/DataTypeUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisMetadataApplier.java

Fix a typo of 'unsupported' and fix the doris pipeline connector using wrong value for 'precision' of time type.
The length of time type or timestamp type always be null.
cc @lvyanquan

[cdc-common][pipeline-doris] Fix a typo and fix the doris pipeline connector.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisEventSerializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisRowConverter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/com/ververica/cdc/connectors/starrocks/sink/StarRocksUtils.java

this closes https://github.com/ververica/flink-cdc-connectors/issues/2953.
Test case is included in [EventRecordSerializationSchemaTest](https://github.com/ververica/flink-cdc-connectors/blob/7ab1e878425bb3d673cd8cfe175551fb90520d23/flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/com/ververical/cdc/connectors/starrocks/sink/EventRecordSerializationSchemaTest.java#L176)

[doris][starrocks] remove SimpleDateFormat usage in Doris/StarRock.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/com/ververica/cdc/connectors/starrocks/sink/StarRocksMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/com/ververica/cdc/connectors/starrocks/sink/StarRocksUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/com/ververical/cdc/connectors/starrocks/sink/CdcDataTypeTransformerTest.java

In the StarRocks, The primary key columns can be any of the following data types: BOOLEAN, TINYINT, SMALLINT, INT, BIGINT, LARGEINT, STRING, VARCHAR, DATE, and DATETIME, But it doesn't include CHAR.
When a char type appears in the primary key of MySQL, creating a table in StarRocks requires conversion to varchar type.

[bug][pipeline-connector][starrocks] Optimize char type mapping for starrocks pipeline connector

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlFullTypesITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlMetadataAccessorITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/ddl/column_type_test.sql
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/ddl/column_type_test_mysql8.sql
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/event/DebeziumSchemaDataTypeInference.java

[pipeline-connector][mysql] fix timestamp with timezone format

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/utils/InstantiationUtil.java

This closes https://github.com/ververica/flink-cdc-connectors/issues/2943.
It was verified using Flink 1.17.1, but e2e verification is still required.

[hotfix] Fix NoSuchMethodError of CollectionUtil.newHashMapWithExpectedSize.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/meta/split/SourceSplitSerializer.java

From 3rd version of stream split, use totalFinishedSplitSize. But with condition of `version == 3`, cannot 
get totalFinishedSplitSize from recovery deserialization in 4th version.
```java
// com.ververica.cdc.connectors.base.source.meta.split.SourceSplitSerializer#deserializeSplit
Map<TableId, TableChange> tableChangeMap = readTableSchemas(version, in);
int totalFinishedSplitSize = finishedSplitsInfo.size();
if (version == 3) {
totalFinishedSplitSize = in.readInt();
}
```
That means that divideMetaToGroups is invalid. A reader  receive and deserialize stream split, totalFinishedSplitSize is always equal to finishedSnapshotSplitInfos, which is a completed splt. See:
```java
// com.ververica.cdc.connectors.base.source.meta.split.StreamSplit#isCompletedSplit
public boolean …
```

[cdc-connector][cdc-base][hot-fix] Fix SourceSplitSerializer to get totalFinishedSplitSize from recovery in 4th version.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java

This closes https://github.com/ververica/flink-cdc-connectors/issues/2981.

[hotfix][cdc-connector][mysql] skip SchemaChangeEvents that were not included in capturedTableFilter.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/RecordUtils.java

Back port of https://github.com/ververica/flink-cdc-connectors/pull/2986 to release-3.0.

[BP-2986] skip SchemaChangeEvents that were not included in capturedTableFilter. 

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/reader/fetch/MongoDBStreamFetchTask.java

In current MongoDBStreamFetchTask, even MongoDBStreamFetchTask is closed, the executor is sitll running.Because nothing is done in MongoDBStreamFetchTask.close now.

[cdc-connector][mongodb][hotfix] Close stream fetcher task in MongoDBStreamFetchTask.close

---

flink-cdc-common/src/main/java/com/ververica/cdc/common/event/AddColumnEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DropColumnEvent.java
flink-cdc-common/src/main/java/com/ververica/cdc/common/utils/SchemaUtils.java
flink-cdc-common/src/test/java/com/ververica/cdc/common/testutils/assertions/DropColumnEventAssert.java
flink-cdc-common/src/test/java/com/ververica/cdc/common/utils/SchemaUtilsTest.java
flink-cdc-composer/src/test/java/com/ververica/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/com/ververica/cdc/connectors/doris/sink/DorisMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/com/ververica/cdc/connectors/mysql/source/parser/CustomAlterTableParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/com/ververica/cdc/connectors/starrocks/sink/StarRocksMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/com/ververical/cdc/connectors/starrocks/sink/EventRecordSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/com/ververical/cdc/connectors/starrocks/sink/StarRocksMetadataApplierTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/ValuesDatabase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/com/ververica/cdc/connectors/values/source/ValuesDataSourceHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/test/java/com/ververica/cdc/connectors/values/ValuesDatabaseTest.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/route/RouteFunction.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/serializer/event/DropColumnEventSerializer.java
flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/serializer/schema/ColumnWithPositionSerializer.java
flink-cdc-runtime/src/test/java/com/ververica/cdc/runtime/operators/route/RouteFunctionTest.java
flink-cdc-runtime/src/test/java/com/ververica/cdc/runtime/operators/schema/coordinator/SchemaManagerTest.java
flink-cdc-runtime/src/test/java/com/ververica/cdc/runtime/serializer/event/AddColumnEventSerializerTest.java
flink-cdc-runtime/src/test/java/com/ververica/cdc/runtime/serializer/event/DropColumnEventSerializerTest.java
flink-cdc-runtime/src/test/java/com/ververica/cdc/runtime/serializer/event/SchemaChangeEventSerializerTest.java
flink-cdc-runtime/src/test/java/com/ververica/cdc/runtime/serializer/schema/ColumnWithPositionSerializerTest.java

Refer to #2857.
Using the name of column, replace using column.
@lvyanquan

[cdc-common][cdc-pipelines][cdc-runtime] Use name instead of column in DropColumnEvent/AddColumnEvent.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresSourceFetchTaskContext.java

Fix https://github.com/ververica/flink-cdc-connectors/issues/2980. Now that PostgresSourceFetchTaskContext can only be contained by single thread now, it is no need to put into AtomicReference.

[cdc-connector][Postgres][hotfix] Fix postgresSQL database connection leak

---

docs/content/connectors/sqlserver-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/source/OracleSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/dialect/SqlServerChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerSourceFetchTaskContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/utils/SqlServerUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/source/SqlServerSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/com/ververica/cdc/connectors/sqlserver/table/SqlServerConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/resources/ddl/customer.sql

-  Fixes #2971 
sqlserver support use specific chunk column as a split key
* Modify SqlServerUtils#getSplitColumn by adding a `chunkKeyColumn` param
* Add doc about chunk column
* Add ITcase UT about using chunk coulmn

[cdc-connector][sqlserver] sqlserver support use specific chunk column as a split key

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/MongoUtils.java

This PR tried to fix issue #3008, which reports that mongo-cdc connector capturing multiple collections with `.scanFullChangelog` option would require every collection saving pre- and post-image records in that database, even for those excluded by RegEx.
Currently, [the entire database was watched](https://github.com/ververica/flink-cdc-connectors/blob/9abf2cf900e48df8ee314f10bac28589d77a3617/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/MongoUtils.java#L181) when an regex was provided to specify required collections. According to [MongoDB docs](https://www.mongodb.com/docs/manual/reference/method/db.watch/), `pipeline` only performs filtering in the final output side, so pre-image and post-image …

[fix][cdc-connector][mongo] Fix scanFullChangelog requires all collections (#3008)

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/EventProcessorFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/OracleScanFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/OracleStreamFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/reader/fetch/StoppableChangeEventSourceContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/table/OracleTableSourceFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/source/OracleSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleTableSourceFactoryTest.java

As shown in https://github.com/ververica/flink-cdc-connectors/issues/2867, expose SNAPSHOT_ONLY mode for Oracle CDC Source  after until https://github.com/ververica/flink-cdc-connectors/issues/2909 is fixed.

[cdc-connector][oracle] Expose SNAPSHOT_ONLY mode for Oracle CDC Source

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/source/utils/OracleConnectionUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/com/ververica/cdc/connectors/oracle/table/OracleTableSourceFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/com/ververica/cdc/connectors/oracle/table/OracleTableSourceFactoryTest.java

- Fixes #2087  
If the database name configured for Oracle CDC in Flink SQL is lowercase, such as the following example (`'database-name' = 'xe'`), 
```sql
CREATE TABLE products (
ID INT NOT NULL,
NAME STRING,
DESCRIPTION STRING,
WEIGHT DECIMAL(10, 3),
PRIMARY KEY(id) NOT ENFORCED
) WITH (
'connector' = 'oracle-cdc',
'hostname' = 'localhost',
'port' = '1521',
'username' = 'flinkuser',
'password' = 'flinkpw',
'database-name' = 'xe',
'schema-name' = 'FLINKUSER',
'table-name' = 'TEST_03');
```
the following problems will occur:
1. For the same table (`TEST_03`)，the snapshot phase  will use the lowercase database name  (`xe.FLINKUSER.TEST_03 `), and the incremental phase will use the uppercase database name (`XE.FLINKUSER.TEST_03 `).
2. For the same table (`TEST_03 `), after being captured in …

[Oracle] Fix Oracle CDC fetch two different db name for the same table

---

.idea/vcs.xml

Add IssueNavigationLink for IDEA git log

[FLINK-34577] Add IssueNavigationLink for IDEA git log

---

flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-mysql-cdc/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/MySqlE2eITCase.java

`flink-cdc-source-connectors` module is depended on `flink-cdc-common`, but `flink-sql-connector-mysql-cdc` is not included `flink-cdc-common` when packaging.

[hotfix][cdc][build] Include cdc-common module when shaded for module flink-sql-connector-mysql-cdc

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue-notice.yml

This pull request adds issue template that reminds users to use Apache Jira and mailing lists for reporting bugs and new features, and new issues will be ignored.

[FLINK-34180][cdc] Add issue template to remind users about the new bug and feature reporting way

---

docs/content/docs/get-started/introduction.md

This pull request adds introduction page for Flink CDC docs.

[FLINK-34678][cdc] Add introduction page for Flink CDC docs

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java

BinlogSplitReaderTest#readBinlogSplitsFromSnapshotSplits should test binlog reader is closed after binlog reader close. But code always test snapshot split reader is closed.
```java
binlogReader.close();
assertNotNull(snapshotSplitReader.getExecutorService());
assertTrue(snapshotSplitReader.getExecutorService().isTerminated());
```
We shoud change code to 
```java
binlogReader.close();
assertNotNull(binlogReader.getExecutorService());
assertTrue(binlogReader.getExecutorService().isTerminated());  
```

[FLINK-34715][cdc-connector][mysql] Fix mysql ut about closing BinlogSplitReader

---

docs/content/docs/core-concept/data-pipeline.md
docs/content/docs/core-concept/data-sink.md
docs/content/docs/core-concept/data-source.md
docs/content/docs/core-concept/route.md
docs/content/docs/core-concept/table-id.md
docs/content/docs/core-concept/transform.md

A follow up of https://github.com/apache/flink-cdc/pull/3146 to complete the docs.

[FLINK-34679][cdc] add doc under core-concept.

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/types/DataField.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/types/utils/DataTypeUtils.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/types/utils/DataTypeUtilsTest.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/utils/SchemaUtilsTest.java

Fix cdc `RowType` can not convert to flink type
I meet the follow exception:
```
java.lang.ArrayStoreException
at java.lang.System.arraycopy(Native Method)
at java.util.Arrays.copyOf(Arrays.java:3213)
at java.util.ArrayList.toArray(ArrayList.java:413)
at java.util.Collections$UnmodifiableCollection.toArray(Collections.java:1036)
```

[FLINK-34948][cdc-common] Fix cdc `RowType` can not convert to flink type

---

flink-cdc-cli/pom.xml
flink-cdc-common/pom.xml
flink-cdc-composer/pom.xml
flink-cdc-connect/pom.xml
flink-cdc-dist/pom.xml
flink-cdc-e2e-tests/pom.xml
flink-cdc-runtime/pom.xml
pom.xml

Update old `flink-cdc-connectors` artifactId to `flink-cdc`.

[FLINK-34959] Update old flink-cdc-connectors artifactId

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/factory/ValuesDataFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/sink/ValuesDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/sink/ValuesDataSinkFunction.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/sink/ValuesDataSinkOptions.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/sink/DataSinkFunctionOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/sink/DataSinkOperator.java

Though current Flink CDC pipeline define com.ververica.cdc.common.sink.FlinkSinkFunctionProvider to to provide a Flink SinkFunction for writing events to external systems. However, com.ververica.cdc.runtime.operators.sink.DataSinkWriterOperator don't support SouceFunction, which means sink implement SinkFunction cannot use CDC pipeline.
Why not support  SourceFunction in Flink CDC pipeline ?
Add An operator `DataSinkOperator` that processes records to be written into a {@link org.apache.flink.streaming.api.functions.sink.SinkFunction}.

[FLINK-34952][cdc-composer][sink] Flink CDC pipeline supports SinkFunction

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java

Event log  
`Caused by: com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException`
would occur as explained in issue #2217  whereby client is restarted during the consumption process, leading to a Rotate Event that clears the tableMapEventByTableId. 
This has been fixed in [DBZ](https://github.com/debezium/debezium/pull/4959) discussing the same issue. This PR tries to port that fix over since Flink CDC clones the MySqlStreamingChangeEventSource.

[MySQL] Fix for DBZ-7037 and 2217 to not clear tableMapEventByTableId for fake Rotates Event

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/CdcDataTypeTransformerTest.java

Flink only have bigint type, if mysql data is unsigned bigint , maybe out of range, so cast to DECIMAL(20, 0).
If starrocks supports unsigned bigint, maybe can transform DECIMAL(20, 0) to unsigned bigint in sink. To be honest, unsigned bigint is not in SQL standard, thus many databases maybe not support it. https://docs.starrocks.io/zh/docs/sql-reference/sql-statements/data-types/data-type-list/
And starrock not support DECIMAL as primary key, thus should be transformed to VARHCAR.
StarRocks is not support Decimal as primary key, so decimal should be cast to  VARHCAR.

[FLINK-34690] Cast decimal to VARCHAR as primary key in starrocks sink

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksUtils.java

Currently, there is no spotless violation in ` flink-cdc-pipeline-connectors `. When run `mvn spotless:apply ` locally , will throw Exception.

[hotfix] run mvn spotless to fix code style violations.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/resources/ddl/chunk_test.js

Currently, when running `MongoDBStreamSplitReaderTest` and `MongoDBSnapshotSplitReaderTest`, tons of warning messages were be printed:
```
Warning: NumberLong: specifying a number as argument is deprecated and may lead to loss of precision, pass a string instead
... (repeated lines)
```
The problem lies in `chunk_test.js:22`, where `NumberLong` was called with a plain number instead of string, which has been deprecated by MongoDB engine due to precision loss concerns, though here `i` would never be greater than `20480`.
Converting it to string before passing it to `NumberLong` should fix this problem.

[minor][cdc-connector][mongo] Fix warning during MongoDB tests

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/MySqlValidator.java

Implemented functino to check `binlog_row_value_optoins` within MySqlValidator.
When `binlog_row_value_optoins` is set to `PARTIAL_JSON`,  
the update operator remains as `Update_rows_partial`.
Flink CDC does not parse this event because `Update_row_partial` binlog event is mapped to `PARTIAL_UPDATE_ROWS_EVENT` and Flink CDC do not handle that event type. Therefore, some update query-related binary logs are lost.
So, we have to check `binlog_row_value_optoins` before starting.
```java
private final MySqlSourceConfig sourceConfig;
public void validate() {
checkVersion(connection);
checkBinlogFormat(connection);
checkBinlogRowImage(connection);
checkBinlogRowValueOptions(connection);
checkTimeZone(connection);
} catch (SQLException ex) {
throw new TableException(
}
}
/** Check whether the …
```

[FLINK-34689][MySQL][Feature] check  binlog_row_value_options

---

.github/workflows/flink_cdc.yml

[[FLINK-35078](https://issues.apache.org/jira/browse/FLINK-35078)]: Separately adds the Flink CDC pipeline connector modules to the CI build.

[FLINK-35078][pipeline-connectors][ci] Adds flink-cdc-pipeline-connectors to the GHA CI

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/offset/ChangeStreamOffset.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/reader/fetch/MongoDBStreamFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/utils/MongoUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/source/NewlyAddedTableITCase.java

Closes [FLINK-35079](https://issues.apache.org/jira/browse/FLINK-35079).
When MongoDB CDC connector tries to create cursor with an expired resuming token during stream task fetching stage, it will crash with a fatal exception: `error due to Command failed with error 280 (ChangeStreamFatalError): cannot resume stream; the resume token was not found.`
This PR added fallback logic to create cursor with timestamp, which only runs when:
* Mongo CDC is in StreamTaskFetch stage
* a `ChangeStreamFatalError` (280) is raised
* Current `ChangeStreamOffset` has a valid timestamp field
Also tweaked @loserwang1024 's test case to cover resume token expiration scenario better.

[FLINK-35079] Fallback to timestamp startup mode when resume token has expired

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSource.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSourceHelper.java

At present, CI testing often causes OOM due to ValuesSource, which may be caused by the use of HybridSource. Considering that this will block other prs, remove it first to restore CI.

[FLINK-35127] remove HybridSource to avoid CI failure.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/pom.xml

This closes [FLINK-35102](https://issues.apache.org/jira/browse/FLINK-35102).
According to Flink CDC Doris connector docs, CHAR and VARCHAR are mapped to 3-bytes since Doris uses UTF-8 variable-length encoding internally.
However, in current type mapping implementation (based on `flink-doris-connector:1.5.0`), it was implemented differently, mapping `CHAR(n)` to `CHAR(n)`, and `VARCHAR(n)` to `VARCHAR(n * 4)`.
```java
public String visit(CharType charType) {
return String.format("%s(%s)", "CHAR", charType.getLength());
}
public String visit(VarCharType varCharType) {
long length = (long)varCharType.getLength();
return length * 4L >= 65533L ? "STRING" : String.format("%s(%s)", "VARCHAR", length * 4L);
}
```
In latest 1.6.0 version, this issue was fixed and are types correctly mapped. …

[FLINK-35102][doris] Fix Doris connector type mapping issues

---

docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

StarRocks refactored its all-in-one docker image in [this PR](https://github.com/StarRocks/starrocks/pull/28240/), which adds a `feproxy` layer exposing 8080 as the unified FE http service port. The previous quickstar guide is outdated since the container doesn't expose port 8030 and connection attempt would fail.
This PR:
* uses fixed docker image tag to make the process reproducible
* changed exposed port & `load-url` to follow latest StarRocks image
* fixed `docker-compose exec` command case-insensitive issue
Local tests have been done to ensure the guide feasible.

[minor][cdc][docs] Fix outdated StarRocks quickstart guide

---

.github/workflows/flink_cdc.yml
docs/content.zh/docs/connectors/kafka.md
docs/content/docs/connectors/kafka.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/ChangeLogJsonFormatFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/JsonSerializationType.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfo.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/PipelineKafkaRecordSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/resources/META-INF/services/org.apache.flink.cdc.common.factories.Factory
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/MockInitializationContext.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfoTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkFactoryTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaUtil.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/resources/log4j2-test.properties
flink-cdc-connect/flink-cdc-pipeline-connectors/pom.xml

This closes https://github.com/ververica/flink-cdc-connectors/issues/2691.
* support value format of `debeium-json` and `canal-json`.
* The written topic of Kafka will be `namespace.schemaName.tableName` string of TableId，this can be changed using `route` function of pipeline.
* If the written topic of Kafka is not existed, we will create one automatically.

[pipeline-connector][kafka] add kafka pipeline data sink connector.

---

docs/content.zh/docs/connectors/legacy-flink-cdc-sources/db2-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/oceanbase-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/oracle-cdc.md
docs/content.zh/docs/connectors/mysql.md
docs/content/docs/connectors/legacy-flink-cdc-sources/db2-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/oceanbase-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/oracle-cdc.md
docs/content/docs/connectors/mysql.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-db2-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-mysql-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-oceanbase-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-oracle-cdc/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/Db2E2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/MySqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/OracleE2eITCase.java

This resolves [FLINK-35055](https://issues.apache.org/jira/browse/FLINK-35055).
Currently, Flink CDC connector releases both slim and fat jars. Apart from CDC itself, all of its dependencies are packaged into fat jars, including some with incompatible licenses:
* Db2 connector: `com.ibm.db2.jcc:db2jcc:db2jcc4` licensed under IBM's non-FOSS license (International Program License Agreement).
* MySQL connector: `mysql:mysql-connector-java` licensed under GPLv2 license, which is incompatible with Apache 2.0.
* OceanBase connector: `mysql:mysql-connector-java` licensed under GPLv2 license, which is incompatible with Apache 2.0.
* Oracle connector: `com.oracle.ojdbc` licensed under Oracle's non-FOSS license (Oracle Free Use Terms and Conditions).
This PR:
1. Excludes questionable dependencies …

[FLINK-35055][cdc] Exclude connector dependencies with questionable licenses from fat jar packages

---

flink-cdc-e2e-tests/flink-cdc-e2e-utils/pom.xml
flink-cdc-e2e-tests/flink-cdc-e2e-utils/src/test/java/org/apache/flink/cdc/common/test/utils/JdbcProxy.java
flink-cdc-e2e-tests/flink-cdc-e2e-utils/src/test/java/org/apache/flink/cdc/common/test/utils/ParameterProperty.java
flink-cdc-e2e-tests/flink-cdc-e2e-utils/src/test/java/org/apache/flink/cdc/common/test/utils/TestUtils.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestEnvironment.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/ddl/mysql_inventory.sql
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/docker/mysql/my.cnf
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/docker/mysql/setup.sql
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/log4j2-test.properties
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/Db2E2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/MongoE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/MySqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/OceanBaseE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/OracleE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/PostgresE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/SqlServerE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/TiDBE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/VitessE2eITCase.java
flink-cdc-e2e-tests/pom.xml

This closes https://github.com/ververica/flink-cdc-connectors/issues/2859.
Add e2e test for two scenes: sync the whole database and sync sharding tables using route function.
To simplify the complexity of different source/sink combinations, I plan to use MySQL as the source for all sinks and Doris as the sink for all sources.
Include two latest major version of Flink, 1.17.1 & 1.18.0.

[e2e] add pipeline e2e test for mysql connector.

---

docs/content.zh/docs/connectors/legacy-flink-cdc-sources/db2-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/oceanbase-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/oracle-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/postgres-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/sqlserver-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/tidb-cdc.md
docs/content.zh/docs/connectors/legacy-flink-cdc-sources/vitess-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/db2-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/mongodb-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/mysql-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/oceanbase-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/oracle-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/postgres-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/sqlserver-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/tidb-cdc.md
docs/content/docs/connectors/legacy-flink-cdc-sources/vitess-cdc.md

This PR update docs by using the download link of the release version instead of a snapshot version.

[hotfix][docs] Use the download link of the release version instead of a snapshot version

---

docs/content.zh/docs/connectors/mysql.md
docs/content/docs/connectors/mysql.md
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/utils/ConfigurationUtils.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/utils/FlinkEnvironmentUtils.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/utils/YamlParserUtils.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/utils/ConfigurationUtilsTest.java
flink-cdc-cli/src/test/resources/flink-home/conf/flink-conf.yaml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestEnvironment.java

This PR fixes pipeline e2e test case failures.
* Allowing legacy Flink YAML parser to accept duplicate keys to avoid conflicts between `flink-conf.yaml` and `FLINK_PROPERTIES` env
* Appending missing `mysql-driver.jar` as it has been excluded from CDC fat jar package

[hotfix][e2e] Fix pipeline e2e test cases failures

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/meta/split/StreamSplit.java

In mysql cdc, re-calculate the starting binlog offset after the new table added in MySqlBinlogSplit#appendFinishedSplitInfos, while there lack of same action in StreamSplit#appendFinishedSplitInfos. This will cause data loss if any newly added table snapshot split's high_watermark is smaller.
Some unstable test problem occurs because of it.

[FLINK-35128][cdc-connector][cdc-base] Re-calculate the starting changelog offset after the new table added

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/meta/split/StreamSplit.java

[BP-3.1][FLINK-35128][cdc-connector][cdc-base] Re-calculate the starting changelog offset after the new table added (#3230) 

---

docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md
docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

Since `mysql-connector-java` has been excluded from released jar packages, pipeline users must provide it explicitly. Updated quickstart guides to clarify this.

[BP-3.1][minor][cdc][docs] Add user guide about providing extra jar package in quickstart docs

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/org/apache/flink/cdc/debezium/utils/ConvertTimeBceUtil.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/converters/MysqlDebeziumTimeConverter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/converters/MysqlDebeziumTimeConverterITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/ddl/date_convert_test.sql

BP [FLINK-35173](https://issues.apache.org/jira/browse/FLINK-35173) to release 3.1.
(cherry picked from commit 6232d84052422aa88299f28074a8437e91db2988)

[BP3.1][FLINK-35173][cdc][mysql] Debezium custom time serializer for MySQL connector (#3240)

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/pom.xml

cherry pick of https://github.com/apache/flink-cdc/pull/3262.

[BP-3.1][FLINK-35235][pipeline-connector][kafka] Fix missing dependencies in the uber jar of Kafka pipeline sink.

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivation.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivationTest.java

This PR fixes bug of serializing derivation mapping in SchemaDerivation that mistakenly uses `out.write` instead of `out.writeInt` when serializing the size of the mapping, and also add a test case for validating serde of SchemaDerivation.

[FLINK-35251][cdc][runtime] Fix bug of serializing derivation mapping in SchemaDerivation

---

docs/content.zh/docs/connectors/doris.md
docs/content/docs/connectors/doris.md

[FLINK-35258][cdc][doc] Fix broken links to Doris in documentation

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformSchemaOperatorTest.java

This closes [FLINK-35256](https://issues.apache.org/jira/browse/FLINK-35256).
Flink CDC 3.1.0 brought transform feature, allowing column type / value transformation prior to data routing process. However after the transformation, column type marked as `NOT NULL` lost their annotation, causing some downstream sinks to fail since they require primary key to be NOT NULL.
Here's the minimum reproducible example about this problem:
```yaml
source:
type: mysql
...
sink:
type: starrocks
name: StarRocks Sink
...
pipeline:
name: Sync MySQL Database to StarRocks
parallelism: 4
transform:
source-table: reicigo.\.*
projection: ID, UPPER(ID) AS UPID
```
MySQL source table schema definition is as follows:
```
CREATE TABLE table1 (
ID VARCHAR(17) NOT NULL,
...
PRIMARY KEY (ID)
);
```
The underlying …

[FLINK-35256][runtime] Fix transform node does not respect type nullability

---

docs/content.zh/docs/core-concept/route.md
docs/content/docs/core-concept/route.md

This PR fixes `route` definition YAML example in Flink CDC core concept documentations.

[minor][docs] Fix route definition example in core concept docs

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformDataOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This closes FLINK-34878.
This PR adds conditional functions for flink cdc transform operator.

[FLINK-34878][cdc] Flink CDC pipeline transform supports CASE WHEN

---

docs/content.zh/docs/core-concept/route.md
docs/content/docs/core-concept/route.md

This PR fixes `route` definition YAML example in Flink CDC core concept documentations.

[BP-3.1][minor][docs] Fix route definition example in core concept docs

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/sink/DataSinkWriterOperator.java

… for the snapshotState and processWatermark methods

[BP-3.1][FLINK-35255] DataSinkWriterOperator should override snapshotState and processWatermark method

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/ddl/mysql_inventory.sql
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/ddl/transform_test.sql
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformSchemaOperator.java

[FLINK-35264][runtime] Fix multiple transform rules do not take effect

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/test/java/org/apache/flink/cdc/connectors/tidb/TiDBTestBase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/test/java/org/apache/flink/cdc/connectors/tidb/table/TiDBConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/test/java/org/apache/flink/cdc/connectors/tidb/table/TiDBConnectorRegionITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/test/java/org/apache/flink/cdc/connectors/tidb/table/TiDBTableSourceFactoryTest.java

see https://issues.apache.org/jira/browse/FLINK-35244
test case for flink-connector-tidb-cdc should under
`org.apache.flink.cdc.connectors.tidb` package
instead of `org.apache.flink.cdc.connectors`

[FLINK-35244][cdc-connector][tidb] Move package for flink-connector-tidb-cdc test

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/main/java/org/apache/flink/cdc/connectors/tidb/TiKVRichParallelSourceFunction.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/main/java/org/apache/flink/cdc/connectors/tidb/metrics/TiDBSourceMetrics.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/src/test/java/org/apache/flink/cdc/connectors/tidb/metrics/TiDBSourceMetricsTest.java

https://issues.apache.org/jira/browse/FLINK-35245
add metrcis: currentFetchEventTimeLag, currentEmitEventTimeLag, sourceIdleTime for TiKVRichParallelSourceFunction

[FLINK-35245][cdc-connector][tidb] Add metrics for flink-connector-tidb-cdc

---

docs/content.zh/docs/core-concept/transform.md
docs/content/docs/core-concept/transform.md

This closes [FLINK-35314](https://issues.apache.org/jira/browse/FLINK-35314).

[FLINK-35314][cdc] Add Flink CDC pipeline transform user document

---

.github/workflows/build_docs.yml

Changes:
-  Enable build check for pr
- Add `release 3.1` doc

[FLINK-35386][cdc][docs] Build release-3.1 documentation and mark it as stable

---

docs/content.zh/docs/faq/faq.md
docs/content/docs/faq/faq.md

Supplementary answer to the [Mysql CDC Q15] question

[hotfix][cdc][docs] Supplementary answer to the Mysql CDC Q15 question

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/metrics/SourceReaderMetrics.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/reader/IncrementalSourceRecordEmitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/metrics/MySqlSourceReaderMetrics.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlRecordEmitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceTestBase.java

- In snapshot phase, set -1 as the value of `currentFetchEventTimeLag` metric.
- Support `currentEmitEventTimeLag` metric.

[FLINK-35298][cdc] improve fetch delay metric reporter logic

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/task/MySqlBinlogSplitReadTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java

Since MySQL does not support the ability to quickly locate an binlog offset through a timestamp, the current logic for starting from a timestamp is to begin from the earliest binlog offset and then filter out the data before the user-specified position.
If the user restarts the job during the filtering process, this filter will become ineffective.
Use source config to check if the filter should be applied in timestamp starting mode.

[FLINK-35294][mysql] Use source config to check if the filter should be applied in timestamp starting mode

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/relational/connection/JdbcConnectionPoolFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java

In JDK 8 and earlier version, if multiple threads invoke `Class.forName("com.xx.Driver")` simultaneously, it may cause jdbc driver deadlock.
[FLINK-19435](https://issues.apache.org/jira/browse/FLINK-19435)  analyzes this problem.

[FLINK-35301][cdc] fix deadlock when loading driver classes

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/MySqlValidator.java

Now, MySQL CDC connector will retrieve the offset seconds between the configured timezone and UTC by executing the SQL statement below, and then compare it with the configured timezone.
```SQL
SELECT TIME_TO_SEC(TIMEDIFF(NOW(), UTC_TIMESTAMP())) 
```
For some MySQL instances, the validating for time-zone is too strict. We can add 30min tolerance value.

[FLINK-35408][cdc][mysql] Add 30 min tolerance value when validating the time-zone setting

---

.github/workflows/build_docs.yml

Solution:
Deletes files from the destination directory that are not present in the source directory.

[FLINK-35447][doc-ci] Flink CDC Document document file had removed but website can access

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java

The issue is described in [FLINK-35409](https://issues.apache.org/jira/browse/FLINK-35409).

[FLINK-35409][cdc][mysql] Request more splits if all splits are filtered from addSplits method

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformDataOperator.java

This closes [FLINK-35323](https://issues.apache.org/jira/browse/FLINK-35323).
Currently, Transform module doesn’t support handling multiple tables with different schema within one projection / filtering rule. A minimum reproducible example is:
```yaml
transform:
- source-table: DB.TABLE\.*
projection: \*
```
If there are `DB.TABLE1` and `DB.TABLE2` in upstream source but with different schema, transform operator will panic. This is not intended and turns out to be related to incorrectly handled processor caching strategy. Fixing the cache key should resolve this problem.

[FLINK-35323][runtime] Fix transform failure when one rule matches multiple tables with incompatible schema

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformDataOperator.java

This closes FLINK-35323.
Currently, Transform module doesn’t support handling multiple tables with different schema within one projection / filtering rule. This is not intended and turns out to be related to incorrectly handled processor caching strategy. Fixing the cache key should resolve this problem.

[BP-3.1][FLINK-35323][runtime] Fix transform failure when one rule matches multiple schemas

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/MySqlValidator.java

[BP-3.1][FLINK-35408][mysql] Introduce 30 minutes tolerance when validating time-zone setting

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/ChangeLogJsonFormatFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchemaTest.java

Refer to [FLINK-35430](https://issues.apache.org/jira/browse/FLINK-35430)
Passed the zoneId to JsonSerializationSchema.

[FLINK-35430][cdc-connector][kafka] Passed the zoneId to JsonSerializationSchema.

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslatorTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksUtils.java

Current , when sink is not instanceof TwoPhaseCommittingSink, use input.transform rather than stream. It means that pre-write topology will be ignored.
```
private void sinkTo(
DataStream<Event> input,
Sink<Event> sink,
String sinkName,
OperatorID schemaOperatorID) {
DataStream<Event> stream = input;
// Pre write topology
if (sink instanceof WithPreWriteTopology) {
stream = ((WithPreWriteTopology<Event>) sink).addPreWriteTopology(stream);
}
if (sink instanceof TwoPhaseCommittingSink) {
addCommittingTopology(sink, stream, sinkName, schemaOperatorID);
} else {
input.transform(
SINK_WRITER_PREFIX + sinkName,
CommittableMessageTypeInfo.noOutput(),
new DataSinkWriterOperatorFactory<>(sink, schemaOperatorID));
}
} 
```
（ps: the modify of StarRocksUtils just apply spotless)

[FLINK-35149][cdc-composer] Fix DataSinkTranslator#sinkTo ignoring pre-write topology if not TwoPhaseCommittingSink

---

docs/content/docs/connectors/flink-sources/postgres-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceBuilder.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/config/PostgresSourceConfig.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/config/PostgresSourceConfigFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/config/PostgresSourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/reader/PostgresSourceReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLTableFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/PostgresTestBase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/reader/PostgresSourceReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/table/MockPostgreSQLTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java

https://issues.apache.org/jira/browse/FLINK-35129
- Adds option for checkpoint cycle parameter
- Commits PG offsets on every multiple of checkpoint cycle
- Updates docs with new parameter definition
- Adds unit & integration tests to cover new functionality

[FLINK-35129][cdc][postgres] Add checkpoint cycle option for commit offsets

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/event/AddColumnEvent.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/SchemaChangeProvider.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java

Refer to jira: https://issues.apache.org/jira/browse/FLINK-35325
Adding support for specifying column order when adding new columns to a table.

[FLINK-35325][cdc-connector][paimon]Support for specifying column order.

---

.github/ISSUE_TEMPLATE/issue-notice.yml
README.md

Improve the readme and issue template

[docs] Improve the readme and issue template

---

docs/content.zh/docs/connectors/flink-sources/db2-cdc.md
docs/content.zh/docs/connectors/flink-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/flink-sources/oceanbase-cdc.md
docs/content.zh/docs/connectors/flink-sources/oracle-cdc.md
docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md
docs/content.zh/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content.zh/docs/connectors/flink-sources/tidb-cdc.md
docs/content.zh/docs/connectors/flink-sources/tutorials/build-real-time-data-lake-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/build-streaming-etl-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/mongodb-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/oceanbase-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/oracle-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/polardbx-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/sqlserver-tutorial.md
docs/content.zh/docs/connectors/flink-sources/tutorials/tidb-tutorial.md
docs/content.zh/docs/connectors/flink-sources/vitess-cdc.md
docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md
docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/connectors/flink-sources/db2-cdc.md
docs/content/docs/connectors/flink-sources/mongodb-cdc.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/flink-sources/oceanbase-cdc.md
docs/content/docs/connectors/flink-sources/oracle-cdc.md
docs/content/docs/connectors/flink-sources/postgres-cdc.md
docs/content/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content/docs/connectors/flink-sources/tidb-cdc.md
docs/content/docs/connectors/flink-sources/vitess-cdc.md
docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

This PR:
* Adds guide to provide excluded DB drivers in quickstart docs
* Updates outdated maven jar links & move to `org.apache.flink` group ID

[FLINK-35527][docs] Polish quickstart guide & migrate maven links from ververica to apache

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSink.java

Because WithPreCommitTopology has extended TwoPhaseCommittingSink, there is no need to implement the TwoPhaseCommittingSink interface separately.

[minor][paimon] Remove duplicates implements.

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslator.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/utils/DorisContainer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/utils/DorisSinkTestBase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/resources/log4j2-test.properties
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/com/starrocks/shade/org/apache/commons/compress/utils/Lists.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/utils/StarRocksContainer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/utils/StarRocksSinkTestBase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MySqlToDorisE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestEnvironment.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
pom.xml

This closes FLINK-35092, FLINK-35120, FLINK-35316, FLINK-35415.
* Adds E2e testcases on recent Flink versions including 1.19
* Fixes CDC compatibility issue with 1.19 (due to breaking changes in @Internal classes)
This is a temporary workaround to avoid breaking compatibility with Flink 1.19. Proposal about upgrading Flink base (FLINK-35385) could be implemented later.

[FLINK-35415][base] Fix compatibility with Flink 1.19

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslatorTest.java

BP https://issues.apache.org/jira/browse/FLINK-35149 to 3.1.1

 [BP-3.1.1][FLINK-35149][cdc-composer] Fix DataSinkTranslator#sinkTo ignoring pre-write topology if not TwoPhaseCommittingSink (#3233)

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerTest.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslatorTest.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/translator/DataSourceTranslatorTest.java

As shown in https://github.com/apache/flink-cdc/pull/3387, adjust test of cdc composer from junit4 to junit5.

[hotfix][cdc-composor] adjust test of cdc composer from junit4 to junit5

---

.github/workflows/flink_cdc.yml

Flink cdc ci `compile_and_test` miss pipeline connector paimon.
And test ci https://github.com/beryllw/flink-cdc/actions/runs/9183968055

[hotfix][ci] CI `compile_and_test` add pipeline connector paimon

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/schema/Selectors.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/Predicates.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/schema/SelectorsTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceFactoryTest.java

https://issues.apache.org/jira/browse/FLINK-35540

[FLINK-35540][cdc-common][cdc-connector][mysql] fix lost table when database and table are with the same name

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/schema/Selectors.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/Predicates.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/schema/SelectorsTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceFactoryTest.java

https://issues.apache.org/jira/browse/FLINK-35540

[FLINK-35540][cdc-common] Fix table missed when database and table are with the same name in release-3.1.1

---

docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/pipeline-connectors/mysql.md
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/CliFrontendTest.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-full.yaml
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-minimized.yaml
flink-cdc-cli/src/test/resources/global-config/global-config.yaml
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/configuration/Configuration.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/factories/FactoryHelper.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/factories/FactoryHelperTests.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/definition/PipelineDef.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/definition/PipelineValidationTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/org/apache/flink/cdc/connectors/doris/factory/DorisDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkFactoryTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceFactoryTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonDataSinkOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonDataSinkFactoryTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSinkFactoryTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/factory/ValuesDataFactory.java

This closes FLINK-35121.
Currently, there's no explicit validations for any option in YAML pipeline definitions, though it's defined in `Factory#requiredOptions` and `Factory#optionalOptions`. This PR enforces checking any missing required options and redundantly provided unknown options.
---
My concern: I've noticed quite a few discrepancies about required/optional options in code logic, Factory definition, and online docs. For example, some explicitly accessed options aren't declared in Factory interface (which has been fixed as much as I can), and some supported options aren't present in documentations (like Kafka connector's `sink.delivery-guarantee`). That makes this change not backwards compatible if user relies such non-standard behavior. Needs more discussions to decide whether …

[FLINK-35121][common] Adds validation for pipeline definition options

---

docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/pipeline-connectors/mysql.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/config/MySqlSourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTableSourceFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java

The value of option `connector.timeout` needs to be checked at compile time.

[FLINK-35297][mysql] Add validation for option connect.timeout

---

.github/labeler.yml

Flink CDC 3.1 adds two new pipeline connectors (Kafka & Paimon). Added them into auto-labeler to tag PRs more precisely.

[hotfix][ci] Add new pipeline connectors into `labeler.yml`

---

docs/assets/_custom.scss
docs/content.zh/_index.md
docs/content/_index.md

cherry-pick #3208 and #3420 from master

[docs][minor] Optimize styles of the Flink CDC index page

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkEnvironmentUtils.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkEnvironmentUtilsTest.java

Current org.apache.flink.cdc.composer.flink.FlinkEnvironmentUtils#addJar will be invoked for each source and sink.
```java
public static void addJar(StreamExecutionEnvironment env, URL jarUrl) {
try {
Class<StreamExecutionEnvironment> envClass = StreamExecutionEnvironment.class;
Field field = envClass.getDeclaredField("configuration");
field.setAccessible(true);
Configuration configuration = ((Configuration) field.get(env));
List<String> jars =
configuration.getOptional(PipelineOptions.JARS).orElse(new ArrayList<>());
jars.add(jarUrl.toString());
configuration.set(PipelineOptions.JARS, jars);
} catch (Exception e) {
throw new RuntimeException("Failed to add JAR to Flink execution environment", e);
} 
```
if multiple source or sink share same jar, the par path will be added repeatly. For …

[FLINK-35281][hotfix][cdc-common] FlinkEnvironmentUtils#addJar add each jar only once

---

docs/content.zh/docs/core-concept/route.md
docs/content/docs/core-concept/route.md
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-full-with-repsym.yaml
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/route/RouteRule.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/definition/RouteDef.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/SchemaOperatorTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/RouteE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperatorFactory.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivation.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistry.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryProvider.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivationTest.java

This closes FLINK-35647, inspired by #2908 and #2947. Credit goes to @icchux and @WholeWorld-Timothy.
---
Currently, we must provide explicit sink-table in pipeline route rules, which means if we'd like to route all tables in specific database and change names in pattern, there's no choice but write all rules separately, which is a chore.
This PR allows specifying a special "replacement symbol" to resemble original table name in route rules like this:
```yaml
route:
- source-table: db.\.*
sink-table: new_db.<>
replace-symbol: <>
```
Now, `<>` will be replaced by upstream table name, so any tables like `db.tableX` will be routed to `new_db.tableX` automatically.

[FLINK-35647][route] Allow symbol replacement to simplify routing rules

---

docs/content.zh/docs/core-concept/data-pipeline.md
docs/content/docs/core-concept/data-pipeline.md
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/pipeline/PipelineOptions.java

This closes FLINK-35781.
Currently, Flink CDC `PIPELINE_PARALLELISM` option is forcefully required in pipeline definition, which turns out to be unnecessary since Flink already has a fallback parallelism option.
This PR adds a default value (1, same as Flink's default parallelism) in CDC CLI to resolve this issue.

[FLINK-35781][cli] Provide a default parallelism (1) for pipeline jobs

---

docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md

[minor][cdc][docs] Optimize markdown formats in doris quickstart doc

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/converters/MysqlDebeziumTimeConverter.java

Code optimization extracts constants

[cdc][mysql]Code optimization extracts constants

---

docs/content.zh/docs/get-started/quickstart/mysql-to-doris.md
docs/content.zh/docs/get-started/quickstart/mysql-to-starrocks.md
docs/content/docs/get-started/quickstart/mysql-to-doris.md
docs/content/docs/get-started/quickstart/mysql-to-starrocks.md

**请注意这里的lib指的是flink-cdc的lib，而不是flink的lib，pipeline相关的包不要放到flink的lib下，否则会引发类加载相关问题**
**Please note that you need to move the jar to the lib directory of Flink CDC Home, not to the lib directory of Flink Home.**

add note    **请注意这里的lib指的是flink-cdc的lib，而不是flink的lib，pipeline相关的包不要放到flink的lib下，否则会引发类加载相关问题**

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/utils/OracleSchema.java

OracleSchema getTableSchema Description Changed from `mysql` to`oracle`

[minor][cdc-connector][oracle] OracleSchema getTableSchema Description Modified

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java

This closes [FLINK-35874]
Optimize and avoid frequent invocations of getBinlogPosition by moving the check pureBinlogPhaseTables.contains(tableId) in the hasEnterPureBinlogPhase method before calling getBinlogPosition. This way, if the SourceRecord belongs to a pure binlog phase table, we can directly return true without the need for the highly performance-consuming getBinlogPosition method.

[FLINK-35874][cdc-connector][mysql] Check pureBinlogPhaseTables set before call getBinlogPosition method

---

docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/options/JdbcSourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/config/MySqlSourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/utils/ChunkUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/utils/RecordUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java

Allow column as chunk key even if it is not in the primary keys.
There are cases where the primary key is not a numeric type, such as varchar or varbinary.
In this case, the `distributed factor` and `chunk range` may be calculated incorrectly, resulting in one chunk containing too many records.
But there was no conditions for restrict column type of primary keys or input chunk key, so this may cause out of memory in the flink task manager.
Actually, in our company, there was a mysql tables that PK is a varbinary column and the above situation occurred.
[https://issues.apache.org/jira/browse/FLINK-35740](https://issues.apache.org/jira/browse/FLINK-35740)

[FLINK-35740][mysql] Allow column as chunk key even if not in Primary Keys

---

flink-cdc-migration-tests/flink-cdc-migration-testcases/pom.xml
flink-cdc-migration-tests/flink-cdc-migration-testcases/src/test/java/org/apache/flink/cdc/migration/tests/MigrationTestBase.java
flink-cdc-migration-tests/flink-cdc-release-3.1.1/pom.xml
flink-cdc-migration-tests/flink-cdc-release-3.1.1/src/main/java/org/apache/flink/cdc/migration/tests/MigrationMockBase.java
flink-cdc-migration-tests/flink-cdc-release-3.1.1/src/main/java/org/apache/flink/cdc/migration/tests/SchemaManagerMigrationMock.java
flink-cdc-migration-tests/flink-cdc-release-3.1.1/src/main/java/org/apache/flink/cdc/migration/tests/SchemaRegistryMigrationMock.java
flink-cdc-migration-tests/flink-cdc-release-3.1.1/src/main/java/org/apache/flink/cdc/migration/tests/TableChangeInfoMigrationMock.java
flink-cdc-migration-tests/pom.xml

Flink CDC 3.1.1 has been released in public. Migration tests could be added to ensure its compatibility with any future versions.

[hotfix][test] Add CDC 3.1.1 release to migration test versions

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java
pom.xml

fix [FLINK-35391](https://issues.apache.org/jira/browse/FLINK-35391)

[FLINK-35391][cdc-connector][paimon] Bump dependency of Paimon Pipeline connector to 0.8.0

---

.github/workflows/flink_cdc.yml
tools/mig-test/.gitignore
tools/mig-test/README.md
tools/mig-test/conf/docker-compose.yml
tools/mig-test/conf/pipeline-route.yaml
tools/mig-test/conf/pipeline.yaml
tools/mig-test/datastream/README.md
tools/mig-test/datastream/compile_jobs.rb
tools/mig-test/datastream/datastream-2.4.2/.gitignore
tools/mig-test/datastream/datastream-2.4.2/pom.xml
tools/mig-test/datastream/datastream-2.4.2/src/main/java/DataStreamJob.java
tools/mig-test/datastream/datastream-3.0.0/.gitignore
tools/mig-test/datastream/datastream-3.0.0/pom.xml
tools/mig-test/datastream/datastream-3.0.0/src/main/java/DataStreamJob.java
tools/mig-test/datastream/datastream-3.0.1/.gitignore
tools/mig-test/datastream/datastream-3.0.1/pom.xml
tools/mig-test/datastream/datastream-3.0.1/src/main/java/DataStreamJob.java
tools/mig-test/datastream/datastream-3.1.0/.gitignore
tools/mig-test/datastream/datastream-3.1.0/pom.xml
tools/mig-test/datastream/datastream-3.1.0/src/main/java/DataStreamJob.java
tools/mig-test/datastream/datastream-3.1.1/.gitignore
tools/mig-test/datastream/datastream-3.1.1/pom.xml
tools/mig-test/datastream/datastream-3.1.1/src/main/java/DataStreamJob.java
tools/mig-test/datastream/datastream-3.2-SNAPSHOT/.gitignore
tools/mig-test/datastream/datastream-3.2-SNAPSHOT/pom.xml
tools/mig-test/datastream/datastream-3.2-SNAPSHOT/src/main/java/DataStreamJob.java
tools/mig-test/datastream/run_migration_test.rb
tools/mig-test/misc/patch_flink_conf.rb
tools/mig-test/prepare_libs.rb
tools/mig-test/run_migration_test.rb

This closes FLINK-35736.
Currently, Flink CDC migration tests are limited to per-class unit tests, and it might not cover all migration cases.
Previously I wrote an E2e migration script, thinking this could be useful for RC verification / automated tests. This PR also added it into CI workflows, but I'm not quite sure about it. I'll remove this from GitHub action rules if it's not suitable for CI.
@morazow PTAL

[FLINK-35736][tests] Add migration test scripts & CI workflows

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplierITCase.java

This closes FLINK-35072.
Thanks to @qg-lin's great work, doris-flink-connector 1.6.2 has implemented column type modification API, so Flink CDC could implement this ticket more easily.
~~Notice that this PR isn't ready for merge yet, since doris-flink-connector 1.6.2 artifact has not been released. Local compilation & tests are required to verify this change for now.~~

[FLINK-35072][doris] Support applying AlterColumnTypeEvent to Doris sink

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/serializer/data/writer/AbstractBinaryWriter.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformDataOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This closes [FLINK-34877](https://issues.apache.org/jira/browse/FLINK-34877).

[FLINK-34877][cdc] Flink CDC pipeline transform supports type conversion

---

.github/workflows/flink_cdc.yml

As mentioned in https://github.com/actions/runner-images/issues/9557, https://github.com/actions/runner-images/issues/9692, GHA has deprecated Docker Compose V1 (`docker-compose` command), which will be removed soon. We should migrate to Docker Compose V2 (`docker compose`) before it got removed from runner images.

[hotfix][ci] Migrate to Docker Compose V2

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/splitter/JdbcSourceChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/utils/JdbcChunkUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/test/java/org/apache/flink/cdc/connectors/base/experimental/MySqlChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/test/java/org/apache/flink/cdc/connectors/base/experimental/utils/MySqlUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/dialect/Db2ChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/utils/Db2Utils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/assigner/splitter/OracleChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/utils/OracleUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/utils/PostgresQueryUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/dialect/SqlServerChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/utils/SqlServerUtils.java

Current, subclasses of JdbcSourceChunkSplitter almost share same code, but each have one copy. It's hard for later maintenance. 
Thus, this Jira aim to move same code from multiple subclasses to JdbcSourceChunkSplitter, just like what have done in 
AbstractScanFetchTask(https://github.com/apache/flink-cdc/issues/2690)

[FLINK-35344][cdc-base] Move same code from multiple subclasses to JdbcSourceChunkSplitter

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/dialect/DataSourceDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/dialect/JdbcDataSourceDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/relational/connection/JdbcConnectionPools.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/HybridSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/SnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/SplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/StreamSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/enumerator/IncrementalSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlBinlogSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/connection/JdbcConnectionPools.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlBinlogSplitAssignerTest.java

Current, inJdbcConnectionPools is static instance, so the datasource pools in it won't be recycle when reader close. It will cause memory leak.
```java
public class JdbcConnectionPools implements ConnectionPools<HikariDataSource, JdbcSourceConfig> {
private static final Logger LOG = LoggerFactory.getLogger(JdbcConnectionPools.class);
private static JdbcConnectionPools instance;
private final Map<ConnectionPoolId, HikariDataSource> pools = new HashMap<>();
private static final Map<String, JdbcConnectionPoolFactory> POOL_FACTORY_MAP = new HashMap<>();
```

[FLINK-35524][cdc-base] Clear connections pools when reader exist.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/DebeziumUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/task/context/StatefulTaskContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/offset/BinlogOffsetUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/SpecificStartingOffsetITCase.java

1. If the binaryLogClient does not have a registered server-id, the binaryLogClient will use the default 65535 parameter. If there is only one source in a Flink job, it will be normal.
2. If multiple sources register binaryLogClients using the default 65535 in a Flink job, registration may fail because one of the sources is searching for the timestamp of the binlog file and has not yet released the client registered using 65535 as the server-id.
3. If registration fails. BlockingQueue will always be empty and waiting without doing nothing.
When registering the binaryLogClient to search timestamp , use the server-id unique to each source for registration.

[FLINK-35674][cdc-connector][mysql]Fix blocking caused by searching for timestamp in binlog file

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/utils/StarRocksContainer.java

This fixes recent StarRocks pipeline connector IT case failure ([#10241560412](https://github.com/apache/flink-cdc/actions/runs/10241560412), [#10233853192](https://github.com/apache/flink-cdc/actions/runs/10233853192), ...), which was caused by an exception in FE startup method [here](https://github.com/StarRocks/starrocks/blob/0f2dc86d2a006ede7ad2bfd2d393cb3d70d0ccb0/fe/fe-core/src/main/java/com/starrocks/leader/MetaHelper.java#L171).
Newer version of StarRocks (3.0+) requires at least 5GB free disk space to start FE node (introduced by https://github.com/StarRocks/starrocks/pull/34813), while current GitHub Actions' configuration could not provide sufficient disk space. My guess is the last GitHub Actions runner image upgrade changed disk space usage situation, since neither CDC code …

[hotfix] Fix StarRocks FE startup failure due to insufficient disk space available

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/configuration/ConfigurationUtils.java

Fix exception like this:
```java
Caused by: java.lang.NullPointerException    at org.apache.flink.cdc.common.configuration.ConfigurationUtils.convertToString(ConfigurationUtils.java:133) ~[?:?]    at org.apache.flink.cdc.common.configuration.Configuration.toMap(Configuration.java:138) ~[?:?] 
```

[FLINK-35234][hotfix][cdc-common] Fix NullPointerException of org.apache.flink.cdc.common.configuration.ConfigurationUtils#convertToString

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/DateTimeUtils.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/ValuesDatabase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/metadata/TransformSqlOperatorTable.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformDataOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/JaninoCompilerTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This closes [FLINK-35743](https://issues.apache.org/jira/browse/FLINK-35743).

[FLINK-35743][cdc-runtime] Fix the time zone configuration for temporal functions is not effective

---

.github/workflows/flink_cdc.yml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/utils/StarRocksContainer.java

Due to the extensive use of Docker images by our CDC unit tests, GitHub runners are running low on disk space, with only `19 GB` remaining. To address this issue and free up additional disk space, we propose removing unnecessary packages from the GitHub runners.
- **Issue**: The frequent downloading of Docker images for CDC unit tests has significantly reduced the available disk space on our GitHub runners.
- **Action**: This merge request aims to delete outdated or unused packages to reclaim disk space and ensure that the runners operate efficiently.
By implementing these changes, we anticipate improved performance and reduced risk of disk space-related issues during CI/CD processes.
We can see `/mnt` has `66 GB` disk space, flink ci …

[hotfix][ci] Clean up disk space

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/schema/Column.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/schema/PhysicalColumn.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/schema/Schema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomAlterTableParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlPipelineRecordEmitter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaManager.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistry.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TableChangeInfo.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/serializer/schema/ColumnSerializer.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/serializer/schema/PhysicalColumnSerializer.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/serializer/schema/SchemaSerializer.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/serializer/schema/PhysicalColumnSerializerTest.java

This closes https://github.com/ververica/flink-cdc-connectors/issues/2936.

[FLINK-35893][cdc-runtime] Write CURRENT_VERSION of TableChangeInfo to state

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java

FLINK-34638 just implemented default value synchronization support.
However, `MySqlE2eITCase` wasn't updated correspondingly to validate check data records with default values, causing E2e cases' failure.

[hotfix][e2e] Add missing default values field in E2e test

---

docs/content.zh/docs/connectors/pipeline-connectors/kafka.md
docs/content/docs/connectors/pipeline-connectors/kafka.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkITCase.java

Refer to https://debezium.io/documentation/reference/1.9/connectors/mysql.html.

[FLINK-35791][kafka] add database and table info of canal/debezium json format for kafka sink.

---

.github/workflows/flink_cdc.yml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestEnvironment.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java

This bumps Flink version used by E2e test cases.
* 1.19.0 -> 1.19.1
*  NEW   -> 1.20.0
Also noticed that after this change, the whole E2e test would take nearly 90 minutes to finish, which is close to default GitHub action timeout limit. Separating pipeline and source E2e cases might help.

[tests] Run E2e tests on Flink 1.20 & Split E2e tests

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/SnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java

As described in https://issues.apache.org/jira/browse/FLINK-35859 , only discover new added table when `assignerStatus == INITIAL_ASSIGNING_FINISHED or || assignerStatus == NEWLY_ADDED_ASSIGNING_FINISHED`. It also same with what java doc says:

[FLINK-34688][cdc-connector] Fix: The assigner is not ready to offer finished split information, this should not be called

---

docs/content.zh/docs/connectors/pipeline-connectors/kafka.md
docs/content/docs/connectors/pipeline-connectors/kafka.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfo.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/serialization/CsvSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/serialization/JsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KeyFormat.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KeySerializationFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/PartitionStrategy.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/PipelineKafkaRecordSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfoTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/serialization/CsvSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/serialization/JsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaUtil.java

To make sure the same record sending to the same partition after job restarted.

[FLINK-35442][cdc-connect][kafka] add key.format and partition.strategy option

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSinkTranslator.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSourceTranslator.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/utils/FactoryDiscoveryUtils.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/utils/FactoryDiscoveryUtilsTest.java

As shown https://issues.apache.org/jira/browse/FLINK-36007 , once search is enough for cdc load factory and add jar url.

[FLINK-36007][[cdc-composer] cdc load factory and add jar in once search

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonCommitter.java

use filterAndCommit API for retried Committables.

[FLINK-35938][cdc-connect][paimon] use filterAndCommit API for retried Committables.

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/ProjectionColumnProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/UnifiedTransformOperatorTest.java

since metadata column existence check was done by searching identifier string in statement, without considering any syntax info
In the transform rule (projection: \*, '_namespace_nameschema_nametable_name_' AS string_literal) mentioned in FLINK-35984, Caused by: java.lang.IllegalArgumentException: wrong number of arguments is thrown because of the "\*" symbol. The PreTransformOperator introduced in FLINK-35272 fixes the "\*" problem, but there are still some scenarios where Caused by: java.lang.IllegalArgumentException: wrong number of arguments is thrown due to metaColumn name conflicts. This PR will fix these bugs.

[FLINK-35984][transform] Fix: Job crashes when metadata column names present in transform rules

---

flink-cdc-runtime/pom.xml
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/BuiltInScalarFunction.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/metadata/TransformSqlOperatorTable.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/SchemaEvolveTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This closes FLINK-35991 and FLINK-36034.
Currently, transform operator chains self-defined SqlFunctions and standard function tables, which might be a problem since there are some conflicting function declarations.
Getting rid of `SqlStdOperatorTable` and declaring supported functions only should resolve this problem.
Also, current implementation unreasonably relies on Flink table planner, causing trouble in Kubernetes deployment mode. Getting rid of it should solve this.

[FLINK-35991][FLINK-36034][transform] Resolve conflicts in transform SQL operator tables

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformExpressionCompiler.java

[BP-3.2][hotfix][runtime] Invalidate cache correctly to avoid classloader leakage

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformExpressionCompiler.java

Occasionally, CDC composer ITcase will fail when running test cases consecutively, with the following error message:
```
Caused by: java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
at org.apache.flink.util.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.ensureInner(FlinkUserCodeClassLoaders.java:184)
at org.apache.flink.util.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.loadClass(FlinkUserCodeClassLoaders.java:198)
at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
at …
```

[hotfix][runtime] Invalidate cache correctly to avoid classloader leakage

---

docs/content.zh/docs/core-concept/transform.md
docs/content/docs/core-concept/transform.md
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/ProjectionColumnProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformFilterProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformProjectionProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/metadata/MetadataColumns.java

This closes FLINK-35805.
Currently, event operation type (insert, update, or delete) was encoded in all `DataChangeEvents`. However it's not possible to access them in transform blocks since it is not exposed as metadata column. Adding this should allow such transform usages:
```yaml
transform:
- projection: \*, __data_event_type__ == '-D' AS logical_delete_tag
```

[FLINK-35805][transform] Add `__data_event_type__` metadata column

---

flink-cdc-cli/pom.xml
flink-cdc-common/pom.xml
flink-cdc-composer/pom.xml
flink-cdc-connect/pom.xml
flink-cdc-dist/pom.xml
flink-cdc-dist/src/main/assembly/assembly.xml
flink-cdc-e2e-tests/pom.xml
flink-cdc-migration-tests/pom.xml
flink-cdc-pipeline-udf-examples/pom.xml
flink-cdc-runtime/pom.xml
pom.xml
tools/releasing/create_source_release.sh

This pull request fixes several issues in Flink CDC parent pom and release script:
In parent pom:
- Parent pom should use artifact ID `flink-cdc-parent` instead of `flink-cdc`
- Distribution management pointing to Sonatype should be removed, as we should use Apache repository
- Parent pom should include correct SCM information
- Parent pom should use `apache-release` profile for releasing
In release script:
- LICENSE file should be included in the binary release
- Source release prefix should be `flink-cdc` instead of `apache-flink-cdc`

[FLINK-36054][cdc][build] Fix Flink CDC parent pom and release scripts

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaMetaDataApplier.java

[FLINK-36082][pipeline-connector][kafka] fix NotSerializableException for KafkaDataSink.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/BucketAssignOperator.java

Try to get latestSchema from SchemaRegistry when job restarted.
this pr is aimed to correct the judgement to request the latest Schema from SchemaRegistry for the DataChangeEvent that haven't met before.

[FLINK-36088][pipeline-connector][paimon] Fix NullPointerException in BucketAssignOperator.

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSourceTranslator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java

As discussed in https://issues.apache.org/jira/browse/FLINK-36076 , Current, we apply schema change asynchronous.  
SchemaChangeThreadPool will set isSchemaChangeApplying as true when apply schema change event. And the main thread which handle operater event will check isSchemaChangeApplying.
For thread safe, this should be volatile.

[FLINK-36076] Set isSchemaChangeApplying as isSchemaChangeApplying for thread safe.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/MultiTableCommittableChannelComputer.java

[FLINK-36111][Paimon] adjust MultiTableCommittableChannelComputer Topology name

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/split/MySqlBinlogSplit.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/split/MySqlBinlogSplitTest.java

**Problem Description:**
When adding a new table, the Flink CDC MySQL source connector experiences missing data for some columns of the newly added table.
**Reproduction Scenario:**
1. Remove a table from a cdc job that is running normally, then start the job with resume functionality.
2. Perform a column addition operation on the removed table.
3. Add the table back to the job. The job continues to run without interruption upon table addition, but data for the newly added columns is missing in the synchronized data.
**Cause Analysis:**
The issue arises because the MySQL CDC Source maintains the table schema in state. When adding a new table, it recovers the schema from the previous state. Since the prior schema exists and represents the structure before the column addition, the MySQL CDC …

[FLINK-36081][cdc-base][mysql] Fix that MySQL source connector missing some columns data of newly added tables

---

docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/pipeline-connectors/mysql.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MysqlPipelineNewlyAddedTableITCase.java

This allow to scan newly table DDL during incremental reading stage.

[FLINK-36115][pipeline-connector][mysql] add scan.incremental.newly-added-table.enabled option

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/utils/SqlServerTypeUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/org/apache/flink/cdc/connectors/sqlserver/source/read/fetch/SqlServerScanFetchTaskTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/resources/ddl/pk.sql

When introspecting a TIMESTAMP column from SQL Server, the connector should use the scale (in Debezium schema terms) as the value for the Flink TIMESTAMP precision, not length.
Otherwise, the connector attempts to convert `datetime` SQL Server type, which Debezium introspects as `datetime(23, 3)`, to Flink's `TIMESTAMP(23)` and fails:
> org.apache.flink.table.api.ValidationException: Timestamp precision must be between 0 and 9 (both inclusive).

[FLINK-35056] Fix conversion of SQL Server TIMESTAMP to Flink

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistry.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java

Currently, SchemaRegistryRequestHandler regards Flush success when it has collected all FlushSuccessEvent from all registered subTasks.
```java
if (flushedSinkWriters.equals(activeSinkWriters)) {
// ...
}
```
However, some subTasks might not be registered early enough, which means flush success condition might be falsely triggered:
```c
// 6 early came sink tasks have registered & flushed successfully
SchemaRegistry - Sink subtask 5 succeed flushing for table default_namespace.default_schema.table1. Attempt number: 0
SchemaRegistry - Sink subtask 0 succeed flushing for table default_namespace.default_schema.table1. Attempt number: 0
SchemaRegistry - Sink subtask 1 succeed flushing for table default_namespace.default_schema.table1. Attempt number: 0
SchemaRegistry - Sink subtask 2 succeed …
```

[hotfix] Fix schema registry flush state switch logic with multiple parallelism

---

flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/event/SchemaChangeEventType.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/pipeline/PipelineOptions.java
flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/ChangeEventUtils.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/utils/ChangeEventUtilsTest.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineUdfITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolveE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolvingTransformE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/partitioning/PrePartitionOperator.java

This closes FLINK-36128.
Currently, default schema evolution mode "EVOLVE" could not handle exceptions, and might not be able to restore from existing state correctly after failover. Before we can "trigger checkpoints on demand" which is not possible prior to in Flink 1.19, making "LENIENT" a default option might be more suitable.
This PR also contains a hotfix patch for PrePartitionOperator broadcasting failure.

[FLINK-36128] Promote LENIENT as the default schema change behavior

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/event/SchemaChangeRequest.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/partitioning/PrePartitionOperator.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/testutils/operators/EventOperatorTestHarness.java

This PR fixes:
* Schema registry hanging due to out-of-order requests
* Fix job failure when visiting DropTableEvent without a prior CreateTableEvent when starting up with timestamp mode

[hotfix] Keep upstream pending requests in order to avoid checkpoint hanging & state inconsistency in timestamp startup mode

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlPipelineRecordEmitter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceFactoryTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MysqlPipelineNewlyAddedTableITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/DebeziumUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/schema/Selectors.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/config/MySqlSourceConfig.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/config/MySqlSourceConfigFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlSourceReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/utils/TableDiscoveryUtils.java

As described in https://issues.apache.org/jira/browse/FLINK-36150 , this PR aims to pass `tables.exclude` to MySqlSourceConfig and will use it when find tables from mysql database.

[FLINK-36150][pipeline-connector/mysql] tables.exclude is still valid if scan.binlog.newly-added-table.enabled is true.

---

flink-cdc-migration-tests/flink-cdc-release-snapshot/src/main/java/org/apache/flink/cdc/migration/tests/SchemaRegistryMigrationMock.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistry.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryProvider.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/SchemaEvolveTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/testutils/operators/EventOperatorTestHarness.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/testutils/operators/MockedOperatorCoordinatorContext.java

This tweaks `SchemaRegistry` coordinator to let it handle requests / trigger checkpoints in background threads to avoid blocking the main thread.

[minor][cdc-runtime] Run schema coordinator logic asynchronously to avoid blocking the main thread

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomAlterTableParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomColumnDefinitionParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java

Currently, it is possible to parse correct CreateTableEvents from Binlog with the following syntax:
```sql
CREATE TABLE table1 (
id INT,
... -- other columns
PRIMARY KEY (id)
);
```
However, inlined primary key declaration syntax is not possible:
```sql
CREATE TABLE table1 (
id INT PRIMARY KEY,
... -- other columns
);
```
This should be resolved by adding missing `enterPrimaryKeyColumnConstraint` handlers in `CustomColumnDefinitionParserListener`.

[hotfix][mysql] Fix primary key restraints missing when using inline `PRIMARY KEY` declaration syntax

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomAlterTableParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/parser/CustomColumnDefinitionParserListener.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java

[BP-3.2][hotfix][mysql] Fix primary key restraints missing when using inline `PRIMARY KEY` declaration syntax

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java

In order to test if pipeline job could correctly handle dangling `DropTableEvent`s (those ones without preceding `CreateTableEvent`s) during binlog reading phase, this PR uses `specific-offset` startup mode to cover such case instead of `timestamp` mode which is not so precise and prone to cause CI failure.

[minor][tests] Fix `testDanglingDroppingTableDuringBinlogMode` tests case due to imprecise timestamp startup

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolveE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperator.java

This closes FLINK-36184.
Currently, tables that are not present in transform blocks should be treated as if there's such a dummy fallback block:
```yaml
transform:
- source-table: "\.*.\.*" # capture all unmentioned tables
projection: "*"         # keep all columns
```
There's a bug in #3557's implementation, where schema change events should be filtered out if there's no wildcard (`*`) in transform rules. However, it also filters out those tables that are not defined in transform rules, which causes schema change events lost with the following example:
```yaml
transform:
- source-table: foo.bar.baz   # Another table that doesn't really matter
projection: ...
```
Here, since there's one transform block, `TransformOperator` will be added into operator chain. Now let's perform some schema …

[FLINK-36184][transform] Fix transform operator swallows schema changes from tables not present in transform rules

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerLenientITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolveE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java

We should applySchemaChange (where the route rule works) first and lenientize its result then, or we may not be able to get evolved schema since tableId isn't routed:
```
Caused by: java.lang.IllegalStateException: Evolved schema does not exist, not ready for schema change event AddColumnEvent{tableId=kunni_test.customers, addedColumns=[ColumnWithPosition{column=`newCol2` VARCHAR(100), position=AFTER, existedColumnName=newCol}]}
at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler.lambda$lenientizeSchemaChangeEvent$3(SchemaRegistryRequestHandler.java:378)
at java.util.Optional.orElseThrow(Optional.java:290)
at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler.lenientizeSchemaChangeEvent(SchemaRegistryRequestHandler.j …
```

[FLINK-36183] Fix lenient schema evolution failure with route blocks

---

.github/workflows/build_docs.yml

This pull request update GitHub workflow for building documentation, to build 3.2 docs and mark it as stable.

[FLINK-36226][cdc][docs] Build 3.2 docs and mark it as stable

---

.github/workflows/close_stale.yml

This fixes `Stale` bot not working as expected due to workflow interactions.
Currently, `approve_label` workflow will trigger update for all PRs' update time, causing Stale label automatically removed though this PR has no updates at all.
Removing auto-remove feature should fix this.

[hotfix] Fix Stale label automatically removed with no update

---

docs/content.zh/docs/core-concept/schema-evolution.md
docs/content/docs/core-concept/schema-evolution.md

This closes FLINK-36151 by adding missing schema evolution related concepts into Flink CDC docs.

[FLINK-36151] Add schema evolution related docs

---

flink-cdc-pipeline-udf-examples/pom.xml

This closes FLINK-36214.
As discussed in https://github.com/apache/spark/pull/41261, compiling scala codes with scala-maven-plugin 4.8.1+ with Java 8 target (See https://github.com/davidB/scala-maven-plugin/issues/686), causing the following benign error message:
```
[ERROR] -release is only supported on Java 9 and higher
```
As it has not been resolved in latest version (`4.9.2`), downgrading it would be a workaround for now.

[FLINK-36214] Downgrade scala-maven-plugin version to 4.8.0 to keep compatibility with Java 8

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java

FlinkCDC uses debezium for capturing and parsing incremental data, but during the snapshot phase, FlinkCDC uses its own designed read implementation, so for FlinkCDC, some debezium options do not take effect, such as 'debezium.snapshot.query.mode'.

[FLINK-36463][cdc][mysql] Forbid to override some debezium options

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/pom.xml

To avoid conflict with flink-connector-kafka jar.

[FLINK-36211][pipeline-connector/kafka] shade org.apache.flink.streaming.connectors.kafka

---

flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-cli/src/test/resources/definitions/pipeline-definition-minimized.yaml

CDC yaml without pipeline should not throw exception.

[FLINK-36174][hotfix] CDC yaml without pipeline should not throw exception.

---

docs/content.zh/docs/deployment/kubernetes.md
docs/content/docs/deployment/kubernetes.md

https://issues.apache.org/jira/browse/FLINK-35544

[FLINK-35544][minor][docs] Add deployment documentations for Kubernetes Operator.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/utils/CustomPostgresSchema.java

As shown in https://issues.apache.org/jira/browse/FLINK-36618, this PR will significantly improve startup time several times or even dozens of times( maybe more) depending on number of table

[FLINK-36618][cdc-connector][postgres] Improve PostgresDialect.discoverDataCollections to reduce the start time of Postgres CDC.

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/SchemaUtils.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/utils/SchemaUtilsTest.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/SchemaOperatorTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksMetadataApplierITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolveE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/SchemaEvolvingTransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/SchemaOperatorFactory.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivation.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivationTest.java

This closes FLINK-36474.
For now, it's not possible to merge timestamp-family data (including `Timestamp`, `ZonedTimestamp`, and `LocalZonedTimestamp`) without some awkward transform rules and explicit castings. This PR adds the following type coercions:
* ~~`TIME`s,~~ `TIMESTAMP`s, `TIMESTAMP_TZ`s, and `TIMESTAMP_LTZ`s with promoted precision
For example, `TIMESTAMP(3)` and `TIMESTAMP(6)` will be considered compatible and data with lower precision will be automatically escalated to the higher one.
* `TIMESTAMP_TZ`s and `TIMESTAMP_LTZ`s will be converted to `TIMESTAMP` if necessary.
I reused some code from `SystemFunctionUtils#castToTimestamp`, so this implicit behavior should be equivalent to writing explicit castings manually.

[FLINK-36474] Support merging timestamp columns when routing

---

flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParserTest.java

This closes FLINK-36514.
If schema evolution behavior is set to LENIENT, Truncate / Drop table events will be ignored by default. However, there's currently no way for users to override this behavior due to the following code:
```java
// YamlPipelineDefinitionParser#toSinkDef
if (excludedSETypes.isEmpty() && SchemaChangeBehavior.LENIENT.equals(schemaChangeBehavior))
{
// In lenient mode, we exclude DROP_TABLE and TRUNCATE_TABLE by default. This could be
// overridden by manually specifying excluded types. 
Stream.of(SchemaChangeEventType.DROP_TABLE, SchemaChangeEventType.TRUNCATE_TABLE) 
.map(SchemaChangeEventType::getTag)
.forEach(excludedSETypes::add);
}
}
```
If one wants to exclude no types, it's actually not possible since passing `[]` is equivalent to passing nothing, and `DROP` and …

[FLINK-36514] Fix unable to override exclude schema types in lenient mode

---

docs/content.zh/docs/core-concept/transform.md
docs/content/docs/core-concept/transform.md

This closes FLINK-36221.
[FLINK-34877](https://issues.apache.org/jira/browse/FLINK-34877) adds `CAST ... AS ...` syntax in transform expressions, but there's no corresponding documentations yet. Adding it would make it easier for users to write expressions.

[FLINK-36221] Add `CAST ... AS ...` documentations

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/TransformTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java

This closes FLINK-35982.
One may readjust source table primary keys, partition keys, table options by specifying them in a Transform block like this:
```yaml
transform:
- source-table: db.tbl
projection: '*'
primary-keys: order_id, product_name
partition-keys: order_id
table-options: bucket=1
```
However, if the projection field is omitted (which fallbacks to default behavior that does not change any source table columns), such configuration will not take effect:
```yaml
transform:
- source-table: db.tbl
primary-keys: order_id, product_name
partition-keys: order_id
table-options: bucket=1 # These options will not apply
```
The underlying reason is transform blocks without `projection` was simply ignored by `PreTransformOperator`, which isn't accurate since other options like primary keys, …

[FLINK-35982] Fix transform metadata config doesn't work if no projection block was provided

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/utils/StatementUtils.java

[FLINK-36247](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-36247)
remove `connection.setAutoCommit(false)`

[FLINK-36247][cdc-connector] Fix potential transaction leak during MySQL snapshot phase

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java

PR #3537 and #3592 has some implicit conflicts that will cause CI failure.
#3537 changes `SUBSTR` function to 1-based index and corresponding test cases in #3592 didn't get updated yet.

[hotfix] Fix SUBSTR built-in function testcases

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java

https://issues.apache.org/jira/browse/FLINK-36649
Oracle When reading via OracleIncrementalSource, the connection is occasionally closed.
```
14:57:56,432 INFO  org.apache.flink.cdc.connectors.base.source.reader.IncrementalSourceSplitReader [Source Data Fetcher for Source: doris_source[1] -> SinkConversion[2] -> Sink: Print to Std. Out (1/1)#0] [] - Close snapshot reader org.apache.flink.cdc.connectors.base.source.reader.external.IncrementalSourceScanFetcher
14:57:56,597 INFO  io.debezium.jdbc.JdbcConnection                              [pool-14-thread-1] [] - Connection gracefully closed
14:57:56,602 ERROR io.debezium.connector.oracle.logminer.LogMinerHelper         [debezium-snapshot-reader-0] [] - Mining session stopped due to the java.sql.SQLException: 关闭的 Resultset: getLong …
```

[FLINK-36649] Fix oracle connection close error by OracleIncrementalSource read

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistry.java

See the details in [FLINK-36407](https://issues.apache.org/jira/browse/FLINK-36407). Not sure how this can be unit-tested given that the issue is not reproducible with JUnit.

[FLINK-36407] Shut down coordinatorExecutor upon closing SchemaRegistry

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfo.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfoTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriterHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriterHelperTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksPipelineITCase.java

This test case has already indicated this issue, but it was initially overlooked.
1. For Paimon & Kafka, they already support timestamp with local time zone type, so we don't need add extra conversion using zoneId.
2. For Doris & Starrocks, they only have datetime type and don't support timestamp with local time zone, refer to https://doris.apache.org/zh-CN/docs/1.2/sql-manual/sql-reference/Data-Types/DATETIMEV2/ and https://docs.starrocks.io/docs/sql-reference/data-types/date-types/DATE/, so we need to convert timestamp_ltz to timestamp using zoneid of database, Therefore, we do not need to modify the implementation.

[FLINK-36560][pipeline-connector][paimon] fix the issue that timestamp_ltz field is not correctly converted.

---

flink-cdc-pipeline-udf-examples/pom.xml

[BP-3.2][FLINK-36214] Downgrade scala-maven-plugin version to 4.8.0 to keep compatibility with Java 8

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonCommitter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

https://issues.apache.org/jira/browse/FLINK-35938 problem still persists.
`storeMultiCommitter.commit` API may cause the same datafile commit twice when job restart from failure.

[FLINK-36517][cdc-connect][paimon] use filterAndCommit API for Avoid commit the same datafile duplicate

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerLenientITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSourceHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSourceOptions.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaRegistryRequestHandler.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaDerivationTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/schema/coordinator/SchemaManagerTest.java

SchemaOperator receives an AddColumnEvent/RenameColumnEvent inLenient mode , the default value will be lost when sent downstream.
JIRA: [https://issues.apache.org/jira/browse/FLINK-36375](https://github.com/apache/flink-cdc/pull/url)

[FLINK-36375][cdc-runtime] Fix missed default value in AddColumnEvent/RenameColumnEvent

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

PaimonSink now implements StatefulSink to store checkpointId in state, It has been verified through local testing that it is compatible with the state of 3.2.0. I will try to add a state compatibility test.

[FLINK-36541][pipeline-connector][paimon] pass checkpointId to StoreSinkWrite#prepareCommit correctly.

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/SchemaUtils.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperator.java

This closes FLINK-36461.
Currently, such transform configuration will fail for any schema change events from tables except `foo.bar.baz`:
```yaml
transform:
  - source-table: foo.bar.baz
    projection: \*
```
The exception message is as follows:
```
java.lang.ArrayIndexOutOfBoundsException: -1
at java.util.ArrayList.elementData(ArrayList.java:424)
at java.util.ArrayList.get(ArrayList.java:437)
at org.apache.flink.cdc.common.utils.SchemaUtils.lambda$transformSchemaChangeEvent$11(SchemaUtils.java:371)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at …
```

[FLINK-36461] Fix schema evolution failure with un-transformed tables

---

docs/content.zh/docs/deployment/yarn.md
docs/content/docs/deployment/yarn.md

See the details in #3706 , backport PR for release-3.2 branch

[FLINK-36678][docs][deploy] Fixed the documentation error of Flink CDC YARN deployment mode

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java

fix Unsupported bucket mode: GLOBAL_DYNAMIC error.

[FLINK-36609][pipeline-connector][paimon] add partition columns to primary keys.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfo.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/TableSchemaInfoTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriterHelper.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriterHelperTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksPipelineITCase.java

backport FLINK-36560 to release-3.2
(cherry picked from commit ecfee702dc91a1e039b1b6f3fc16fa50dfc1331c)

[BP release 3.2][FLINK-36560][pipeline-connector][paimon] Fix the issue that timestamp_ltz field is not correctly converted

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestEnvironment.java

This is a temporary workaround before FLINK-36690 get closed.
Occasionally, SchemaRegistry freezes when handling schema change events simultaneously in parallel. Current E2e test touches this corner case frequently and keeps failing.
Temporarily fallback to single-parallelism testcases to allow CI passing for now.

[hotfix][e2e] Temporarily disable multiple parallelism E2e cases

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/types/utils/DataTypeUtils.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/types/utils/DataTypeUtilsTest.java

Correct the nullability for data type ARRAY and MAP in method `DataTypeUtils#toFlinkDataType`.

[FLINK-36699][common] Fix nullability when converting cdc data type to flink data type

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/io/debezium/connector/mysql/converters/MysqlDebeziumTimeConverter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/converters/MysqlDebeziumTimeConverterITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/ddl/date_convert_test.sql

Fix [FLINK-35173](https://issues.apache.org/jira/browse/FLINK-35173) MysqlDebeziumTimeConverter miss timezone convert to timestamp.

[FLINK-35592] Fix MysqlDebeziumTimeConverter miss timezone convert to timestamp

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java

This closes FLINK-36596. ~~Requires #3632 being merged first.~~
As described in docs, omitting `transform[*].projection` field in YAML definition should be equivalent to `projection: \*` expression. However, now schema change events will be dropped when there are no projection fields explicitly written down. For example, the following definition:
```yaml
transform:
- source-table: db.tbl
filter: x > 0
```
could not apply upstream schema change events to downstream due to the lacking of `projection` block, which would be surprising.
Unifying the syntax of `projection: \*` and omitting `projection` field should fix this.

[FLINK-36596] Fix unable to schema evolve with project-less transform rules

---

docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md

backport [FLINK-36681](https://issues.apache.org/jira/browse/FLINK-36681) to release-3.2
(cherry picked from commit https://github.com/apache/flink-cdc/commit/ba74c7c45ff69ccb0052e9ae17972de4a4257ba0)

[BP release-3.2][FLINK-36681][mysql-cdc][docs] Fix the wrong chunks splitting query in incremental snapshot reading section

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisPipelineITCase.java
tools/ci/license_check.rb

This closes FLINK-36285.
Thanks to @qg-lin's great work in https://github.com/apache/doris-flink-connector/pull/490, doris-flink-connector now supports altering column type without passing default value explicitly. Bumping dependency version should close this issue.

[FLINK-36285][doris] Fix unable to alter column type without default value specified

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonCommitter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

[FLINK-36517][pipeline-connector][paimon] Use filterAndCommit API to avoid committing the same datafile twice

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java

backport FLINK-36509 to release-3.2
(cherry picked from commit ae986ab3f607d788b4b82e2aabceb3e807a54139)

[BP release-3.2][FLINK-36509][pipeline-connector][paimon] Add partition columns to primary keys

---

docs/content.zh/docs/connectors/flink-sources/vitess-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/elasticsearch.md
docs/content/docs/connectors/flink-sources/vitess-cdc.md
docs/content/docs/connectors/pipeline-connectors/elasticsearch.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/pom.xml

backport PR for release-3.2 branch

[FLINK-36052][docs][cdc-pipeline-connector/es] Add flink cdc pipeline elasticsearch connector docs

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/StoreSinkWriteImpl.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

Use replace API instead of removing and recreating StoreSinkWrite to keep the write state consistent with previous  StoreSinkWrite.

[FLINK-36750][paimon] Restore SinkWrite from state to keep the information of previous SinkWrite when schema evolution happen.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/main/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/src/test/java/org/apache/flink/cdc/connectors/starrocks/sink/StarRocksDataSinkFactoryTest.java

backport [FLINK-36572](https://issues.apache.org/jira/browse/FLINK-36572) to release-3.2
(cherry picked from commit https://github.com/apache/flink-cdc/commit/be9b52750c7bb4835a7b8631ebdb17666aff6bb1)

[BP release-3.2][FLINK-36572][pipeline-connector][starrocks] Fix the issue that the local time zone is wrongly set

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/splitter/JdbcSourceChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/meta/split/SnapshotSplit.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/test/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/test/java/org/apache/flink/cdc/connectors/base/source/meta/split/SourceSplitSerializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/assigners/splitters/SampleBucketSplitStrategy.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/assigners/splitters/ShardedSplitStrategy.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/assigners/splitters/SingleSplitStrategy.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/assigners/splitters/SplitStrategy.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/assigners/splitters/SplitVectorSplitStrategy.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/split/MySqlSnapshotSplit.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/split/MySqlSplitSerializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/split/MySqlSplitStateTest.java

This PR make the connectors use the same format `tableId:chunkId` for splitId in SnapshotSplit.

[FLINK-36803][cdc-connector][base] Use the same format `tableId:chunkId` for splitId in SnapshotSplit

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/java/org/apache/flink/cdc/connectors/oceanbase/OceanBaseTestBase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/java/org/apache/flink/cdc/connectors/oceanbase/table/OceanBaseMySQLModeITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/java/org/apache/flink/cdc/connectors/oceanbase/testutils/UniqueDatabase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/resources/ddl/mysql/column_type_test.sql
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/resources/ddl/mysql/inventory.sql

This fixes a mysterious test failure in OceanBaseMySQLModeITCase like [this](https://github.com/apache/flink-cdc/actions/runs/11720914709/job/32647267237). Recently it is happening quite frequently, possibly brought in by #3439.
This could be stably reproduced locally, by running `OceanBaseMySqlModeITCase` locally, and make sure `testMetadataColumns` is executed right after `testSnapshotOnly`.
This test case will fail, because instead of getting expected
```
+I(test,inventory,products,101,scooter,Small 2-wheel scooter,3.1400000000), 
+I(test,inventory,products,102,car battery,12V car battery,8.1000000000), 
+I(test,inventory,products,103,12-pack drill bits,12-pack of drill bits with sizes ranging from #40 to #3,0.8000000000), 
+I(test,inventory,products,104,hammer,12oz carpenter's …
```

[tests][oceanbase] Fix oceanbase test failure, possibly caused by some interactions among cases

---

NOTICE
flink-cdc-dist/src/main/assembly/assembly.xml

Now, Flink CDC's NOTICE file contains no third-party software notice, which violates corresponding open-source license that requires explicit mentioning during redistribution.
I added corresponding third-party open-source software licenses by referencing a properly written [NOTICE file example](https://github.com/apache/paimon/blob/master/NOTICE) from Paimon project.

[legal] Add third-party OSS NOTICE

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/enumerator/IncrementalSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/enumerator/MySqlSourceEnumerator.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/source/NewlyAddedTableITCase.java

[FLINK-36771](https://issues.apache.org/jira/browse/FLINK-36771)

[FLINK-36771][cdc-base][mysql] Fix UT trigger error: Invalid assigner status {} [NEWLY_ADDED_ASSIGNING_FINISHED]

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/test/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializerTest.java

Given that the output buffer is reused between calls to `serialize()`, it should be cleared in a `finally` block to account for potential exceptions.

FLINK-36891: MySQL CDC connector produces corrupted state in case of serialization failure

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/dialect/DataSourceDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/SnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/splitter/ChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/splitter/JdbcSourceChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/state/ChunkSplitterState.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/state/SnapshotPendingSplitsState.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/dialect/Db2ChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/dialect/Db2Dialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/assigners/splitters/MongoDBChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/dialect/MongoDBDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/OracleDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/assigner/splitter/OracleChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/source/NewlyAddedTableITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/source/OracleSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/source/OracleSourceTestBase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/table/OracleConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/PostgresDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresScanFetchTaskTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/dialect/SqlServerChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/dialect/SqlServerDialect.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/org/apache/flink/cdc/connectors/sqlserver/source/read/fetch/SqlServerScanFetchTaskTest.java
flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/OracleE2eITCase.java

As shown in https://issues.apache.org/jira/browse/FLINK-34688 :
In Mysql CDC,  MysqlSnapshotSplitAssigner splits snapshot chunks asynchronously(https://github.com/apache/flink-cdc/pull/931). But CDC framework lacks it.
If table is too big to split, the enumerator will be stuck, and checkpoint will be influenced( sometime will checkpoint timeout occurs).

[FLINK-34688][cdc-connector] CDC framework split snapshot chunks asynchronously

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/splitter/JdbcSourceChunkSplitter.java

JdbcChunkUtils#queryMin()
final String minQuery =
String.format(
"SELECT MIN(%s) FROM %s WHERE %s > ?",
quotedColumnName, quotedTableName, quotedColumnName);
but JdbcSourceChunkSplitter #queryMin
protected Object queryMin(
JdbcConnection jdbc, TableId tableId, Column splitColumn, Object excludedLowerBound)
throws SQLException
{ return JdbcChunkUtils.queryMin( jdbc, jdbc.quotedColumnIdString(splitColumn.name()), jdbc.quotedTableIdString(tableId), excludedLowerBound); }
Error passing column/tableId parameter. Resulting in the generated sql "select tableId from columnID".

[FLINK-36895]The JdbcSourceChunkSplitter#queryMin method passed a parameter with tableName/coiumnName reversed.

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerLenientITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/ProjectionColumn.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/UnifiedTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This closes FLINK-36854.
Consider the following simple schema:
`[id INT NOT NULL COMMENT 'id_field' DEFAULT 17]`
This would be sync to downstream sink databases that supports them intactly.
However, things would go wrong after being transformed like this:
```yaml
transform:
- projection: id, id AS id_alias, id + 1 AS id_new
```
Here, `id_new` column should carry no comments / default expressions obviously, since it has nothing to do with original `id` technically.
However, for `id` and `id_alias` column, it's reasonable to expect that comments and default expressions to be kept. Worse still, the nullability of `id_alias` will be lost since the previous half is regarded as a complex expression, and nullability of an expression's return type is uncertain.
So, currently the transform will …

[FLINK-36854] Fix comments and default expressions missing after being transformed

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java

A follow up of #3357. It would be surprising if narrowing expressions like `CAST(3.14 AS INT)` are forbidden.

[FLINK-36866] Fix unable to narrow casting on numeric values

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/JaninoCompilerTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This closes FLINK-36864.
Flink SQL (and its underlying Calcite framework) allows integer literals within `Int64` range (`-9223372036854775808` ~ `9223372036854775807`), which is enough for most cases.
However, CDC YAML parser supports Int32 range (`-2147483648` ~ `2147483647`) only, because Java code only allows `Int32` literals without any suffix. This could be overridden by appending an extra "L" at the end of the literal.

[FLINK-36864] Fix unable to use numeric literals that goes beyond Int32 range

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/source/SupportedMetadataColumn.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/DataSourceTranslator.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/TransformTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerLenientITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineUdfITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSource.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlEventDeserializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/OpTsMetadataColumn.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/OpTsMetadataColumn.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSource.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSourceHelper.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformer.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/ProjectionColumnProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformFilterProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformProjectionProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformRule.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/metadata/MetadataColumns.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This PR supports to add metadata in the meta field of DataChangeEvent at transform.

[FLINK-36784][common] Support to add metadata columns for data in the meta fields of DataChangeEvent at transform

---

docs/config.toml

The existing Table of Contents on the right-hand side of the page does not display H1 elements. 
H1 are used throughout the docs as part of the logical presentation of content.
Therefore it makes sense to include them, as is already done in the main Flink docs.

[docs] Fix ToC to include H1

---

.github/workflows/close_stale.yml

Some issues and PRs are not meant to be closed automatically, like roadmap / umbrella tickets. By specifying an exempt label, repo members could override stale checking by appending a **"pinned"** label.

[hotfix] Allow pinning issues & PRs that never decay

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/java/org/apache/flink/cdc/connectors/oceanbase/table/OceanBaseMySQLModeITCase.java

> Originally reported by @Jzjsnow in https://github.com/apache/flink-cdc/pull/3802#issuecomment-2567352155.
Currently, OceanBase CDC connector determines the specific offset that marks the transition from "snapshot" to "streaming" stage by a timestamp (second-precision only).
However, when Binlog records are actively inserted near the transition point, duplicate insert events might be emitted:
```
Snapshot starts here
|
v
------------> +I[1] -----> +I[2] -----> -D[1] -----> ...
^
|
Transition Point marked here
```
Since we don't have much records in database in test cases, snapshot stage completes almost immediately. Thus, record `+I[1]` might be emitted twice (as a snapshot record first, and a streaming record later).
#3211 should fix this by enforcing the "exactly-once" semantic to …

[hotfix][tests] Fix unstable `OceanBaseMySQLModelITCase`

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/SchemaUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/common/SchemaDerivator.java

[hotfix] Remove duplicated code to improve performance

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/pom.xml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonCommitter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/StoreSinkWriteImpl.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/BucketAssignOperator.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java

1) bump version to 0.9.0. 
2) Forcibly add cache-enabled = false in catalog option to avoid using previous table schema.
Refer to https://paimon.apache.org/docs/master/maintenance/configurations/#catalogoptions, after bump version to 0.9.0, we can support create table with uppercase columns using allow-upper-case catalog option, which resolved https://issues.apache.org/jira/browse/FLINK-36475.

[FLINK-36524][pipeline-connector][paimon] bump version of Paimon to 0.9.0

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/main/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchema.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/canal/CanalJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/sink/KafkaDataSinkITCase.java

An example of current output:
```
{
"old": [
{
"id": 8,
"name": "zhangsan3",
"age": 30
}
],
"data": null,
"type": "DELETE",
"database": null,
"table": "flink_penghai_test_yaml_student_copy2",
"pkNames": [
"id"
],
"ts": 0
}
```
However, for canal-json, fields in delete record should be written to `data` field instead of `old` field.
Otherwise, we will get java.io.IOException: Corrupt Canal JSON message when reading with Kafka connector.

[FLINK-36877][pipeline-connector-kafka] Fix the output of canal-json for Kafka Sink when the record is deleted record.

---

docs/content.zh/docs/core-concept/transform.md
docs/content/docs/core-concept/transform.md
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerLenientITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineUdfITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformProjectionProcessor.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformOperatorWithSchemaEvolveTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/UnifiedTransformOperatorTest.java

This closes FLINK-36956 by appending NOT NULL attribute to columns that declared as Primary Keys.

[FLINK-36956][transform] Append NOT NULL attribute to PK columns

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposerITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformProjection.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformProjectionProcessor.java

In FlinkPipelineComposerITCase.testTransformMergingWithRoute:
```
// Create test dataset:
// Create table 1 [id, name, age]
// Table 1: +I[1, Alice, 18]
// Table 1: +I[2, Bob, 20]
// Table 1: -U[2, Bob, 20] +U[2, Bob, 30]
// Create table 2 [id, name, age, description]
// Table 2: +I[3, Charlie, 15, student]
// Table 2: +I[4, Donald, 25, student]
// Table 2: -D[4, Donald, 25, student]
// Rename column for table 1: name -> last_name
// Add column for table 2: gender
// Table 1: +I[5, Eliza, 24]
// Table 2: +I[6, Frank, 30, student, male] 
```
This is executed correctly.
```
// Create test dataset:
// Create table 1 [id, name, age]
// Create table 2 [id, name, age, description]
// Table 1: +I[1, Alice, 18]
// Table 1: +I[2, Bob, 20]
// Table 1: -U[2, Bob, 20] +U[2, Bob, 30]
// Table 2: +I[3, …
```

[FLINK-36981][cdc] Fix the bug of transform merging with route in YAML task

---

flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/SchemaMergingUtils.java
flink-cdc-common/src/test/java/org/apache/flink/cdc/common/utils/SchemaMergingUtilsTest.java

In SchemaMergingUtils#getLeastCommonType, the merge result of BIGINT and DOUBLE is STRING now.
However, considering JSON format, JSON numbers can be integers or floating point, which can be inferred as BIGINT and  DOUBLE respectively. In this case, a JSON number field will be inferred as STRING, which is confusing.
The updated data type merge tree is:
```mermaid
graph TD;
BOOLEAN --> STRING;
CHAR --> STRING;
VARCHAR --> STRING;
BINARY --> STRING;
VARBINARY --> STRING;
TINYINT --> FLOAT;
SMALLINT --> FLOAT;
FLOAT --> DOUBLE;
INT --> DOUBLE;
TINYINT --> SMALLINT --> INT --> BIGINT --> DOUBLE --> STRING;
BIGINT --> DECIMAL;
DECIMAL --> STRING;
TIMESTAMP --> TIMESTAMP_LTZ --> TIMESTAMP_TZ --> STRING;
TIME --> STRING;
ROW -->  STRING;
ARRAY --> STRING;
MAP --> STRING;
```

[FLINK-36970][runtime] Merge result of data type BIGINT and DOUBLE should be DOUBLE instead of STRING

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineUdfITCase.java
flink-cdc-pipeline-model/src/test/java/org/apache/flink/cdc/runtime/model/TestOpenAIChatModel.java
flink-cdc-pipeline-model/src/test/java/org/apache/flink/cdc/runtime/model/TestOpenAIEmbeddingModel.java

[FLINK-35325][transform] Skip insufficient_quota error when running test case using ad model.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/SnapshotSplitReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssignerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlSourceReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/utils/MockMySqlSplitEnumeratorEnumeratorContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/testutils/MetricsUtils.java

See [FLINK-36811](https://issues.apache.org/jira/browse/FLINK-36811).

[FLINK-36811][mysql] MySQL cdc setIsProcessingBacklog in snapshot phase and exit when snapshot phase finished

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/ProjectionColumnProcessor.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java

pipelin.yml
```
...
transform:
  - source-table: testdb.cdc_test
    projection: id, concat(__table_name__,'_',id) as tbname_id
    primary-keys: id
....
```
When the id is not string type, the following exception is thrown
```
Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.janino.ExpressionEvaluator.evaluate(ExpressionEvaluator.java:541)
        at org.codehaus.janino.ExpressionEvaluator.evaluate(ExpressionEvaluator.java:533)
    …
```

[FLINK-37012][transform] Fix exception caused by metadataColumns causing argument type mismatch

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java

remove Catalog.ColumnAlreadyExistException when apply applyAddColumnEventWithPosition in paimon. because use may create table already before with the target column.

[FLINK-36985]remove Catalog.ColumnAlreadyExistException when apply applyAddColumnEventWithPosition in paimon

---

README.md
docs/content.zh/docs/get-started/quickstart/cdc-up-quickstart-guide.md
docs/content/docs/get-started/quickstart/cdc-up-quickstart-guide.md
tools/cdcup/.gitignore
tools/cdcup/Dockerfile
tools/cdcup/README.md
tools/cdcup/cdcup.sh
tools/cdcup/src/app.rb
tools/cdcup/src/download_libs.rb
tools/cdcup/src/sink/doris.rb
tools/cdcup/src/sink/kafka.rb
tools/cdcup/src/sink/paimon.rb
tools/cdcup/src/sink/star_rocks.rb
tools/cdcup/src/sink/values_sink.rb
tools/cdcup/src/source/my_sql.rb
tools/cdcup/src/source/values_source.rb

This closes FLINK-35634.
* implemented an cli utility to simplify cdc playground environment configuration
* added corresponding docs in quickstart guide

[FLINK-35634] Add CdcUp playground CLI scripts

---

flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/CliFrontend.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/CliFrontendOptions.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/CliFrontendTest.java

Support overwrite flink config in the command line, for example:
`bin/flink-cdc.sh1732864461789.yaml --flink-conf execution.checkpointing.interval=10min --flink-conf rest.bind-port=42689 --flink-conf yarn.application.id=application_1714009558476_3563 --flink-conf execution.target=yarn-session --flink-conf rest.bind-address=10.5.140.140`
The example provided is used to submit a job to a specified host's YARN session cluster with specific Flink configurations.

[FLINK-36974]support overwrite flink config by command line

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/WatermarkDispatcher.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/relational/JdbcSourceEventDispatcher.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/reader/external/AbstractScanFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/reader/external/JdbcSourceFetchTaskContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/fetch/Db2ScanFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/fetch/Db2SourceFetchTaskContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/fetch/Db2StreamFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/reader/fetch/EventProcessorFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/reader/fetch/OracleScanFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/reader/fetch/OracleSourceFetchTaskContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/reader/fetch/OracleStreamFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/fetch/CDCPostgresDispatcher.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresScanFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresSourceFetchTaskContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/reader/fetch/SqlServerScanFetchTask.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/reader/fetch/SqlServerSourceFetchTaskContext.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/reader/fetch/SqlServerStreamFetchTask.java

As shown in FLINK-35387, postgres cdc support: debezium.heartbeat.action.query

[FLINK-35387][cdc-connector][postgres] PG CDC source support heart beat.

---

docs/content.zh/docs/core-concept/transform.md
docs/content/docs/core-concept/transform.md
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

Timestamp data can not be compared in cdc pipeline transform.
When projecting or filtering code containing timestamp comparisons, the program will encounter errors.
```
TO_TIMESTAMP('2024-01-01 00:00:00') < TO_TIMESTAMP('2024-08-01 00:00:00')
```
Error:
```
org.apache.flink.api.common.InvalidProgramException: Expression cannot be compiled. This is a bug. Please file an issue.
Expression: import static org.apache.flink.cdc.runtime.functions.SystemFunctionUtils.*;toTimestamp("2024-01-01 00:00:00", __time_zone__) < toTimestamp("2024-08-01 00:00:00", __time_zone__) ? 1 : 0
...
...
Caused by: org.codehaus.commons.compiler.CompileException: Line 1, Column 176: Operator "<" not allowed on reference operands 
```
This PR has already solved the problem, and its modifications mainly include the …

[FLINK-36636][cdc] Timestamp data supports comparison in cdc pipeline transform

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/SchemaChangeProvider.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java

paimon apply default value options when apply add_column schema change

[FLINK-36977]paimon apply default value options when apply add_column schema change

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineUdfITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/sink/ValuesDataSinkHelper.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/BinaryTypeReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/CharTypeReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/DecimalTypeNonNullReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/DecimalTypeReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/LocalZonedTimestampTypeReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/TimestampTypeReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/VarBinaryTypeReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/java/org/apache/flink/cdc/udf/examples/java/precision/VarCharTypeReturningClass.java
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/BinaryTypeReturningClass.scala
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/CharTypeReturningClass.scala
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/DecimalTypeNonNullReturningClass.scala
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/DecimalTypeReturningClass.scala
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/LocalZonedTimestampTypeReturningClass.scala
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/TimestampTypeReturningClass.scala
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/VarBinaryTypeReturningClass.scala
flink-cdc-pipeline-udf-examples/src/main/scala/org/apache/flink/cdc/udf/examples/scala/precision/VarCharTypeReturningClass.scala
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/metadata/TransformTable.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/typeutils/DataTypeConverter.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

The precision and scale of Decimal has been lost when use FlinkCDC transform to project express or alias.
The fields of this table are as follows:
| Column Name | Data Type |
| :---- | :----: |
| id | int |
| name | varchar(50) |
| sex | char(1) |
| address | binary(50) |
| phone | varbinary(50) |
| deposit | decimal(10, 2) |
| birthday | timestamp(3) |
| birthday_ltz | timestamp_ltz(3) |
| update_time | time(3) |
The projection rule of this pipeline are as follows:
```
projection: id, UPPER(name) as name2, UPPER(sex) as sex2, COALESCE(address,address) as address2, COALESCE(phone,phone) as phone2, COALESCE(deposit,deposit) as deposit2, COALESCE(birthday,birthday) as birthday2, COALESCE(birthday_ltz,birthday_ltz) as birthday_ltz2, COALESCE(update_time,update_time) as update_time2
```
The …

[FLINK-36741][cdc][transform] Fix the precision of and length of data type has been lost when use transform and support DecimalData

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/definition/TransformDef.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/translator/TransformTranslator.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformRule.java

When projection is empty or NULL, the projection should be treated as an asterisk. The following transform rule should throw an exception [different column counts], but the actual schema columns are id and name, which is not expected.
```
transform:
- source-table: testdb.test_table1
filter: age> 8 and age < 18
- source-table: testdb.test_table1
projection: id,UPPER(name) AS name
filter: age >= 18 
```
The following transform rule will throw exception [different column counts]
```
transform:
- source-table: testdb.test_table1
projection: *
filter: age> 8 and age < 18
- source-table: testdb.test_table1
projection: id,UPPER(name) AS name
filter: age >= 18 
```
We should treat projection as asterisk when it is empty or NULL, to be consistent

[FLINK-36754][transform] when projection is empty or null, it is treated as an asterisk

---

.github/workflows/flink_cdc_base.yml
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-maxcompute/src/test/java/org/apache/flink/cdc/connectors/maxcompute/EmulatorTestBase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-maxcompute/src/test/java/org/apache/flink/cdc/connectors/maxcompute/utils/TypeConvertUtilsTest.java

This PR fixes failing unit tests in MaxCompute Pipeline Connector by upgrading the maxcompute-emulator dependency from 0.0.4 to 0.0.7.
- Updated `maxcompute-emulator` version in org.apache.flink.cdc.connectors.maxcompute.EmulatorTestBase

[hotfix][maxcompute] Fix MaxCompute Pipeline Connector unit tests by upgrading maxcompute-emulator

---

docs/content.zh/docs/connectors/pipeline-connectors/overview.md
docs/content/docs/connectors/pipeline-connectors/overview.md

[FLINK-36224](https://issues.apache.org/jira/browse/FLINK-36224)

[FLINK-36224][docs] Add the version mapping between pipeline connectors and flink

---

flink-cdc-dist/src/main/flink-cdc-bin/bin/flink-cdc.sh

Currently, most of FlinkCDC's command line arguments are supported in the format `--$KEY $VALUE`  or `--$KEY=$VALUE`, e.g. --jar, but, except for flink home, which only supports space spacing. Users who use the `--flink-home=$FLINK_HOME` format on the command line (trying to be consistent with the other = spacing arguments) will not be able to set flink home correctly.
In particular, when there is an environment variable $FLINK_HOME and you want to override it by setting --flink-home=/path/to/new/flink/home, you will find that it does not work.
Here, we make the flink-home parameter available in both --flink-home $FLINK_HOME and --flink-home=$FLINK_HOME formats in the `flink-cdc.sh` script, so that users can avoid formatting differences and runtime exceptions when using command line …

[FLINK-36620][cdc-dist] Add support for specifying the --flink-home command line parameter with an '=' character

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/org/apache/flink/cdc/connectors/doris/sink/DorisRowConverter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisMetadataApplierITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/test/java/org/apache/flink/cdc/connectors/doris/sink/DorisRowConverterTest.java

Support the conversion of Flink TIME type to Doris String type [FLINK-36351](https://issues.apache.org/jira/browse/FLINK-36351.)

[FLINK-36351][pipeline-connector/doris] support the conversion of Flink TIME type to Doris String type

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/common/SchemaRegistry.java

This is a follow-up PR after #3623

[FLINK-36406][cdc-runtime] Close MetadataApplier when the job stops

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceFactoryTest.java

Add treat-tinyint1-as-boolean.enabled to optional options

[FLINK-36282][pipeline-connector][cdc-connector][mysql]fix incorrect data type of TINYINT(1) in mysql pipeline connector

---

.github/labeler.yml
.github/workflows/close_stale.yml
.github/workflows/flink_cdc_ci_nightly.yml

This PR contains some pretty trivial fixes on our GHA workflows:
* Changes PR stale cycle to 120d / 60d
Now, our `actions/stale` workflow closes inactive PRs with a 60 / 30 days cycle, that is to say, 60 days' inactive to label it "Stale" and 30 more days to close it. But it turns out to be too eager and has accidentally closed many useful PRs.
This change has been discussed with other maintainers.
* Update outdated "Labeler"
Labeler can automatically detect what files have been touched, and categorize PRs with suitable labels, based on a predefined ruleset. It's just a routine update on the rule definition.
* Run nightly CI on a more "random" time instead of 00:00 UTC
There are really too much CI workflows scheduled to run on UTC midnight that Apache's download server could not handle …

[hotfix] Miscellaneous fixes on GHA workflows

---

docs/config.toml

This PR changes docs in master to 3.4-SNAPSHOT

[hotfix][docs] Change docs in master to 3.4-SNAPSHOT

---

docs/content.zh/docs/core-concept/data-pipeline.md
docs/content.zh/docs/core-concept/data-sink.md
docs/content.zh/docs/core-concept/data-source.md
docs/content.zh/docs/core-concept/route.md
docs/content.zh/docs/core-concept/table-id.md
docs/content.zh/docs/core-concept/transform.md

Translate "Core Concept" Pages of Flink CDC into Chinese Documentation.

[FLINK-34729][docs] Translate "Core Concept" Pages of Flink CDC into Chinese Documentation.

---

docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md

Align https://nightlies.apache.org/flink/flink-cdc-docs-master/zh/docs/connectors/flink-sources/postgres-cdc/#connector-options with https://nightlies.apache.org/flink/flink-cdc-docs-master/docs/connectors/flink-sources/postgres-cdc/

[FLINK-37252][doc] Align Chinese document of Postgres CDC Connector with English document.

---

docs/content.zh/docs/connectors/flink-sources/mongodb-cdc.md

Add missing doc of [Full Changelog](https://nightlies.apache.org/flink/flink-cdc-docs-release-3.3/docs/connectors/flink-sources/mongodb-cdc/#full-changeloga-namefull-changelog-id003-a) session.

[FLINK-37224] Add the missing documents and parameters of MongoDB CDC.

---

docs/content.zh/docs/connectors/flink-sources/db2-cdc.md
docs/content.zh/docs/connectors/flink-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/flink-sources/oceanbase-cdc.md
docs/content.zh/docs/connectors/flink-sources/oracle-cdc.md
docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md
docs/content.zh/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/flink-sources/db2-cdc.md
docs/content/docs/connectors/flink-sources/mongodb-cdc.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/flink-sources/oceanbase-cdc.md
docs/content/docs/connectors/flink-sources/oracle-cdc.md
docs/content/docs/connectors/flink-sources/postgres-cdc.md
docs/content/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content/docs/connectors/pipeline-connectors/mysql.md

Add doc for https://issues.apache.org/jira/browse/FLINK-36315 and already added MySQLCDC source metrics.

[FLINK-37231] Add doc for Source metrics.

---

docs/content.zh/docs/connectors/pipeline-connectors/elasticsearch.md
docs/content/docs/connectors/pipeline-connectors/elasticsearch.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/main/java/org/apache/flink/cdc/connectors/elasticsearch/config/ElasticsearchSinkOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/main/java/org/apache/flink/cdc/connectors/elasticsearch/serializer/ElasticsearchEventSerializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/main/java/org/apache/flink/cdc/connectors/elasticsearch/sink/ElasticsearchDataSink.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/main/java/org/apache/flink/cdc/connectors/elasticsearch/sink/ElasticsearchDataSinkFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/main/java/org/apache/flink/cdc/connectors/elasticsearch/sink/ElasticsearchDataSinkOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/test/java/org/apache/flink/cdc/connectors/elasticsearch/sink/ElasticsearchDataSinkFactoryTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/src/test/java/org/apache/flink/cdc/connectors/elasticsearch/sink/ElasticsearchEventSerializerTest.java

Support Elasticsearch sink to write into different indexes based on a specific field.

[FLINK-36698][pipeline-connector][elasticsearch] Elasticsearch Pipeline Connector support index sharding

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/converters/MysqlDebeziumTimeConverterITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlMultipleTablesRenamingITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/SpecificStartingOffsetITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTimezoneITCase.java

This closes FLINK-37306.
The failing test cases were introduced in #3298 and #3876 (and more), but has not been exposed until we decided to run CI test cases in random timezones (#3650).
MySQL docker container runs in UTC timezone by default, but `MySQLSourceITCase#testSourceMetrics` didn't specify `serverTimeZone` option explicitly like other test cases. As a result, running test cases in non-UTC timezone will fail with the following error:
> org.apache.flink.table.api.ValidationException: The MySQL server has a timezone offset (0 seconds ahead of UTC) which does not match the configured timezone GMT+XX:XX. Specify the right server-time-zone to avoid inconsistencies for time-related fields.
These cases need to run MySQL container in specific timezones, so they all have a method called …

[FLINK-37306][tests] Fix MySQLSourceITCase failure in non-UTC timezone

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplier.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java

Repeat step：
1. ALTER TABLE table_name add  COLUMN new_first_column bigint first
2. throw ArrayIndexOutOfBoundsException(Because the [add column first] event will be converted into an [add column before] event, ArrayIndexOutOfBoundsException is thrown when getting the existingColumnIndex)
log:
```
2025-02-19 11:32:16,586 INFO  org.apache.flink.cdc.runtime.operators.schema.regular.SchemaCoordinator [] - All sink subtask have flushed for table dw_app.cdc_sink19. Start to apply schema change request: 
SchemaChangeRequest{tableId=dw_app.cdc_sink19, schemaChangeEvent=AddColumnEvent{tableId=dw_app.cdc_sink19, addedColumns=[ColumnWithPosition{column=`new_first_column` BIGINT, position=BEFORE, existedColumnName=first_column}]}, subTaskId=0}
that extracts to: …
```

[FLINK-37348][pipeline-paimon] fix paimon ArrayIndexOutOfBoundsException when add column first

---

.github/workflows/flink_cdc_base.yml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/converters/MysqlDebeziumTimeConverterITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/SpecificStartingOffsetITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTimezoneITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/polardbx/PolardbxCharsetITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/polardbx/PolardbxSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/log4j2-test.properties

As noted in https://github.com/apache/flink-cdc/actions/runs/13623293435/job/38139886612?pr=3912, if JVM timezone is randomly set to GMT+0:00, it will be "smartly" converted to `"GMT"` (w/o offset part). As a result, we're configuring MySQL to start up with an empty timezone string, causing the CI failure.
Extra checking has been added to cover such case.

[hotfix][tests] Fix MySQL test case failure in exact UTC timezone

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java

This closes [FLINK-37409](https://issues.apache.org/jira/browse/FLINK-37409).

[FLINK-37409][cdc-connector/mysql] Catch throwable to exit reading binlog when error occurs

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaCoordinator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/event/SchemaChangeResponse.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/sink/DataSinkOperatorWithSchemaEvolveTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/testutils/operators/RegularEventOperatorTestHarness.java

This closes FLINK-37278.
Currently, regular SE topology uses the following process to drain existing `DataChangeEvent`s in the pipeline:
1. SchemaOperator ("client") emits `FlushEvent` to downstream.
2. The "client" keeps polling the SchemaCoordinator ("server") with 1-second interval.
3. The "server" rejects all requests from clients until it has collected enough `FlushSuccessEvent` notifications from Sink.
As a result, all schema change requests will took at least 1 second to finish, after at least  one polling interval.
---
This PR replaces the polling code with maintaining a pending schema change request queue, where SchemaCoordinator could manage all pending clients and effectively blocking them from handling upstream events. Schema evolution process could start immediately after …

[FLINK-37278] Optimize regular schema evolution topology's performance

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/TimestampTypeMetadataColumn.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSource.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/src/main/java/org/apache/flink/cdc/connectors/values/source/ValuesDataSourceHelper.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/ProjectionColumn.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/ProjectionColumnProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformExpressionCompiler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformExpressionKey.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformFilter.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/TransformFilterProcessor.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/TransformParser.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/TransformOperatorWithSchemaEvolveTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/UnifiedTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This close [FLINK-37429](https://issues.apache.org/jira/browse/FLINK-37429), [FLINK-37326](https://issues.apache.org/jira/browse/FLINK-37326)

[FLINK-37429][transform] Map each column name to a new name in generated expression

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceOptions.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceFactoryTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/config/JdbcSourceConfigFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/options/SourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/table/Db2TableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/table/Db2TableSourceFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/test/java/org/apache/flink/cdc/connectors/db2/table/Db2TableSourceFactoryTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/table/MongoDBTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/table/MongoDBTableSourceFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/table/MongoDBTableFactoryTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlTableSourceFactoryTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/table/OracleTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/table/OracleTableSourceFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/table/OracleTableSourceFactoryTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLTableFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLTableFactoryTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/table/SqlServerTableFactory.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/table/SqlServerTableSource.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/org/apache/flink/cdc/connectors/sqlserver/table/SqlServerTableFactoryTest.java

Update variables name that related to `scan.incremental.snapshot.unbounded-chunk-first.enabled` option.

[minor] Correct variables name according to option name.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlPipelineRecordEmitter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/log4j2-test.properties
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/sink/DataSinkWriterOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PreTransformOperator.java

Emit CreateTableEvent only when met the related SourceRecord to avoid downstream backpressure.

[FLINK-37386] Emit CreateTableEvent only when met the related SourceRecord.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonHashFunction.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonHashFunctionTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/PaimonMetadataApplierTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/test/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonSinkITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MySqlToPaimonE2eITCase.java

The original implementation can already support Paimon AppendOnly Table, I‘ve tried to optimize the logic of data shuffle and add testing here.

[FLINK-37452][pipeline-connector][paimon] Add support and test for AppendOnly table.

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaCoordinator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaOperator.java

[code clean] clean unuse code for schema operator&coordinator.

[code clean] clean unuse code for schema operator&coordinator.

---

docs/content.zh/docs/deployment/yarn.md
docs/content/docs/deployment/yarn.md
flink-cdc-cli/pom.xml
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/CliExecutor.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/CliFrontend.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/parser/PipelineDefinitionParser.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParser.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/utils/ConfigurationUtils.java
flink-cdc-cli/src/main/java/org/apache/flink/cdc/cli/utils/FlinkEnvironmentUtils.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/CliFrontendTest.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/parser/YamlPipelineDefinitionParserTest.java
flink-cdc-cli/src/test/java/org/apache/flink/cdc/cli/utils/ConfigurationUtilsTest.java
flink-cdc-composer/pom.xml
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/PipelineDeploymentExecutor.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/FlinkPipelineComposer.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/deployment/ComposeDeployment.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/deployment/ComposeDeploymentFactory.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/deployment/K8SApplicationDeploymentExecutor.java
flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/deployment/YarnApplicationDeploymentExecutor.java
flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/deployment/ComposeDeploymentTest.java
flink-cdc-e2e-tests/flink-cdc-e2e-utils/src/test/java/org/apache/flink/cdc/common/test/utils/TestUtils.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/MysqlE2eWithYarnApplicationITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestOnYarnEnvironment.java

hi @Mrart ,I merged your [PR](https://github.com/apache/flink-cdc/pull/3599) and tested it, but found some problem,i fixed it and added some tests.
flink-cdc-pipeline is a great feature, but currently only supports yarn-session in yarn. I think the cdc-community should support application mode as soon as possible so that users can promote the use of pipeline features within the company.
main changes of this PR are:
1. Added CliExecutor#main method as the program entry of application mode, because in application mode, the main method runs in the cluster
2. org.apache.flink.core.fs.Path replaces java.nio.file.Path, because additionalJars may be on the remote hdfs or oss
3. MysqlE2eWithYarnApplicationITCase is the flink yarn application test class, which will start yarnminicluster to submit …

[FLINK-35360] support Flink cdc pipeline Yarn application mode

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/utils/PostgresQueryUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresDialectTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresScanFetchTaskTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/reader/PostgresSourceReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/testutils/TestTable.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/testutils/TestTableId.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/resources/ddl/customer.sql

There are two problems in the code:
1. The table name passed to `to_regclass()` isn't quoted, so the upper-case letters get lower-cased.
2. The column names used in snapshot queries aren't quoted, so the upper-case letters get lower-cased.
There's also a minor issue with the `quote()` implementation that it doesn't double the double quotes. So if the table name or column name contains double quote, it will result in a SQL syntax error.
1. Instead of quoting the table name passed to `to_regclass()`, pass the schema name and table name individually. This way, they are interpreted as literals don't get automatically lower-cased.
2. Use prepared statement parameters in the query against `pg_class`. Otherwise, the table and schema name would have to be additionally quoted.
3. Quote column …

[FLINK-37371] Postgres CDC incremental source fails to handle upper-case table and column names

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonEventSink.java

BucketWrapper#getBucket is use to shuffle DataChangeEvent to avoid multiple subtasks writting in the same bucket.
However, in many cases, most tables may only have a few buckets, this way, the data will all fall on subtask1, subtask2... even if we have configured a high parallelism.
So I suggest allocating based on bucket+hash of TableId during shuffle, This way, there will be no conflict and data skew can be avoided to a certain extent.

[FLINK-37572] Shuffle Event by bucket and tableid to avoid data skew.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonWriter.java

Set waitCompaction=true in PaimonWriter only when deletion-vectors.enabled of table option is true.

[FLINK-37577][paimon] Set waitCompaction=true in PaimonWriter only when deletion-vectors.enabled option enabled

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/src/main/java/org/apache/flink/cdc/connectors/doris/sink/DorisSchemaChangeManager.java

Fix deprecated method usage in DorisSchemaChangeManager
```
org.apache.doris.flink.catalog.doris.DorisSystem#identifier
/** @deprecated */
@Deprecated
public static String identifier(String name) {
return DorisSchemaFactory.identifier(name);
}

[minor][pipeline-connectors][doris]Fix deprecated method usage in DorisSchemaChangeManager

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/SnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/splitter/ChunkRange.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/splitter/JdbcSourceChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/ChunkRange.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlChunkSplitter.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlChunkSplitterTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java

Fix [FLINK-37484](https://issues.apache.org/jira/browse/FLINK-37484), unevenly chunk split also enables unbounded-chunk-first.enabled.

[FLINK-37484][cdc-connector] unevenly chunk split also enables unbounded-chunk-first.enabled.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlAncientDateAndTimeITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/ddl/ancient_date_and_time.sql
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/docker/server-allow-ancient-date-time/my.cnf
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/org/apache/flink/cdc/debezium/event/DebeziumEventDeserializationSchema.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/org/apache/flink/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlAncientDateAndTimeITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/table/MySqlAncientDateAndTimeITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/ddl/ancient_date_and_time.sql
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/resources/docker/server-allow-ancient-date-time/my.cnf

Originally reported by @WuChongYong.
---
Currently, MySQL connector couldn't properly handle Date and DateTime records prior to 1970-01-01 (Unix epoch).
* DateTime records in Year 0000 are always null.
> This behavior is actually expected, since 0000 A.D. does not exist. Common Era starts at Year 0001.
> This could not be easily fixed since lots of libraries including MySQL connector and Java `Calendar` does not really support Year 0000 well (will be converted to 0001 automatically).
* DateTime Records between Year 0001 and 0099 are Shifted to 1970 and 2069.
> This could be overridden by `debezium.enable.time.adjuster` option.
* DateTime Records between 0100 and 1969 with precision digits are not serializable.
> This is caused by a glitch in `RowDataDebeziumDeserializeSchema` and …

[FLINK-37000] Fix MySQL CDC could not handle datetime prior to 1970 properly

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/src/test/java/org/apache/flink/cdc/connectors/kafka/json/debezium/DebeziumJsonSerializationSchemaTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/utils/JdbcChunkUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/utils/ChunkUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssignerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/util/ChunkUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/source/OracleSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/org/apache/flink/cdc/connectors/postgres/source/utils/ChunkUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/org/apache/flink/cdc/connectors/sqlserver/source/SqlServerSourceITCase.java

This close https://github.com/apache/flink-cdc/pull/3922.
MySQL CDC connector supports this feature from flink cdc v3.2
Now, other connectors that support incremental snapshot allow any columns as chunk key column
apache jira: https://issues.apache.org/jira/browse/FLINK-37332
pr for docs: https://github.com/apache/flink-cdc/pull/3924
cc. @gtk96 @leonardBang @lvyanquan

[FLINK-37332] Support any column as chunk key column (postgres, orcale, db2, sqlserver) #3922

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/PostgreSQLSourceTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/PostgresTestBase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/NewlyAddedTableITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceExampleTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/reader/PostgresSourceReaderTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLConnectorITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/table/PostgreSQLSavepointITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/resources/ddl/column_type_test.sql

As discussed in http://issues.apache.org/jira/browse/FLINK-37696, the postgres 14 is most used version of postgres, thus this Jira will replace test image and use pgoutput.

[FLINK-37696][test][cdc-connector][postgres] replace postgres image to official pg 14 and adjust test to use pgoutput plugin

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/distributed/SchemaCoordinator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/distributed/SchemaOperator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/distributed/event/SchemaChangeRequest.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/distributed/event/SchemaChangeResponse.java

This closes FLINK-37578 and #3858.
There's a subtle sequential bug in both `SchemaCoordinator`s after a schema evolve coordination process finishes. Coordinator may finish operators' blocking state first before restoring internal state properly, which may accidentally expose unwanted internal states or freeze the entire pipeline job.
@linjianchang's optimization in #3858 is actually correct, however it increases the chance of this glitch. Baked the original commit into this PR to test if it works well.

[FLINK-37578] Fix distributed schema registry exposes bad internal state accidentally

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlTablePatternMatchingTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceTestBase.java

This closes FLINK-37507.
Currently, MySQL CDC pipeline connector will accidentally capture database that should have been excluded from capture RegExp list when scan.binlog.newly-added-table option is enabled. 
For example, `tables: db.\.*` will also include all tables in databases like `dbnew` (with the same common prefix `db`), which is unexpected.

[FLINK-37507] Fix MySQL CDC accidentally captures common-prefix database when `scan.binlog.newly-added-table` is enabled

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/src/test/java/org/apache/flink/cdc/connectors/oceanbase/OceanBaseTestUtils.java

This PR aim to fix tests which failed due to disk space, we propose to use lts docker image version instead of latest for test.

[FLINK-37706][source-connector/oceanbase][tests] Use lts docker image version instead of latest for test

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/meta/split/SourceSplitSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/test/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializerTest.java

This Pr do two things:
1. [hotfix][cdc-base] Fix split not serialize isSnapshotCompleted
2. Cp https://github.com/apache/flink-cdc/pull/2705.

[hotfix][cdc-base] Fix split not serialize isSnapshotCompleted

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/common/SchemaRegistry.java

OperatorCoordinator#resetToCheckpoint() is called even before OperatorCoordinator#start(). So we should check SchemaManager is null before we create a new one.

[FLINK-37713][runtime] Fix SchemaManager was recreated in SchemaRegistry after job failover.

---

flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

How to reproduct:
1. Source table has a column name `op_type` and its type is not String type.
YAML configuration:
```
transform:
- source-table: your_table
projection: \*, __data_event_type__ AS op_type
```

[FLINK-37587][runtime] Fix error when adding a column using transform which has the same column name with one column of source table.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/io/debezium/relational/RelationalTableFilters.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/org/apache/flink/cdc/debezium/table/DebeziumOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/config/MySqlSourceConfig.java

In binlog reading phase, we only use connectorConfig.getTableFilters().dataCollectionFilter() to filter Event.
However, if user has configured exclude.tables, we should use sourceConfig.getTableFilter() instead.

[FLINK-37566] Avoid processing events of excluded tables.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/reader/IncrementalSourceReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/pom.xml
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/source/reader/OracleSourceReaderTest.java

[FLINK-36742](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-36742)

[FLINK-36742][cdc-base][oracle] Filter unacked  split for no capture tables when task restore from state

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/functions/SystemFunctionUtils.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperatorTest.java
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

Cherry-picked from #3863.
Currently, transform built-in function `dateFormat` supports formatting `TIMESTAMP`s only, and any `NULL` value will cause the job failover entirely.

[FLINK-36973] DateFormat function supports LocalZonedTimestampData type

---

flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaCoordinator.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/schema/regular/SchemaOperator.java

This closes FLINK-37462.
As reported previously, FlinkParallelizedPipelineITCase.testRegularTablesSourceInMultipleParallelism test case fails frequently on GitHub Actions, but could not be reliably reproduced locally (perhaps because GHA runners are much more powerful).
By enabling verbose logging, the reason might be: we released responseFuture from SchemaOperator before clearing it from `pendingRequests` set. So if client proposes another request immediately after being responded, the request coming later might be removed accidentally.
`SchemaOperator`'s logging sequence has been modified to indicate current stage of schema change requests.
I've ran this test case repeatedly (17 times) in my forked repo (https://github.com/yuxiqian/flink-cdc/pull/121) to verify this change.

[FLINK-37462] Fix consecutive schema change requests might be overwritten

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/deployment/YarnApplicationDeploymentExecutor.java

Fix environment variable check for FLINK_CDC_HOME in YarnApplicationDeploymentExecutor.

[hotfix] Fix environment variable check for FLINK_CDC_HOME in YarnApplicationDeploymentExecutor.

---

flink-cdc-composer/src/main/java/org/apache/flink/cdc/composer/flink/deployment/YarnApplicationDeploymentExecutor.java

Fix environment variable check for FLINK_CDC_HOME in YarnApplicationDeploymentExecutor.  (#4012)
(cherry picked from commit ceffbc0ea1a223bb2a81bd63c507be5978dee7f3)

[BP-3.4.0] Fix environment variable check for FLINK_CDC_HOME in YarnApplicationDeploymentExecutor. 

---

docs/content.zh/docs/connectors/flink-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/flink-sources/oracle-cdc.md
docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md
docs/content.zh/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/flink-sources/mongodb-cdc.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/flink-sources/oracle-cdc.md
docs/content/docs/connectors/flink-sources/postgres-cdc.md
docs/content/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content/docs/connectors/pipeline-connectors/mysql.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlDataSourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/reader/external/IncrementalSourceStreamFetcher.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReader.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java

close FLINK-37128.
It takes a long time to filter records to ensure exactly-once but when sink supports at-least-once, we can skip it.
When pipeline sink support at-least-once semantics, we can use `scan.incremental.snapshot.backfill.skip` to skip shouldEmit filter in binlog replay, which will accelerate binlog replay.
```
for (FinishedSnapshotSplitInfo splitInfo : finishedSplitsInfo.get(tableId)) {
if (RecordUtils.splitKeyRangeContains(
chunkKey, splitInfo.getSplitStart(), splitInfo.getSplitEnd())
&& position.isAfter(splitInfo.getHighWatermark())) {
return true;
}
}
```

[FLINK-37128][pipeline-connector/mysql] Binlog reader skip `shouldEmit` filter when snapshot reader skip backfill

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/test/java/org/apache/flink/cdc/connectors/base/source/assigner/state/PendingSplitsStateSerializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializerTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/utils/SqlServerConnectionUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/utils/SqlServerUtils.java

There are two problems:
1. Invalid SQL query for listing tables.
2. Invalid serialization of `TableId`s.
The latter is similar to #4000, which wasn't fixed consistently across the codebase.
Besides making the database name quoted in SQL, I modified the implementation of `SqlServerUtils#quote()` – it should not only enclose the name in square brackets but also escape the closing square bracket.

FLINK-37774: SQL Server CDC connector incorrectly handles special characters in database and table names

---

docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/pipeline-connectors/mysql.md

Align with the doc in English.

[FLINK-37223] Add the missing documents and parameters of MySQL CDC.

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/org/apache/flink/cdc/connectors/mongodb/source/reader/fetch/MongoDBStreamFetchTask.java

https://issues.apache.org/jira/browse/FLINK-37909
Update `heartbeatManager` so it has latest `changeStreamCursor`, when it changes in the running while loop.
Right now `heartbeatManager` is created with orginal  `changeStreamCursor` and not renewed whenever `changeStreamCursor` is updated upon Change stream cursor expiry.

[FLINK-37909-][cdc-connector-mongodb] Update MongoDBStreamFetchTask to renew heartbeatManager

---

docs/content.zh/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content/docs/connectors/flink-sources/sqlserver-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/table/SqlServerTableFactory.java

This documentation should have been updated as part of https://github.com/apache/flink-cdc/pull/1732.
See the actual code: https://github.com/apache/flink-cdc/blob/0faf387fd10a62b34a02447363e4cb0c098a7833/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/table/SqlServerTableFactory.java#L236-L242

FLINK-37891: Remove SQL Server CDC documentation for initial-only

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-iceberg/src/main/java/org/apache/flink/cdc/connectors/iceberg/sink/utils/IcebergTypeUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-iceberg/src/test/java/org/apache/flink/cdc/connectors/iceberg/sink/IcebergMetadataApplierTest.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-iceberg/src/test/java/org/apache/flink/cdc/connectors/iceberg/sink/v2/IcebergWriterTest.java

According to the Iceberg documentation https://iceberg.apache.org/docs/nightly/flink/#flink-to-iceberg, the CDC type TINYINT should be mapped to the Iceberg type INTEGER. However, in the code implementation of the Iceberg sink, I noticed that TINYINT is actually mapped to the Iceberg type BOOLEAN.

[FLINK-38141][pipeline-connector/iceberg] Fix iceberg connector incorrect type mapping

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/MySqlEventDeserializer.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/source/reader/MySqlPipelineRecordEmitter.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlPipelineITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/src/main/java/org/apache/flink/cdc/connectors/db2/source/utils/Db2Utils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/utils/StatementUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/main/java/org/apache/flink/cdc/connectors/oracle/source/utils/OracleUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/main/java/org/apache/flink/cdc/connectors/sqlserver/source/utils/SqlServerUtils.java

The vulnerability exists in the `quote()` function implementations that fail to properly escape special characters:
**Vulnerable Implementations:**
1. **MySQL** (Line 226):
```java
public static String quote(String dbOrTableName) {
    return "`" + dbOrTableName + "`";  // No backtick escaping
}
```
2. **SQL Server** (Line 367):
```java
public static String quote(String name) {
    return "[" + name + "]";  // No bracket escaping
}
```
3. **Oracle** (Line 232):
```java
public static String quote(String dbOrTableName) {
    return "\"" + dbOrTableName + "\"";  // No quote escaping
}
```
4. **DB2** (Line 358):
```java
public static String quote(String dbOrTableName) {
    return "\"" + dbOrTableName + "\"";  // No quote escaping
}
```
**Correct Implementation (PostgreSQL only):**
```java …
```

[minor] Fix potential sql connection statement issue

---

flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/pom.xml
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/FlussE2eITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/utils/PipelineTestEnvironment.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/ddl/mysql_inventory_wo_pk.sql
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/resources/docker/peek-fluss.sql

This is a follow up PR of #4053. Added a MySQL -> Fluss E2e test case.

[ci][fluss] Add MySQL to Fluss E2e IT case

---

flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/source/meta/split/FinishedSnapshotSplitInfo.java

Fix [FLINK-38184](https://issues.apache.org/jira/browse/FLINK-38184)
When I have a big Postgres source table(1 billion data), then the checkpoint will cost multiple minutes which will block the whole reading. The main cost is org.apache.flink.core.memory.DataOutputSerializer#getCopyOfBuffer.
In cdc framework, SplitSerializer will invoke DataOutputSerializer#getCopyOfBuffer for each finished split info
```java
// org.apache.flink.cdc.connectors.base.source.meta.split.SourceSplitSerializer#writeFinishedSplitsInfo
private void writeFinishedSplitsInfo(
List<FinishedSnapshotSplitInfo> finishedSplitsInfo, DataOutputSerializer out)
throws IOException {
final int size = finishedSplitsInfo.size();
out.writeInt(size);
for (FinishedSnapshotSplitInfo splitInfo : finishedSplitsInfo) { …
```

[FLINK-38184] one time of GetCopyOfBuffer is enough When serializing split.

---

docs/content.zh/docs/connectors/pipeline-connectors/mysql.md
docs/content/docs/connectors/pipeline-connectors/mysql.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/utils/MySqlTypeUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlFullTypesITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlMetadataAccessorITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/ddl/column_type_test.sql
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/resources/ddl/column_type_test_mysql8.sql

In MySQL, LONG and LONG VARCHAR map to the MEDIUMTEXT data type. MySQL-pipeline-connector should support this type. Refer to the official MySQL documentation https://dev.mysql.com/doc/refman/9.0/en/blob.html .

[FLINK-38164][pipeline-connector/mysql] support mysql long and long varchar type

---

docs/content.zh/docs/connectors/flink-sources/db2-cdc.md
docs/content.zh/docs/connectors/flink-sources/mongodb-cdc.md
docs/content.zh/docs/connectors/flink-sources/mysql-cdc.md
docs/content.zh/docs/connectors/flink-sources/oracle-cdc.md
docs/content.zh/docs/connectors/flink-sources/postgres-cdc.md
docs/content.zh/docs/connectors/flink-sources/sqlserver-cdc.md
docs/content/docs/connectors/flink-sources/db2-cdc.md
docs/content/docs/connectors/flink-sources/mongodb-cdc.md
docs/content/docs/connectors/flink-sources/mysql-cdc.md
docs/content/docs/connectors/flink-sources/oracle-cdc.md
docs/content/docs/connectors/flink-sources/postgres-cdc.md
docs/content/docs/connectors/flink-sources/sqlserver-cdc.md
flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/src/main/java/org/apache/flink/cdc/connectors/base/options/SourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/config/MySqlSourceOptions.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/source/fetch/PostgresScanFetchTaskTest.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/src/test/java/org/apache/flink/cdc/connectors/sqlserver/source/reader/fetch/SqlServerScanFetchTaskTest.java

Enable scan.incremental.snapshot.unbounded-chunk-first by default for improved stability.

[FLINK-37828] Enable scan.incremental.snapshot.unbounded-chunk-first by default for improved stability

---

flink-cdc-composer/src/test/java/org/apache/flink/cdc/composer/flink/FlinkPipelineTransformITCase.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/TransformE2eITCase.java
flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/parser/JaninoCompiler.java
flink-cdc-runtime/src/main/resources/saffron.properties
flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/TransformParserTest.java

This closes FLINK-37905.
As reported by @ruanhang1993, any non-ascii string literals in transform expressions will be encoded into something like `"&'\xxxx"`, which is unexpected since Unicodes are fully supported in Flink SQL expressions.
+@aiwenmo

[FLINK-37905] Fix transform failure with non-ascii string literals

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/source/MongoDBFullChangelogITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/source/MongoDBParallelSourceITCase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/utils/MongoDBTestUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceTestBase.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/src/test/java/org/apache/flink/cdc/connectors/oracle/testutils/OracleTestUtils.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/test/java/org/apache/flink/cdc/connectors/postgres/testutils/PostgresTestUtils.java

This closes FLINK-37963.
Occasionally, test cases related to triggering JM failover might fail, with an NPE thrown when manipulating jobManagerLeaderServices (like https://github.com/apache/flink-cdc/actions/runs/15509047609/job/43667549280).
It is likely to be caused by uninitialised JobManagerService and could be circumvented by invoking `EmbeddedHaServices#getOrCreateJobManagerService` manually.

[FLINK-37963] Fix potential NPE when triggering JobManager failover prematurely

---

flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/main/java/org/apache/flink/cdc/connectors/mysql/source/offset/BinlogOffset.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/debezium/reader/BinlogSplitReaderTest.java

The `compareTo` method in `BinlogOffset` would throw a NullPointerException if the filename field was null. This could happen in scenarios like reading from the latest offset where the initial offset might not have a filename.
This commit updates the comparison logic to safely handle null filenames.A new test, `testReadBinlogWithoutGtidFromLatestOffset`, is also introduced to cover this specific case and verify the solution.

[FLINK-37835] Fix NoPointException when start with latest-offset.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-postgres/src/main/java/org/apache/flink/cdc/connectors/postgres/factory/PostgresDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-postgres/src/test/java/org/apache/flink/cdc/connectors/postgres/factory/PostgresDataSourceFactoryTest.java
flink-cdc-e2e-tests/flink-cdc-pipeline-e2e-tests/src/test/java/org/apache/flink/cdc/pipeline/tests/PostgresE2eITCase.java

Fix [FLINK-38188](https://issues.apache.org/jira/browse/FLINK-38188)
Fix incorrect validation logic in `getValidateDatabaseName` method that causes validation to fail when all tables have the same database name.
- Fix the validation condition in `PostgresDataSourceFactory.getValidateDatabaseName()` method
- Change `!dbName.equals(currentDbName)` to `dbName.equals(currentDbName)` to correctly validate that all tables must have the same database name
This change is already covered by existing tests, or verify manually by:
- Configure multiple PostgreSQL tables with the same database name
- Verify that validation passes instead of throwing IllegalStateException
- Dependencies (does it add or upgrade a dependency): no
- The public API, i.e., is any changed class annotated with …

[FLINK-38188][pipeline-connector][postgres]  Fix database name validation logic in PostgresDataSourceFactory

---

.github/workflows/build_docs.yml

Fix error in https://github.com/apache/flink-cdc/actions/runs/16954053615, refer to https://github.com/apache/incubator-gluten/pull/10373/files.
Error message:
```
The action burnett01/rsync-deployments@5.2 is not allowed in apache/flink-cdc because all actions must be from a repository owned by your enterprise, created by GitHub, verified in the GitHub Marketplace, or match one of the patterns: 1Password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0, AdoptOpenJDK/install-jdk@*, BobAnkh/auto-generate-changelog@*, DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e, DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8, EnricoMi/publish-unit-test-result-action@*, JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b …
```

[hotfix][doc] Update uses of Upload documentation in build_docs.yml.

---

docs/content.zh/docs/connectors/pipeline-connectors/postgres.md
docs/content/docs/connectors/pipeline-connectors/postgres.md
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-postgres/src/test/java/org/apache/flink/cdc/connectors/postgres/source/PostgresFullTypesITCase.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-postgres/src/test/resources/ddl/column_type_test.sql
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/org/apache/flink/cdc/debezium/event/DebeziumEventDeserializationSchema.java
flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/org/apache/flink/cdc/debezium/event/DebeziumSchemaDataTypeInference.java

[FLINK-38278][postgres-pipeline] supported array type field.

[FLINK-38278][postgres-pipeline] supported array type field.

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/main/java/org/apache/flink/cdc/connectors/mysql/factory/MySqlDataSourceFactory.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlTablePatternMatchingTest.java

Ignore trailing spaces in table capturing rules like `tables:  foo.bar , foo.baz `.
This is not actually completely forward compatible, but we believe that using spaces in table names is very dangerous(could not guarantee that all downstream systems support this configuration).
For those who want to capture a table with space in table name, they can use `\s` to replace the ` `.

[FLINK-38358][pipeline-connector][mysql] Ignore trailing spaces in table capturing rules.

---

flink-cdc-dist/src/main/flink-cdc-bin/bin/flink-cdc.sh

I was stuck with this issue for a while when deploying CDC pipelines on my cluster. It seems that it is not convenient to get .jar files only at the first level of depth, so I want to fix it and add a more convenient search for files.
Add all-depth search for .jar files

[minor][improvement] Add subdirectory scrapping to add all .jar in classpath

---

flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-iceberg/src/main/java/org/apache/flink/cdc/connectors/iceberg/sink/utils/IcebergTypeUtils.java
flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-iceberg/src/test/java/org/apache/flink/cdc/connectors/iceberg/sink/v2/IcebergWriterTest.java

flink-cdc run with mysql -> iceberg, column type in mysql is TINYINT and the value is
negative( like -1), write to iceberg table the value change to 65535.
Because -1 pack to "\xff\xff" (short, 2bytes). But in code uppack by int, is get "\xff\xff\x00\x00" (int, 4bytes, got more \x00\x00 from data binary), then get 65535.

[FLINK-38440][pipeline-connector][iceberg] fixed iceberg write SMALLINT/TINYINT data wrong
